<a href="https://colab.research.google.com/github/anshuman4515/Capstone-project/blob/main/Copy_of_data_preprocessing_house.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('/content/independent-house - independent-house.csv')
df.sample(5)

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
824,5 Bedroom House for sale in Greenwood City,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,17 Crore,"₹ 37,777/sq.ft.",(418 sq.m.) Plot Area,Plot area 4500(418.06 sq.m.),5 Bedrooms,8 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room","0000, Greenwood City, Gurgaon, Haryana",3 Floors,North-East,1 to 5 Year Old,"['Huda city centre metro station', 'Axis bank ...",Ultra luxury kothi for sale in greenwood city ...,"['1 Water Purifier', '11 Fan', '1 Fridge', '1 ...","['Centrally Air Conditioned', 'Water purifier'...","['Environment4.5 out of 5', 'Lifestyle4 out of...",T68644254
835,6 Bedroom House for sale in Sushant Lok Phase 3,https://www.99acres.com/6-bhk-bedroom-independ...,Ansal Sushant Residency,4.6 Crore,"₹ 17,037/sq.ft.",(251 sq.m.) Plot Area,Plot area 300(250.84 sq.m.),6 Bedrooms,6 Bathrooms,3 Balconies,"Pooja Room,Study Room,Servant Room,Store Room","C-Block, Sushant Lok Phase 3, Gurgaon, Haryana",3 Floors,East,10+ Year Old,"['Radhakrishna Shani Mandir', 'Sanatan Dharm M...",Best 6 bhk villa for modern-Day lifestyle is n...,"['1 Water Purifier', '1 Fan', '1 Fridge', '1 E...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5...",K69632360
382,2 Bedroom House for sale in Sector 13 Gurgaon,https://www.99acres.com/2-bhk-bedroom-independ...,NaN,1.5 Crore,"₹ 10,518/sq.ft.",(132 sq.m.) Plot Area,Plot area 1426(132.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,"Pooja Room,Study Room","Hno. 26, A Block, Sector 13 Gurgaon, Gurgaon, ...",3 Floors,South-West,10+ Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...","The house is located in sanjay gram, sector 13...",NaN,"['Water Storage', 'Waste Disposal']","['Environment4 out of 5', 'Lifestyle5 out of 5...",O69220384
974,7 Bedroom House for sale in Sector 48 Gurgaon,https://www.99acres.com/7-bhk-bedroom-independ...,Eldeco Mansionz,4.75 Crore,"₹ 20,299/sq.ft.",(217 sq.m.) Plot Area,Plot area 260(217.39 sq.m.),7 Bedrooms,7 Bathrooms,3 Balconies,Study Room,"36b Spaze I Tech Park Shona Road, Sector 48 Gu...",2 Floors,North-East,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",It is a good property. Near by all amenities l...,"['7 Wardrobe', '7 Fan', '1 Exhaust Fan', '6 Ge...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Safety4 out of 5', ...",B70111024
247,6 Bedroom House for sale in Palam Vihar,https://www.99acres.com/6-bhk-bedroom-independ...,NaN,5 Crore,"₹ 15,384/sq.ft.",(302 sq.m.) Carpet Area,Carpet area: 3250 (301.93 sq.m.),6 Bedrooms,6 Bathrooms,2 Balconies,NaN,"Palam Vihar, Palam Vihar, Gurgaon, Haryana",1 Floors,South,undefined,NaN,Recognised as greenest area in palam vihar pal...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5...",G69905858

In [4]:
df.shape

(1095, 21)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1095 non-null   object
 1   link             1095 non-null   object
 2   society          471 non-null    object
 3   price            968 non-null    object
 4   rate             1054 non-null   object
 5   area             1095 non-null   object
 6   areaWithType     987 non-null    object
 7   bedRoom          987 non-null    object
 8   bathroom         987 non-null    object
 9   balcony          987 non-null    object
 10  additionalRoom   589 non-null    object
 11  address          1031 non-null   object
 12  noOfFloor        967 non-null    object
 13  facing           674 non-null    object
 14  agePossession    987 non-null    object
 15  nearbyLocations  913 non-null    object
 16  description      1036 non-null   object
 17  furnishDetails   743 non-null    object
 18  features         674 non-null    object
 19  rating           907 non-null    object
 20  property_id      1036 non-null   object
dtypes: object(21)
memory usage: 179.8+ KB

In [6]:
df.isnull().sum()

property_name        0
link                 0
society            624
price              127
rate                41
area                 0
areaWithType       108
bedRoom            108
bathroom           108
balcony            108
additionalRoom     506
address             64
noOfFloor          128
facing             421
agePossession      108
nearbyLocations    182
description         59
furnishDetails     352
features           421
rating             188
property_id         59
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(13)

In [8]:
df = df.drop_duplicates()

In [9]:
df.head()

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/10-bhk-bedroom-indepen...,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,https://www.99acres.com/21-bhk-bedroom-indepen...,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/12-bhk-bedroom-indepen...,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [10]:
df.drop(columns=['link','property_id'], inplace=True)

In [11]:
df.rename(columns={'rate':'price_per_sqft'},inplace=True)
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [12]:
df['society'].value_counts()

society
Emaar MGF Marbella                                   26
International City by SOBHA Phase 2                  26
Vipul Tatvam Villa                                   25
International City by Sobha Phase 1                  23
Unitech Uniworld Resorts                             14
DLF City Plots Phase 2                               11
Unitech Espace                                       11
DLF City Plots                                       11
Eldeco Mansionz                                       9
Bptp Visionnaire                                      8
Uppal Southend4.0 ★                                   8
Not Applicable                                        7
Ansals Palam Vihar                                    6
Sushant Lok 1 Builder Floors                          6
Experion Windchants3.8 ★                              5
DLF City Phase 1                                      5
DLF Alameda                                           4
Ansals Florence Villa                                 4
DLF New Town Heights 24.0 ★                           4
nul                                                   4
Unitech Nirvana Birch Court                           4
Unitech Aspen Greens                                  4
Vatika India Next4.1 ★                                4
Ansal Sushant Lok Plots4.1 ★                          4
DLF City Plots Phase 3                                3
Puri Diplomatic Greens4.0 ★                           3
Tata Primanti4.1 ★                                    3
Bestech Park View Ananda4.2 ★                         3
Housing Board Colony                                  3
Central Park Flower Valley                            3
Anant Raj Estates                                     3
Rattan Garden                                         3
BPTP Astaire Gardens3.7 ★                             3
Silverglades Tarudhan Valley Golf Resort              3
SS Aaron Ville                                        3
Eros Rosewood City4.0 ★                               3
Sector 14 RWA                                         3
Vatika Signature Villas                               3
Eros Rosewood Villas                                  3
HUDA Ashok Vihar Phase 13.9 ★                         3
Malibu Towne                                          3
Palam Vihar Extension West Zone RWA                   3
Hans Enclave                                          3
Spaze Privy3.9 ★                                      2
Project Mianwali Colony                               2
Project Housing Board Colony                          2
Sobha City                                            2
Ardee City3.8 ★                                       2
DLF City Plots Phase 4                                2
Suncity Essel Towers4.2 ★                             2
Ansal Sushant Residency                               2
DLF South City 1                                      2
Luxury DLF City Floors                                2
Ansal API Esencia3.7 ★                                2
Emaar Emerald Hills4.1 ★                              2
shivpuri                                              2
Unitech Deerwood Chase                                2
Suncity Township4.1 ★                                 2
Emaar The Palm Springs                                2
Nirvana Cedar Crest                                   2
Satya The Hermitage3.5 ★                              2
Bhim Garh Kheri                                       2
Signature Global City 92                              2
SS Hibiscus                                           2
Unitech Palms South City 1                            2
BPTP Pedestal                                         2
Saksham Welfare Association                           2
Sector 38 RWA                                         2
IFFCO Nagar and 17B RWA                               2
RWA Sector 46                                         2
Unitech Escape3.8 ★                                   2
Ninex City                                            1
My Home                                               1
Signature Global Park4.0 ★                            1
DLF New Town Heights3.7 ★                             1
All Punjabi Welfare Association                       1
FLOOR WISE DESIGNER KOTHI                             1
sector 37                                             1
Grover Homes Sec 4                                    1
Ansal Heights3.2 ★                                    1
rajendra park sec 105                                 1
Ashok Vihar Phase 3 Gurgaon                           1
secter 16a daultabad faridabad house no 313           1
Prem Kunj                                             1
Farrukhnagar                                          1
Sector-17C                                            1
Anant Raj Manor Villas                                1
huda sector-56 gurgaon                                1
private house                                         1
patel nager house no 927/5                            1
Om Nagar, Sector-11                                   1
Bhawani enclave                                       1
Smart World Gems                                      1
Ganpati Heights Apartment                             1
Hero Homes                                            1
Jacobpura Gurugram                                    1
Anand Garden, Sector-105                              1
RK Excelo                                             1
Laxmi Garden Sector-11                                1
shree krishna homes                                   1
mian wali                                             1
Shri Shyam Residency                                  1
ROW HOUSE                                             1
HUDA Plot Sector 38                                   1
Madan puri                                            1
Ansal Celebrity Homes                                 1
HUDA Housing Board Colony4.1 ★                        1
Surat nagar phase 2                                   1
bhim nagar, sector 6                                  1
Emaar MGF The Palm Drive4.1 ★                         1
Tulip Ivory3.5 ★                                      1
Huda Plots                                            1
Vatika Sovereign Next                                 1
MANOHAR NAGAR                                         1
Laxman vihar phase 2                                  1
Anamika Enclave                                       1
Surendra Homes Dayanand Colony                        1
DLF The Grove                                         1
DLF Garden City Floors                                1
DLF The Arbour                                        1
house number B-34                                     1
ATS Tourmaline3.9 ★                                   1
Rajendra Park Gurgaon                                 1
DLF Gardencity Enclave                                1
Vipul World3.9 ★                                      1
Greenopolis                                           1
Ansal Esencia Sovereign Floors                        1
Nirmal Enclave, Maruti Kunj Road                      1
jacob pura                                            1
mahavir pura                                          1
Raj Villas                                            1
Shivaji Nagar Residential                             1
Naman Residency                                       1
Bhim Nagar Society                                    1
Sai Kripa Floors 5                                    1
DLF City Plot Phase 4                                 1
Krishna Palace                                        1
Indiabulls Centrum Park3.7 ★                          1
Jacobpura                                             1
Huda Flats                                            1
Tulip Yellow                                          1
Sector 15 Part 2 RWA                                  1
Ansal                                                 1
Nitin Vihar                                           1
rattan vihar rajendra park                            1
Signature Global City 63A                             1
Landmark House                                        1
Ashok vihar phase III Extension                       1
Adani Brahma Samsara4.2 ★                             1
DLF City Plot Phase 3                                 1
Anshul                                                1
Sare Crescent Parc Royal Greens Phase 1               1
Suncity Avenue 76                                     1
Sheetla Enclave                                       1
sneh vihar                                            1
SS Omnia                                              1
Ireo Victory Valley4.1 ★                              1
4S Aradhya Homes                                      1
Ansal API Spanish Court                               1
Central Park Flower Valley Cerise Floors              1
Birla Navya                                           1
cloudnine cottages                                    1
nirvana country                                       1
Kothi                                                 1
u block dlf phase 3 road no 21                        1
Signature Global City 81                              1
Central Park                                          1
Ansal Florence Super                                  1
DLF Floors Phase 3                                    1
Signature Global City                                 1
Smart World Orchard                                   1
Unitech South City 23.8 ★                             1
Ireo Victory Valley4.0 ★                              1
Independent House Sector 45                           1
Vatika The Seven Lamps3.8 ★                           1
Unitech Greenwood City3.6 ★                           1
Nirvana Country                                       1
Ansal Sushant Lok                                     1
Satya The Legend3.8 ★                                 1
DLF Pink Town House4.0 ★                              1
Vatika Independent Floors3.8 ★                        1
Arjun Marg/ Sector- 26 Phase- 1/ Golf Course Road     1
The Laburnum                                          1
Ansal Sushant Lok 2                                   1
Sector 57 Huda                                        1
Godrej Meridien                                       1
Huda                                                  1
Huda Floor                                            1
Name: count, dtype: int64

In [13]:
df['society'].value_counts().shape

(188,)

In [14]:
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [15]:
df['society'].value_counts().shape

(186,)

In [16]:
df['society'] = df['society'].str.replace('nan','independent')

In [17]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [18]:
df['price'].value_counts()

price
3.5 Crore           19
5.5 Crore           17
6.5 Crore           16
6 Crore             14
4.5 Crore           13
5 Crore             13
8 Crore             13
50 Lac              13
75 Lac              13
70 Lac              13
7 Crore             12
8.5 Crore           12
85 Lac              12
1.5 Crore           11
4 Crore             11
90 Lac              10
Price on Request    10
2.25 Crore          10
45 Lac              10
60 Lac              10
10 Crore            10
2.5 Crore           10
9 Crore             10
12 Crore             9
2 Crore              9
80 Lac               9
9.5 Crore            9
1.1 Crore            9
1.7 Crore            9
1 Crore              8
1.6 Crore            8
11 Crore             8
6.75 Crore           8
4.6 Crore            8
3.75 Crore           7
1.2 Crore            7
55 Lac               7
40 Lac               7
1.3 Crore            7
12.5 Crore           7
95 Lac               7
65 Lac               7
1.35 Crore           7
2.1 Crore            7
7.5 Crore            6
6.25 Crore           6
3.25 Crore           6
2.95 Crore           6
10.5 Crore           6
13.5 Crore           6
3.6 Crore            6
2.75 Crore           6
1.45 Crore           6
5.7 Crore            6
4.25 Crore           6
1.15 Crore           6
16 Crore             6
15 Crore             5
3 Crore              5
1.25 Crore           5
5.6 Crore            5
38 Lac               5
4.75 Crore           5
7.25 Crore           5
35 Lac               5
2.8 Crore            5
1.8 Crore            5
18 Crore             4
13 Crore             4
4.35 Crore           4
17 Crore             4
3.3 Crore            4
5.8 Crore            4
9.25 Crore           4
1.4 Crore            4
1.65 Crore           4
3.2 Crore            4
5.75 Crore           4
37 Lac               4
4.7 Crore            4
11.5 Crore           4
6.8 Crore            4
2.4 Crore            4
42 Lac               4
8.25 Crore           4
5.25 Crore           4
20 Crore             3
1.95 Crore           3
4.45 Crore           3
62 Lac               3
5.65 Crore           3
82 Lac               3
2.2 Crore            3
6.95 Crore           3
3.85 Crore           3
1.55 Crore           3
2.3 Crore            3
3.1 Crore            3
1.85 Crore           3
92 Lac               3
5.15 Crore           3
32 Lac               3
34 Lac               3
49 Lac               3
1.16 Crore           3
7.35 Crore           3
2.9 Crore            3
3.4 Crore            3
1.9 Crore            3
4.3 Crore            3
8.4 Crore            3
7.2 Crore            3
19 Crore             3
6.4 Crore            3
11.95 Crore          2
1.05 Crore           2
14 Crore             2
11.25 Crore          2
6.3 Crore            2
30 Lac               2
10.45 Crore          2
66 Lac               2
36 Lac               2
26 Crore             2
11.75 Crore          2
8.49 Crore           2
2.55 Crore           2
3.55 Crore           2
3.15 Crore           2
9.9 Crore            2
15.5 Crore           2
58.25 Lac            2
2.15 Crore           2
67 Lac               2
3.05 Crore           2
1.75 Crore           2
48 Lac               2
10.85 Crore          2
7.1 Crore            2
58 Lac               2
4.95 Crore           2
19.5 Crore           2
3.65 Crore           2
10.55 Crore          2
3.35 Crore           2
89 Lac               2
3.51 Crore           2
6.6 Crore            1
6.2 Crore            1
5.9 Crore            1
8.8 Crore            1
1.87 Crore           1
4.12 Crore           1
5.35 Crore           1
5.85 Crore           1
7.05 Crore           1
2.68 Crore           1
2.7 Crore            1
10.75 Crore          1
61 Lac               1
18.25 Crore          1
2.35 Crore           1
8.6 Crore            1
9.55 Crore           1
9.8 Crore            1
4.99 Crore           1
9.85 Crore           1
1.18 Crore           1
9.01 Crore           1
15.1 Crore           1
1.04 Crore           1
25 Crore             1
8.7 Crore            1
15.5 Lac             1
12.39 Crore          1
7.49 Crore           1
55.11 Lac            1
68 Lac               1
4.65 Crore           1
6.1 Crore            1
1.72 Crore           1
52 Lac               1
78 Lac               1
1.52 Crore           1
2.58 Crore           1
8.95 Crore           1
13.2 Crore           1
51 Lac               1
53 Lac               1
63 Lac               1
7.69 Crore           1
22 Lac               1
7.5 Lac              1
3.12 Crore           1
11.3 Crore           1
3.69 Crore           1
4.02 Crore           1
3.93 Crore           1
29 Lac               1
3.08 Crore           1
18 Lac               1
24 Lac               1
98 Lac               1
83 Lac               1
7.99 Crore           1
5.4 Crore            1
65.8 Lac             1
18.02 Crore          1
96 Lac               1
13 Lac               1
69 Lac               1
2.43 Crore           1
74 Lac               1
3.09 Crore           1
44 Lac               1
47.5 Lac             1
59 Lac               1
1.39 Crore           1
3.87 Crore           1
2.6 Crore            1
1.34 Crore           1
46 Lac               1
9.54 Crore           1
14.75 Crore          1
8.1 Crore            1
27 Lac               1
24 Crore             1
7.46 Crore           1
17.3 Crore           1
18.9 Crore           1
47 Lac               1
71 Lac               1
52.5 Lac             1
1.44 Crore           1
3.71 Crore           1
1.07 Crore           1
5.2 Crore            1
42.75 Lac            1
22 Crore             1
4.15 Crore           1
8.9 Crore            1
4.49 Crore           1
8.81 Crore           1
6.81 Crore           1
59.95 Lac            1
3.99 Crore           1
18.5 Crore           1
27.5 Crore           1
8.31 Crore           1
6.21 Crore           1
1.83 Crore           1
5.1 Crore            1
5.46 Crore           1
10.56 Crore          1
2.01 Crore           1
3.9 Crore            1
5.88 Crore           1
52.75 Lac            1
12.25 Crore          1
46.75 Lac            1
9.4 Crore            1
10.3 Crore           1
8.45 Crore           1
6.15 Crore           1
2.47 Crore           1
3.7 Crore            1
18.4 Crore           1
4.4 Crore            1
7.3 Crore            1
7.6 Crore            1
2.65 Crore           1
99 Lac               1
11.29 Crore          1
1.27 Crore           1
11.58 Crore          1
8.48 Crore           1
8.2 Crore            1
4.31 Crore           1
3.49 Crore           1
2.99 Crore           1
9.19 Crore           1
1.64 Crore           1
9.35 Crore           1
4.05 Crore           1
8.75 Crore           1
5.51 Crore           1
23 Crore             1
2.45 Crore           1
7.85 Crore           1
5.3 Crore            1
10.8 Crore           1
31.5 Crore           1
4.1 Crore            1
7.65 Crore           1
6.46 Crore           1
6.44 Crore           1
7.8 Crore            1
3.8 Crore            1
7.45 Crore           1
7.42 Crore           1
6.09 Crore           1
2.98 Crore           1
Name: count, dtype: int64

In [19]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [20]:
df.shape

(1082, 19)

In [21]:
df[df['price'] == 'Price on Request']

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
295,2 Bedroom House for sale in Sector 8 Gurgaon,independent,Price on Request,NaN,(74 sq.m.) Built-up Area,Built Up area: 800 (74.32 sq.m.),2 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 8 Gurgaon, Gurgaon, Haryana",1 Floors,NaN,undefined,NaN,"1 bath, semi-Furnished, at sector 8 location g...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
296,3 Bedroom House for sale in Dharam Colony,independent,Price on Request,NaN,(93 sq.m.) Carpet Area,Carpet area: 1000 (92.9 sq.m.),3 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Dharam Colony, Gurgaon, Haryana",2 Floors,NaN,undefined,NaN,"2 bath, unfurnished, at dharam colony location...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
325,5 Bedroom House for sale in Laxman Vihar,independent,Price on Request,NaN,(167 sq.m.) Built-up Area,Built Up area: 1800 (167.23 sq.m.),5 Bedrooms,8 Bathrooms,3+ Balconies,NaN,"Phase 2, Laxman Vihar, Gurgaon, Haryana",2 Floors,North,undefined,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","8 bath, unfurnished, overlooking main road, no...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
326,3 Bedroom House for sale in Laxman Vihar,independent,Price on Request,NaN,(223 sq.m.) Built-up Area,Built Up area: 2400 (222.97 sq.m.)Carpet area:...,3 Bedrooms,4 Bathrooms,2 Balconies,NaN,"1248 B, Near Hanuman Mandir, Laxman Vihar, Gur...",2 Floors,NaN,undefined,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","4 bath, unfurnished, 1st floor (Of 2), 1 side ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
402,7 Bedroom House for sale in Rajendra Park,independent,Price on Request,NaN,(585 sq.m.) Built-up Area,Built Up area: 700 (585.29 sq.m.),7 Bedrooms,6 Bathrooms,3 Balconies,NaN,"Rajendra Park, Gurgaon, Haryana",4 Floors,NaN,5 to 10 Year Old,NaN,"6 bath, furnished, 2 side open, at rajendra pa...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
431,3 Bedroom House for sale in Ansal Plaza,independent,Price on Request,NaN,(40 sq.m.) Carpet Area,Carpet area: 429 (39.86 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Ansal Plaza, Sector 23, Ansal Plaza, Gurgaon, ...",4 Floors,NaN,undefined,NaN,Best in class property available at ansal plaz...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
494,2 Bedroom House for sale in Sheetla Colony,independent,Price on Request,NaN,(42 sq.m.) Plot Area,Plot area 50(41.81 sq.m.)Built Up area: 720 sq...,2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Sheetla Colony, Gurgaon, Haryana",2 Floors,NaN,undefined,NaN,"2 bath, semi-Furnished, at sheetla colony loca...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment3 out of 5', 'Lifestyle3 out of 5..."
569,5 Bedroom House for sale in Surat Nagar,independent,Price on Request,NaN,(54 sq.m.) Built-up Area,Built Up area: 65 (54.35 sq.m.),5 Bedrooms,2 Bathrooms,No Balcony,NaN,"Surat Nagar Phase 2, Sector 104, Surat Nagar, ...",2 Floors,NaN,undefined,NaN,5bhk residential house for resale in surat nag...,NaN,NaN,"['Environment3 out of 5', 'Lifestyle3 out of 5..."
595,2 Bedroom House for sale in Dharam Colony Block E,independent,Price on Request,NaN,(84 sq.m.) Built-up Area,Built Up area: 900 (83.61 sq.m.),2 Bedrooms,1 Bathroom,No Balcony,NaN,"Dharam Colony Block E, Gurgaon, Haryana",1 Floors,NaN,undefined,"['Palam triangle', 'Palam Vihar Vyapar kendra'...","1 bath, unfurnished, ground floor (Of 1), at d...",NaN,NaN,NaN
668,4 Bedroom House for sale in Madanpuri,independent,Price on Request,NaN,(167 sq.m.) Carpet Area,Carpet area: 1800 (167.23 sq.m.),4 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Madanpuri, Gurgaon, Haryana",2 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 1 side open, at madan pur...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [22]:
df = df[df['price'] != 'Price on Request']

In [23]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [24]:
def treat_price(x):
    try:
        if len(x) >= 2 and x[1] == 'Lac':
            return round(float(x[0]) / 100, 2)
        else:
            return float(x[0])
    except:
        return None

In [25]:
df['price'] = df['price'].str.split(' ').apply(treat_price)

In [26]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [27]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [28]:
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 22,222/sq.ft.     14
₹ 11,111/sq.ft.     12
₹ 33,333/sq.ft.     11
₹ 10,000/sq.ft.     10
₹ 37,037/sq.ft.      7
₹ 13,333/sq.ft.      7
₹ 30,556/sq.ft.      6
₹ 31,481/sq.ft.      6
₹ 26,235/sq.ft.      6
₹ 26,667/sq.ft.      6
₹ 8,000/sq.ft.       6
₹ 11,100/sq.ft.      5
₹ 5,000/sq.ft.       5
₹ 23,148/sq.ft.      5
₹ 8,889/sq.ft.       5
₹ 32,407/sq.ft.      5
₹ 23,333/sq.ft.      5
₹ 9,444/sq.ft.       5
₹ 9,722/sq.ft.       4
₹ 21,605/sq.ft.      4
₹ 34,722/sq.ft.      4
₹ 27,778/sq.ft.      4
₹ 15,625/sq.ft.      4
₹ 18,889/sq.ft.      4
₹ 35,000/sq.ft.      4
₹ 24,691/sq.ft.      4
₹ 25,000/sq.ft.      4
₹ 6,944/sq.ft.       4
₹ 32,222/sq.ft.      3
₹ 33,951/sq.ft.      3
₹ 36,111/sq.ft.      3
₹ 29,880/sq.ft.      3
₹ 100,000/sq.ft.     3
₹ 25,926/sq.ft.      3
₹ 5,555/sq.ft.       3
₹ 7,500/sq.ft.       3
₹ 10,556/sq.ft.      3
₹ 8,235/sq.ft.       3
₹ 13,889/sq.ft.      3
₹ 8,333/sq.ft.       3
₹ 12,222/sq.ft.      3
₹ 60,000/sq.ft.      3
₹ 6,666/sq.ft.       3
₹ 50,000/sq.ft.      3
₹ 14,815/sq.ft.      3
₹ 17,037/sq.ft.      3
₹ 15,555/sq.ft.      3
₹ 23,457/sq.ft.      3
₹ 8,444/sq.ft.       3
₹ 16,058/sq.ft.      3
₹ 11,250/sq.ft.      3
₹ 20,000/sq.ft.      3
₹ 44,444/sq.ft.      3
₹ 9,259/sq.ft.       3
₹ 12,000/sq.ft.      3
₹ 9,634/sq.ft.       2
₹ 45,833/sq.ft.      2
₹ 12,342/sq.ft.      2
₹ 38,580/sq.ft.      2
₹ 35,556/sq.ft.      2
₹ 24,155/sq.ft.      2
₹ 38,760/sq.ft.      2
₹ 38,194/sq.ft.      2
₹ 42,222/sq.ft.      2
₹ 59,259/sq.ft.      2
₹ 20,635/sq.ft.      2
₹ 17,187/sq.ft.      2
₹ 18,928/sq.ft.      2
₹ 13,622/sq.ft.      2
₹ 15,700/sq.ft.      2
₹ 12,027/sq.ft.      2
₹ 13,910/sq.ft.      2
₹ 12,500/sq.ft.      2
₹ 16,039/sq.ft.      2
₹ 19,708/sq.ft.      2
₹ 24,500/sq.ft.      2
₹ 25,562/sq.ft.      2
₹ 17,778/sq.ft.      2
₹ 4,444/sq.ft.       2
₹ 11,574/sq.ft.      2
₹ 1,859/sq.ft.       2
₹ 10,579/sq.ft.      2
₹ 42,194/sq.ft.      2
₹ 15,278/sq.ft.      2
₹ 201,388/sq.ft.     2
₹ 7,058/sq.ft.       2
₹ 7,718/sq.ft.       2
₹ 25,535/sq.ft.      2
₹ 21,124/sq.ft.      2
₹ 39,841/sq.ft.      2
₹ 17,284/sq.ft.      2
₹ 37,627/sq.ft.      2
₹ 48,148/sq.ft.      2
₹ 29,630/sq.ft.      2
₹ 35,185/sq.ft.      2
₹ 13,000/sq.ft.      2
₹ 32,328/sq.ft.      2
₹ 32,963/sq.ft.      2
₹ 3,857/sq.ft.       2
₹ 21,759/sq.ft.      2
₹ 24,306/sq.ft.      2
₹ 7,619/sq.ft.       2
₹ 10,101/sq.ft.      2
₹ 10,783/sq.ft.      2
₹ 19,000/sq.ft.      2
₹ 10,753/sq.ft.      2
₹ 20,833/sq.ft.      2
₹ 3,500/sq.ft.       2
₹ 15,257/sq.ft.      2
₹ 10,518/sq.ft.      2
₹ 27,461/sq.ft.      2
₹ 5,333/sq.ft.       2
₹ 14,444/sq.ft.      2
₹ 16,975/sq.ft.      2
₹ 75,000/sq.ft.      2
₹ 55,000/sq.ft.      2
₹ 9,000/sq.ft.       2
₹ 24,845/sq.ft.      2
₹ 12,963/sq.ft.      2
₹ 26,389/sq.ft.      2
₹ 7,407/sq.ft.       2
₹ 8,888/sq.ft.       2
₹ 12,444/sq.ft.      2
₹ 11,852/sq.ft.      2
₹ 21,242/sq.ft.      2
₹ 26,852/sq.ft.      2
₹ 7,777/sq.ft.       2
₹ 38,095/sq.ft.      2
₹ 39,062/sq.ft.      1
₹ 48,889/sq.ft.      1
₹ 10,838/sq.ft.      1
₹ 34,491/sq.ft.      1
₹ 28,782/sq.ft.      1
₹ 38,150/sq.ft.      1
₹ 13,034/sq.ft.      1
₹ 53,763/sq.ft.      1
₹ 14,000/sq.ft.      1
₹ 18,814/sq.ft.      1
₹ 15,000/sq.ft.      1
₹ 18,885/sq.ft.      1
₹ 19,125/sq.ft.      1
₹ 122,222/sq.ft.     1
₹ 28,490/sq.ft.      1
₹ 24,170/sq.ft.      1
₹ 32,593/sq.ft.      1
₹ 13,410/sq.ft.      1
₹ 9,374/sq.ft.       1
₹ 105,751/sq.ft.     1
₹ 31,008/sq.ft.      1
₹ 13,992/sq.ft.      1
₹ 33,129/sq.ft.      1
₹ 12,551/sq.ft.      1
₹ 13,359/sq.ft.      1
₹ 11,784/sq.ft.      1
₹ 4,333/sq.ft.       1
₹ 255,555/sq.ft.     1
₹ 24,912/sq.ft.      1
₹ 29,321/sq.ft.      1
₹ 102,941/sq.ft.     1
₹ 13,071/sq.ft.      1
₹ 24,444/sq.ft.      1
₹ 3,452/sq.ft.       1
₹ 481/sq.ft.         1
₹ 43,333/sq.ft.      1
₹ 8,181/sq.ft.       1
₹ 23,932/sq.ft.      1
₹ 79,365/sq.ft.      1
₹ 26,063/sq.ft.      1
₹ 29,974/sq.ft.      1
₹ 88,157/sq.ft.      1
₹ 92,857/sq.ft.      1
₹ 86,567/sq.ft.      1
₹ 26,613/sq.ft.      1
₹ 24,214/sq.ft.      1
₹ 28,283/sq.ft.      1
₹ 5,698/sq.ft.       1
₹ 8,007/sq.ft.       1
₹ 8,928/sq.ft.       1
₹ 14,286/sq.ft.      1
₹ 8,878/sq.ft.       1
₹ 10,233/sq.ft.      1
₹ 74,074/sq.ft.      1
₹ 13,131/sq.ft.      1
₹ 197,080/sq.ft.     1
₹ 6,172/sq.ft.       1
₹ 99,173/sq.ft.      1
₹ 40,775/sq.ft.      1
₹ 7,778/sq.ft.       1
₹ 4,666/sq.ft.       1
₹ 7,666/sq.ft.       1
₹ 138,888/sq.ft.     1
₹ 7,309/sq.ft.       1
₹ 25,111/sq.ft.      1
₹ 14,729/sq.ft.      1
₹ 4,490/sq.ft.       1
₹ 28,424/sq.ft.      1
₹ 25,960/sq.ft.      1
₹ 23,699/sq.ft.      1
₹ 46,906/sq.ft.      1
₹ 2,778/sq.ft.       1
₹ 10,288/sq.ft.      1
₹ 29,336/sq.ft.      1
₹ 7,843/sq.ft.       1
₹ 15,384/sq.ft.      1
₹ 12,592/sq.ft.      1
₹ 7,589/sq.ft.       1
₹ 11,717/sq.ft.      1
₹ 8,486/sq.ft.       1
₹ 6,250/sq.ft.       1
₹ 9,793/sq.ft.       1
₹ 2,296/sq.ft.       1
₹ 8,701/sq.ft.       1
₹ 7,308/sq.ft.       1
₹ 4,117/sq.ft.       1
₹ 80,357/sq.ft.      1
₹ 9,111/sq.ft.       1
₹ 557/sq.ft.         1
₹ 10,555/sq.ft.      1
₹ 8,518/sq.ft.       1
₹ 10,277/sq.ft.      1
₹ 11,029/sq.ft.      1
₹ 630/sq.ft.         1
₹ 4,074/sq.ft.       1
₹ 9,028/sq.ft.       1
₹ 36,667/sq.ft.      1
₹ 8,916/sq.ft.       1
₹ 26,423/sq.ft.      1
₹ 24,280/sq.ft.      1
₹ 17,650/sq.ft.      1
₹ 25,514/sq.ft.      1
₹ 12,593/sq.ft.      1
₹ 11,284/sq.ft.      1
₹ 5,472/sq.ft.       1
₹ 20,425/sq.ft.      1
₹ 21,667/sq.ft.      1
₹ 9,333/sq.ft.       1
₹ 8,500/sq.ft.       1
₹ 8,697/sq.ft.       1
₹ 10,089/sq.ft.      1
₹ 90,000/sq.ft.      1
₹ 7,280/sq.ft.       1
₹ 41,666/sq.ft.      1
₹ 32,291/sq.ft.      1
₹ 8,411/sq.ft.       1
₹ 230,547/sq.ft.     1
₹ 6,083/sq.ft.       1
₹ 39,265/sq.ft.      1
₹ 8,947/sq.ft.       1
₹ 11,693/sq.ft.      1
₹ 5,833/sq.ft.       1
₹ 20,359/sq.ft.      1
₹ 20,323/sq.ft.      1
₹ 13,888/sq.ft.      1
₹ 6,173/sq.ft.       1
₹ 2/sq.ft.           1
₹ 17,817/sq.ft.      1
₹ 21,519/sq.ft.      1
₹ 17,695/sq.ft.      1
₹ 2,525/sq.ft.       1
₹ 18,667/sq.ft.      1
₹ 8,735/sq.ft.       1
₹ 25,386/sq.ft.      1
₹ 10,482/sq.ft.      1
₹ 57,692/sq.ft.      1
₹ 38,703/sq.ft.      1
₹ 4,808/sq.ft.       1
₹ 9,654/sq.ft.       1
₹ 7,875/sq.ft.       1
₹ 5,888/sq.ft.       1
₹ 13,157/sq.ft.      1
₹ 14,167/sq.ft.      1
₹ 10,804/sq.ft.      1
₹ 14,045/sq.ft.      1
₹ 14,492/sq.ft.      1
₹ 27,155/sq.ft.      1
₹ 40,909/sq.ft.      1
₹ 126,865/sq.ft.     1
₹ 39,886/sq.ft.      1
₹ 17,900/sq.ft.      1
₹ 53,125/sq.ft.      1
₹ 6,567/sq.ft.       1
₹ 5,666/sq.ft.       1
₹ 7,627/sq.ft.       1
₹ 11,273/sq.ft.      1
₹ 8,222/sq.ft.       1
₹ 38,667/sq.ft.      1
₹ 21,250/sq.ft.      1
₹ 13,778/sq.ft.      1
₹ 14,650/sq.ft.      1
₹ 24,069/sq.ft.      1
₹ 42,032/sq.ft.      1
₹ 13,519/sq.ft.      1
₹ 16,428/sq.ft.      1
₹ 8,557/sq.ft.       1
₹ 12,842/sq.ft.      1
₹ 12,828/sq.ft.      1
₹ 19,869/sq.ft.      1
₹ 8,910/sq.ft.       1
₹ 12,162/sq.ft.      1
₹ 10,784/sq.ft.      1
₹ 21,111/sq.ft.      1
₹ 9,725/sq.ft.       1
₹ 28,674/sq.ft.      1
₹ 13,636/sq.ft.      1
₹ 4,400/sq.ft.       1
₹ 9,375/sq.ft.       1
₹ 10,134/sq.ft.      1
₹ 15,097/sq.ft.      1
₹ 12,778/sq.ft.      1
₹ 8,386/sq.ft.       1
₹ 66,666/sq.ft.      1
₹ 22,068/sq.ft.      1
₹ 78,125/sq.ft.      1
₹ 6,111/sq.ft.       1
₹ 5,778/sq.ft.       1
₹ 133,079/sq.ft.     1
₹ 6,410/sq.ft.       1
₹ 26,570/sq.ft.      1
₹ 22,634/sq.ft.      1
₹ 19,286/sq.ft.      1
₹ 24,305/sq.ft.      1
₹ 26,000/sq.ft.      1
₹ 14,072/sq.ft.      1
₹ 7,701/sq.ft.       1
₹ 24,545/sq.ft.      1
₹ 5,658/sq.ft.       1
₹ 7,522/sq.ft.       1
₹ 8,796/sq.ft.       1
₹ 40,135/sq.ft.      1
₹ 23,662/sq.ft.      1
₹ 27,139/sq.ft.      1
₹ 74,000/sq.ft.      1
₹ 3,285/sq.ft.       1
₹ 10,224/sq.ft.      1
₹ 315,789/sq.ft.     1
₹ 6,790/sq.ft.       1
₹ 73,333/sq.ft.      1
₹ 125,000/sq.ft.     1
₹ 22,297/sq.ft.      1
₹ 120,000/sq.ft.     1
₹ 80,000/sq.ft.      1
₹ 211,111/sq.ft.     1
₹ 7,916/sq.ft.       1
₹ 17,955/sq.ft.      1
₹ 25,103/sq.ft.      1
₹ 151/sq.ft.         1
₹ 21,195/sq.ft.      1
₹ 105,263/sq.ft.     1
₹ 23,557/sq.ft.      1
₹ 9,091/sq.ft.       1
₹ 17,574/sq.ft.      1
₹ 41,615/sq.ft.      1
₹ 28,760/sq.ft.      1
₹ 22,006/sq.ft.      1
₹ 27,793/sq.ft.      1
₹ 18,750/sq.ft.      1
₹ 10,463/sq.ft.      1
₹ 10,714/sq.ft.      1
₹ 16,999/sq.ft.      1
₹ 16,244/sq.ft.      1
₹ 12,820/sq.ft.      1
₹ 31,506/sq.ft.      1
₹ 16,389/sq.ft.      1
₹ 32,258/sq.ft.      1
₹ 11,888/sq.ft.      1
₹ 10,378/sq.ft.      1
₹ 11,556/sq.ft.      1
₹ 7,576/sq.ft.       1
₹ 3,874/sq.ft.       1
₹ 11,555/sq.ft.      1
₹ 11,718/sq.ft.      1
₹ 11,464/sq.ft.      1
₹ 35,494/sq.ft.      1
₹ 6,500/sq.ft.       1
₹ 8,784/sq.ft.       1
₹ 14,954/sq.ft.      1
₹ 6,481/sq.ft.       1
₹ 8,642/sq.ft.       1
₹ 10,122/sq.ft.      1
₹ 90,909/sq.ft.      1
₹ 37,313/sq.ft.      1
₹ 6,367/sq.ft.       1
₹ 13,331/sq.ft.      1
₹ 13,623/sq.ft.      1
₹ 35,400/sq.ft.      1
₹ 13,909/sq.ft.      1
₹ 14,245/sq.ft.      1
₹ 54,794/sq.ft.      1
₹ 218,750/sq.ft.     1
₹ 232/sq.ft.         1
₹ 12,400/sq.ft.      1
₹ 229,885/sq.ft.     1
₹ 30,384/sq.ft.      1
₹ 29,311/sq.ft.      1
₹ 13,095/sq.ft.      1
₹ 8,230/sq.ft.       1
₹ 8,730/sq.ft.       1
₹ 11,538/sq.ft.      1
₹ 14,583/sq.ft.      1
₹ 8,125/sq.ft.       1
₹ 10,142/sq.ft.      1
₹ 183,333/sq.ft.     1
₹ 8,012/sq.ft.       1
₹ 7,111/sq.ft.       1
₹ 9,135/sq.ft.       1
₹ 11,904/sq.ft.      1
₹ 245,398/sq.ft.     1
₹ 6,707/sq.ft.       1
₹ 6,648/sq.ft.       1
₹ 12,777/sq.ft.      1
₹ 3,704/sq.ft.       1
₹ 6,667/sq.ft.       1
₹ 2,500/sq.ft.       1
₹ 63,492/sq.ft.      1
₹ 76,000/sq.ft.      1
₹ 19,753/sq.ft.      1
₹ 5,664/sq.ft.       1
₹ 14,720/sq.ft.      1
₹ 4,000/sq.ft.       1
₹ 7,820/sq.ft.       1
₹ 13,499/sq.ft.      1
₹ 98,214/sq.ft.      1
₹ 1,992/sq.ft.       1
₹ 19,818/sq.ft.      1
₹ 3,254/sq.ft.       1
₹ 17,937/sq.ft.      1
₹ 9,500/sq.ft.       1
₹ 26,620/sq.ft.      1
₹ 181,818/sq.ft.     1
₹ 4,222/sq.ft.       1
₹ 14,323/sq.ft.      1
₹ 3,904/sq.ft.       1
₹ 17,500/sq.ft.      1
₹ 16,892/sq.ft.      1
₹ 12,343/sq.ft.      1
₹ 25,543/sq.ft.      1
₹ 11,494/sq.ft.      1
₹ 20,062/sq.ft.      1
₹ 20,233/sq.ft.      1
₹ 11,407/sq.ft.      1
₹ 4,877/sq.ft.       1
₹ 18,333/sq.ft.      1
₹ 6,702/sq.ft.       1
₹ 6,981/sq.ft.       1
₹ 11,194/sq.ft.      1
₹ 3,519/sq.ft.       1
₹ 5,583/sq.ft.       1
₹ 9,074/sq.ft.       1
₹ 5,397/sq.ft.       1
₹ 17,584/sq.ft.      1
₹ 4,251/sq.ft.       1
₹ 8,078/sq.ft.       1
₹ 7,075/sq.ft.       1
₹ 16,667/sq.ft.      1
₹ 21,875/sq.ft.      1
₹ 4,583/sq.ft.       1
₹ 8,101/sq.ft.       1
₹ 7,333/sq.ft.       1
₹ 6,800/sq.ft.       1
₹ 9,210/sq.ft.       1
₹ 14,890/sq.ft.      1
₹ 6,000/sq.ft.       1
₹ 13,750/sq.ft.      1
₹ 26,973/sq.ft.      1
₹ 5,950/sq.ft.       1
₹ 8,702/sq.ft.       1
₹ 45,710/sq.ft.      1
₹ 7,727/sq.ft.       1
₹ 9,103/sq.ft.       1
₹ 16,003/sq.ft.      1
₹ 7,400/sq.ft.       1
₹ 7,479/sq.ft.       1
₹ 7,168/sq.ft.       1
₹ 28,200/sq.ft.      1
₹ 28,898/sq.ft.      1
₹ 1,649/sq.ft.       1
₹ 10,067/sq.ft.      1
₹ 7,539/sq.ft.       1
₹ 6,938/sq.ft.       1
₹ 21,000/sq.ft.      1
₹ 27,971/sq.ft.      1
₹ 12,519/sq.ft.      1
₹ 37,777/sq.ft.      1
₹ 84,000/sq.ft.      1
₹ 9,390/sq.ft.       1
₹ 10,582/sq.ft.      1
₹ 4,260/sq.ft.       1
₹ 14,184/sq.ft.      1
₹ 7,302/sq.ft.       1
₹ 10,610/sq.ft.      1
₹ 308,333/sq.ft.     1
₹ 13,030/sq.ft.      1
₹ 49,500/sq.ft.      1
₹ 7,555/sq.ft.       1
₹ 8,127/sq.ft.       1
₹ 160,000/sq.ft.     1
₹ 10,484/sq.ft.      1
₹ 18,658/sq.ft.      1
₹ 30,968/sq.ft.      1
₹ 14,166/sq.ft.      1
₹ 7,000/sq.ft.       1
₹ 17,857/sq.ft.      1
₹ 6,289/sq.ft.       1
₹ 20,444/sq.ft.      1
₹ 19,737/sq.ft.      1
₹ 17,980/sq.ft.      1
₹ 10,740/sq.ft.      1
₹ 29,629/sq.ft.      1
₹ 40,611/sq.ft.      1
₹ 10,085/sq.ft.      1
₹ 6,034/sq.ft.       1
₹ 11,583/sq.ft.      1
₹ 15,046/sq.ft.      1
₹ 6,813/sq.ft.       1
₹ 9,615/sq.ft.       1
₹ 144,444/sq.ft.     1
₹ 5,160/sq.ft.       1
₹ 24,074/sq.ft.      1
₹ 10,591/sq.ft.      1
₹ 8,155/sq.ft.       1
₹ 38,734/sq.ft.      1
₹ 39,074/sq.ft.      1
₹ 29,444/sq.ft.      1
₹ 44,265/sq.ft.      1
₹ 51,864/sq.ft.      1
₹ 34,307/sq.ft.      1
₹ 14,285/sq.ft.      1
₹ 15,926/sq.ft.      1
₹ 5,777/sq.ft.       1
₹ 5,128/sq.ft.       1
₹ 8,254/sq.ft.       1
₹ 35,294/sq.ft.      1
₹ 8,920/sq.ft.       1
₹ 7,007/sq.ft.       1
₹ 25,463/sq.ft.      1
₹ 5,093/sq.ft.       1
₹ 33,592/sq.ft.      1
₹ 241,666/sq.ft.     1
₹ 27,191/sq.ft.      1
₹ 14,351/sq.ft.      1
₹ 15,437/sq.ft.      1
₹ 11,240/sq.ft.      1
₹ 15,444/sq.ft.      1
₹ 36,911/sq.ft.      1
₹ 8,866/sq.ft.       1
₹ 11,102/sq.ft.      1
₹ 31,915/sq.ft.      1
₹ 10,260/sq.ft.      1
₹ 23,889/sq.ft.      1
₹ 600,000/sq.ft.     1
₹ 41,833/sq.ft.      1
₹ 23,442/sq.ft.      1
₹ 20,988/sq.ft.      1
₹ 13,501/sq.ft.      1
₹ 18,888/sq.ft.      1
₹ 82,540/sq.ft.      1
₹ 26,428/sq.ft.      1
₹ 13,178/sq.ft.      1
₹ 20,741/sq.ft.      1
₹ 1,560/sq.ft.       1
₹ 42,054/sq.ft.      1
₹ 21,495/sq.ft.      1
₹ 11,157/sq.ft.      1
₹ 13,492/sq.ft.      1
₹ 11,600/sq.ft.      1
₹ 18,444/sq.ft.      1
₹ 194,444/sq.ft.     1
₹ 24,455/sq.ft.      1
₹ 23,000/sq.ft.      1
₹ 24,171/sq.ft.      1
₹ 26,298/sq.ft.      1
₹ 24,366/sq.ft.      1
₹ 18,626/sq.ft.      1
₹ 21,296/sq.ft.      1
₹ 16,378/sq.ft.      1
₹ 29,716/sq.ft.      1
₹ 20,690/sq.ft.      1
₹ 45,889/sq.ft.      1
₹ 43,534/sq.ft.      1
₹ 27,741/sq.ft.      1
₹ 7,290/sq.ft.       1
₹ 19,097/sq.ft.      1
₹ 13,542/sq.ft.      1
₹ 400,000/sq.ft.     1
₹ 27,222/sq.ft.      1
₹ 57,206/sq.ft.      1
₹ 38,889/sq.ft.      1
₹ 39,530/sq.ft.      1
₹ 22,429/sq.ft.      1
₹ 32,562/sq.ft.      1
₹ 16,569/sq.ft.      1
₹ 20,068/sq.ft.      1
₹ 17,662/sq.ft.      1
₹ 23,061/sq.ft.      1
₹ 31,686/sq.ft.      1
₹ 178,571/sq.ft.     1
₹ 261,194/sq.ft.     1
₹ 22,812/sq.ft.      1
₹ 6,778/sq.ft.       1
₹ 29,697/sq.ft.      1
₹ 29,293/sq.ft.      1
₹ 235,376/sq.ft.     1
₹ 31,790/sq.ft.      1
₹ 26,111/sq.ft.      1
₹ 40,850/sq.ft.      1
₹ 2,716/sq.ft.       1
₹ 23,437/sq.ft.      1
₹ 19,360/sq.ft.      1
₹ 19,268/sq.ft.      1
₹ 15,989/sq.ft.      1
₹ 23,693/sq.ft.      1
₹ 23,704/sq.ft.      1
₹ 32,253/sq.ft.      1
₹ 20,940/sq.ft.      1
₹ 10,601/sq.ft.      1
₹ 63,554/sq.ft.      1
₹ 27,083/sq.ft.      1
₹ 31,444/sq.ft.      1
₹ 34,846/sq.ft.      1
₹ 40,000/sq.ft.      1
₹ 19,607/sq.ft.      1
₹ 6,849/sq.ft.       1
₹ 8,089/sq.ft.       1
₹ 19,608/sq.ft.      1
₹ 10,926/sq.ft.      1
₹ 17,707/sq.ft.      1
₹ 16,056/sq.ft.      1
₹ 161,849/sq.ft.     1
₹ 30,864/sq.ft.      1
₹ 17,624/sq.ft.      1
₹ 27,333/sq.ft.      1
₹ 16,004/sq.ft.      1
₹ 6,597/sq.ft.       1
₹ 62,222/sq.ft.      1
₹ 26,615/sq.ft.      1
₹ 28,841/sq.ft.      1
₹ 10,035/sq.ft.      1
₹ 23,556/sq.ft.      1
₹ 7,827/sq.ft.       1
₹ 16,666/sq.ft.      1
₹ 35,741/sq.ft.      1
₹ 12,198/sq.ft.      1
₹ 12,837/sq.ft.      1
₹ 29,022/sq.ft.      1
₹ 27,911/sq.ft.      1
₹ 38,611/sq.ft.      1
₹ 31,926/sq.ft.      1
₹ 43,210/sq.ft.      1
₹ 22,075/sq.ft.      1
₹ 16,388/sq.ft.      1
₹ 14,222/sq.ft.      1
₹ 16,990/sq.ft.      1
₹ 25,309/sq.ft.      1
₹ 38,022/sq.ft.      1
₹ 17,692/sq.ft.      1
₹ 35,109/sq.ft.      1
₹ 27,871/sq.ft.      1
₹ 36,883/sq.ft.      1
₹ 19,645/sq.ft.      1
₹ 1,087/sq.ft.       1
₹ 19,820/sq.ft.      1
₹ 15,111/sq.ft.      1
₹ 28,233/sq.ft.      1
₹ 7,870/sq.ft.       1
₹ 16,577/sq.ft.      1
₹ 21,825/sq.ft.      1
₹ 7,756/sq.ft.       1
₹ 25,556/sq.ft.      1
₹ 21,097/sq.ft.      1
₹ 34,568/sq.ft.      1
₹ 20,769/sq.ft.      1
₹ 13,513/sq.ft.      1
₹ 28,549/sq.ft.      1
₹ 28,858/sq.ft.      1
₹ 10,123/sq.ft.      1
₹ 34,037/sq.ft.      1
₹ 20,197/sq.ft.      1
₹ 7,937/sq.ft.       1
₹ 47,167/sq.ft.      1
₹ 11,666/sq.ft.      1
₹ 38,986/sq.ft.      1
₹ 55,556/sq.ft.      1
₹ 16,066/sq.ft.      1
₹ 18,605/sq.ft.      1
₹ 7,582/sq.ft.       1
₹ 8,137/sq.ft.       1
₹ 29,638/sq.ft.      1
₹ 7,172/sq.ft.       1
₹ 7,750/sq.ft.       1
₹ 17,014/sq.ft.      1
₹ 18,620/sq.ft.      1
₹ 17,213/sq.ft.      1
₹ 31,111/sq.ft.      1
₹ 37,778/sq.ft.      1
₹ 29,074/sq.ft.      1
₹ 17,706/sq.ft.      1
₹ 19,231/sq.ft.      1
₹ 41,818/sq.ft.      1
₹ 20,299/sq.ft.      1
₹ 21,367/sq.ft.      1
₹ 173,992/sq.ft.     1
₹ 20,599/sq.ft.      1
₹ 19,293/sq.ft.      1
₹ 12,285/sq.ft.      1
₹ 18,008/sq.ft.      1
₹ 283,333/sq.ft.     1
₹ 31,666/sq.ft.      1
₹ 20,370/sq.ft.      1
₹ 30,247/sq.ft.      1
₹ 22,184/sq.ft.      1
₹ 11,428/sq.ft.      1
₹ 24,510/sq.ft.      1
₹ 27,160/sq.ft.      1
₹ 21,251/sq.ft.      1
₹ 15,432/sq.ft.      1
₹ 21,786/sq.ft.      1
₹ 234,375/sq.ft.     1
₹ 23,504/sq.ft.      1
₹ 9,349/sq.ft.       1
₹ 3,786/sq.ft.       1
₹ 41,315/sq.ft.      1
₹ 30,728/sq.ft.      1
₹ 27,390/sq.ft.      1
₹ 18,250/sq.ft.      1
₹ 16,319/sq.ft.      1
₹ 14,787/sq.ft.      1
₹ 14,667/sq.ft.      1
₹ 6,875/sq.ft.       1
₹ 28,787/sq.ft.      1
₹ 20,026/sq.ft.      1
₹ 23,870/sq.ft.      1
₹ 21,219/sq.ft.      1
₹ 16,600/sq.ft.      1
₹ 18,088/sq.ft.      1
₹ 20,317/sq.ft.      1
₹ 22,331/sq.ft.      1
₹ 12,393/sq.ft.      1
₹ 290,948/sq.ft.     1
₹ 29,333/sq.ft.      1
₹ 40,741/sq.ft.      1
₹ 22,855/sq.ft.      1
₹ 27,132/sq.ft.      1
₹ 22,046/sq.ft.      1
₹ 35,530/sq.ft.      1
₹ 34,351/sq.ft.      1
₹ 51,440/sq.ft.      1
₹ 16,071/sq.ft.      1
₹ 23,240/sq.ft.      1
₹ 33,404/sq.ft.      1
₹ 32,870/sq.ft.      1
₹ 24,005/sq.ft.      1
₹ 24,573/sq.ft.      1
₹ 14,914/sq.ft.      1
₹ 33,200/sq.ft.      1
₹ 34,083/sq.ft.      1
₹ 10,077/sq.ft.      1
₹ 20,115/sq.ft.      1
₹ 18,808/sq.ft.      1
₹ 26,502/sq.ft.      1
₹ 266,666/sq.ft.     1
₹ 24,390/sq.ft.      1
₹ 17,820/sq.ft.      1
₹ 12,037/sq.ft.      1
₹ 19,847/sq.ft.      1
₹ 38,251/sq.ft.      1
₹ 43,066/sq.ft.      1
₹ 12,938/sq.ft.      1
₹ 15,451/sq.ft.      1
₹ 41,762/sq.ft.      1
₹ 29,861/sq.ft.      1
₹ 24,202/sq.ft.      1
₹ 20,349/sq.ft.      1
₹ 20,566/sq.ft.      1
₹ 33,665/sq.ft.      1
₹ 6,230/sq.ft.       1
₹ 47,803/sq.ft.      1
Name: count, dtype: int64

In [29]:
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 22,222/sq.ft.     14
₹ 11,111/sq.ft.     12
₹ 33,333/sq.ft.     11
₹ 10,000/sq.ft.     10
₹ 37,037/sq.ft.      7
₹ 13,333/sq.ft.      7
₹ 30,556/sq.ft.      6
₹ 31,481/sq.ft.      6
₹ 26,235/sq.ft.      6
₹ 26,667/sq.ft.      6
₹ 8,000/sq.ft.       6
₹ 11,100/sq.ft.      5
₹ 5,000/sq.ft.       5
₹ 23,148/sq.ft.      5
₹ 8,889/sq.ft.       5
₹ 32,407/sq.ft.      5
₹ 23,333/sq.ft.      5
₹ 9,444/sq.ft.       5
₹ 9,722/sq.ft.       4
₹ 21,605/sq.ft.      4
₹ 34,722/sq.ft.      4
₹ 27,778/sq.ft.      4
₹ 15,625/sq.ft.      4
₹ 18,889/sq.ft.      4
₹ 35,000/sq.ft.      4
₹ 24,691/sq.ft.      4
₹ 25,000/sq.ft.      4
₹ 6,944/sq.ft.       4
₹ 32,222/sq.ft.      3
₹ 33,951/sq.ft.      3
₹ 36,111/sq.ft.      3
₹ 29,880/sq.ft.      3
₹ 100,000/sq.ft.     3
₹ 25,926/sq.ft.      3
₹ 5,555/sq.ft.       3
₹ 7,500/sq.ft.       3
₹ 10,556/sq.ft.      3
₹ 8,235/sq.ft.       3
₹ 13,889/sq.ft.      3
₹ 8,333/sq.ft.       3
₹ 12,222/sq.ft.      3
₹ 60,000/sq.ft.      3
₹ 6,666/sq.ft.       3
₹ 50,000/sq.ft.      3
₹ 14,815/sq.ft.      3
₹ 17,037/sq.ft.      3
₹ 15,555/sq.ft.      3
₹ 23,457/sq.ft.      3
₹ 8,444/sq.ft.       3
₹ 16,058/sq.ft.      3
₹ 11,250/sq.ft.      3
₹ 20,000/sq.ft.      3
₹ 44,444/sq.ft.      3
₹ 9,259/sq.ft.       3
₹ 12,000/sq.ft.      3
₹ 9,634/sq.ft.       2
₹ 45,833/sq.ft.      2
₹ 12,342/sq.ft.      2
₹ 38,580/sq.ft.      2
₹ 35,556/sq.ft.      2
₹ 24,155/sq.ft.      2
₹ 38,760/sq.ft.      2
₹ 38,194/sq.ft.      2
₹ 42,222/sq.ft.      2
₹ 59,259/sq.ft.      2
₹ 20,635/sq.ft.      2
₹ 17,187/sq.ft.      2
₹ 18,928/sq.ft.      2
₹ 13,622/sq.ft.      2
₹ 15,700/sq.ft.      2
₹ 12,027/sq.ft.      2
₹ 13,910/sq.ft.      2
₹ 12,500/sq.ft.      2
₹ 16,039/sq.ft.      2
₹ 19,708/sq.ft.      2
₹ 24,500/sq.ft.      2
₹ 25,562/sq.ft.      2
₹ 17,778/sq.ft.      2
₹ 4,444/sq.ft.       2
₹ 11,574/sq.ft.      2
₹ 1,859/sq.ft.       2
₹ 10,579/sq.ft.      2
₹ 42,194/sq.ft.      2
₹ 15,278/sq.ft.      2
₹ 201,388/sq.ft.     2
₹ 7,058/sq.ft.       2
₹ 7,718/sq.ft.       2
₹ 25,535/sq.ft.      2
₹ 21,124/sq.ft.      2
₹ 39,841/sq.ft.      2
₹ 17,284/sq.ft.      2
₹ 37,627/sq.ft.      2
₹ 48,148/sq.ft.      2
₹ 29,630/sq.ft.      2
₹ 35,185/sq.ft.      2
₹ 13,000/sq.ft.      2
₹ 32,328/sq.ft.      2
₹ 32,963/sq.ft.      2
₹ 3,857/sq.ft.       2
₹ 21,759/sq.ft.      2
₹ 24,306/sq.ft.      2
₹ 7,619/sq.ft.       2
₹ 10,101/sq.ft.      2
₹ 10,783/sq.ft.      2
₹ 19,000/sq.ft.      2
₹ 10,753/sq.ft.      2
₹ 20,833/sq.ft.      2
₹ 3,500/sq.ft.       2
₹ 15,257/sq.ft.      2
₹ 10,518/sq.ft.      2
₹ 27,461/sq.ft.      2
₹ 5,333/sq.ft.       2
₹ 14,444/sq.ft.      2
₹ 16,975/sq.ft.      2
₹ 75,000/sq.ft.      2
₹ 55,000/sq.ft.      2
₹ 9,000/sq.ft.       2
₹ 24,845/sq.ft.      2
₹ 12,963/sq.ft.      2
₹ 26,389/sq.ft.      2
₹ 7,407/sq.ft.       2
₹ 8,888/sq.ft.       2
₹ 12,444/sq.ft.      2
₹ 11,852/sq.ft.      2
₹ 21,242/sq.ft.      2
₹ 26,852/sq.ft.      2
₹ 7,777/sq.ft.       2
₹ 38,095/sq.ft.      2
₹ 39,062/sq.ft.      1
₹ 48,889/sq.ft.      1
₹ 10,838/sq.ft.      1
₹ 34,491/sq.ft.      1
₹ 28,782/sq.ft.      1
₹ 38,150/sq.ft.      1
₹ 13,034/sq.ft.      1
₹ 53,763/sq.ft.      1
₹ 14,000/sq.ft.      1
₹ 18,814/sq.ft.      1
₹ 15,000/sq.ft.      1
₹ 18,885/sq.ft.      1
₹ 19,125/sq.ft.      1
₹ 122,222/sq.ft.     1
₹ 28,490/sq.ft.      1
₹ 24,170/sq.ft.      1
₹ 32,593/sq.ft.      1
₹ 13,410/sq.ft.      1
₹ 9,374/sq.ft.       1
₹ 105,751/sq.ft.     1
₹ 31,008/sq.ft.      1
₹ 13,992/sq.ft.      1
₹ 33,129/sq.ft.      1
₹ 12,551/sq.ft.      1
₹ 13,359/sq.ft.      1
₹ 11,784/sq.ft.      1
₹ 4,333/sq.ft.       1
₹ 255,555/sq.ft.     1
₹ 24,912/sq.ft.      1
₹ 29,321/sq.ft.      1
₹ 102,941/sq.ft.     1
₹ 13,071/sq.ft.      1
₹ 24,444/sq.ft.      1
₹ 3,452/sq.ft.       1
₹ 481/sq.ft.         1
₹ 43,333/sq.ft.      1
₹ 8,181/sq.ft.       1
₹ 23,932/sq.ft.      1
₹ 79,365/sq.ft.      1
₹ 26,063/sq.ft.      1
₹ 29,974/sq.ft.      1
₹ 88,157/sq.ft.      1
₹ 92,857/sq.ft.      1
₹ 86,567/sq.ft.      1
₹ 26,613/sq.ft.      1
₹ 24,214/sq.ft.      1
₹ 28,283/sq.ft.      1
₹ 5,698/sq.ft.       1
₹ 8,007/sq.ft.       1
₹ 8,928/sq.ft.       1
₹ 14,286/sq.ft.      1
₹ 8,878/sq.ft.       1
₹ 10,233/sq.ft.      1
₹ 74,074/sq.ft.      1
₹ 13,131/sq.ft.      1
₹ 197,080/sq.ft.     1
₹ 6,172/sq.ft.       1
₹ 99,173/sq.ft.      1
₹ 40,775/sq.ft.      1
₹ 7,778/sq.ft.       1
₹ 4,666/sq.ft.       1
₹ 7,666/sq.ft.       1
₹ 138,888/sq.ft.     1
₹ 7,309/sq.ft.       1
₹ 25,111/sq.ft.      1
₹ 14,729/sq.ft.      1
₹ 4,490/sq.ft.       1
₹ 28,424/sq.ft.      1
₹ 25,960/sq.ft.      1
₹ 23,699/sq.ft.      1
₹ 46,906/sq.ft.      1
₹ 2,778/sq.ft.       1
₹ 10,288/sq.ft.      1
₹ 29,336/sq.ft.      1
₹ 7,843/sq.ft.       1
₹ 15,384/sq.ft.      1
₹ 12,592/sq.ft.      1
₹ 7,589/sq.ft.       1
₹ 11,717/sq.ft.      1
₹ 8,486/sq.ft.       1
₹ 6,250/sq.ft.       1
₹ 9,793/sq.ft.       1
₹ 2,296/sq.ft.       1
₹ 8,701/sq.ft.       1
₹ 7,308/sq.ft.       1
₹ 4,117/sq.ft.       1
₹ 80,357/sq.ft.      1
₹ 9,111/sq.ft.       1
₹ 557/sq.ft.         1
₹ 10,555/sq.ft.      1
₹ 8,518/sq.ft.       1
₹ 10,277/sq.ft.      1
₹ 11,029/sq.ft.      1
₹ 630/sq.ft.         1
₹ 4,074/sq.ft.       1
₹ 9,028/sq.ft.       1
₹ 36,667/sq.ft.      1
₹ 8,916/sq.ft.       1
₹ 26,423/sq.ft.      1
₹ 24,280/sq.ft.      1
₹ 17,650/sq.ft.      1
₹ 25,514/sq.ft.      1
₹ 12,593/sq.ft.      1
₹ 11,284/sq.ft.      1
₹ 5,472/sq.ft.       1
₹ 20,425/sq.ft.      1
₹ 21,667/sq.ft.      1
₹ 9,333/sq.ft.       1
₹ 8,500/sq.ft.       1
₹ 8,697/sq.ft.       1
₹ 10,089/sq.ft.      1
₹ 90,000/sq.ft.      1
₹ 7,280/sq.ft.       1
₹ 41,666/sq.ft.      1
₹ 32,291/sq.ft.      1
₹ 8,411/sq.ft.       1
₹ 230,547/sq.ft.     1
₹ 6,083/sq.ft.       1
₹ 39,265/sq.ft.      1
₹ 8,947/sq.ft.       1
₹ 11,693/sq.ft.      1
₹ 5,833/sq.ft.       1
₹ 20,359/sq.ft.      1
₹ 20,323/sq.ft.      1
₹ 13,888/sq.ft.      1
₹ 6,173/sq.ft.       1
₹ 2/sq.ft.           1
₹ 17,817/sq.ft.      1
₹ 21,519/sq.ft.      1
₹ 17,695/sq.ft.      1
₹ 2,525/sq.ft.       1
₹ 18,667/sq.ft.      1
₹ 8,735/sq.ft.       1
₹ 25,386/sq.ft.      1
₹ 10,482/sq.ft.      1
₹ 57,692/sq.ft.      1
₹ 38,703/sq.ft.      1
₹ 4,808/sq.ft.       1
₹ 9,654/sq.ft.       1
₹ 7,875/sq.ft.       1
₹ 5,888/sq.ft.       1
₹ 13,157/sq.ft.      1
₹ 14,167/sq.ft.      1
₹ 10,804/sq.ft.      1
₹ 14,045/sq.ft.      1
₹ 14,492/sq.ft.      1
₹ 27,155/sq.ft.      1
₹ 40,909/sq.ft.      1
₹ 126,865/sq.ft.     1
₹ 39,886/sq.ft.      1
₹ 17,900/sq.ft.      1
₹ 53,125/sq.ft.      1
₹ 6,567/sq.ft.       1
₹ 5,666/sq.ft.       1
₹ 7,627/sq.ft.       1
₹ 11,273/sq.ft.      1
₹ 8,222/sq.ft.       1
₹ 38,667/sq.ft.      1
₹ 21,250/sq.ft.      1
₹ 13,778/sq.ft.      1
₹ 14,650/sq.ft.      1
₹ 24,069/sq.ft.      1
₹ 42,032/sq.ft.      1
₹ 13,519/sq.ft.      1
₹ 16,428/sq.ft.      1
₹ 8,557/sq.ft.       1
₹ 12,842/sq.ft.      1
₹ 12,828/sq.ft.      1
₹ 19,869/sq.ft.      1
₹ 8,910/sq.ft.       1
₹ 12,162/sq.ft.      1
₹ 10,784/sq.ft.      1
₹ 21,111/sq.ft.      1
₹ 9,725/sq.ft.       1
₹ 28,674/sq.ft.      1
₹ 13,636/sq.ft.      1
₹ 4,400/sq.ft.       1
₹ 9,375/sq.ft.       1
₹ 10,134/sq.ft.      1
₹ 15,097/sq.ft.      1
₹ 12,778/sq.ft.      1
₹ 8,386/sq.ft.       1
₹ 66,666/sq.ft.      1
₹ 22,068/sq.ft.      1
₹ 78,125/sq.ft.      1
₹ 6,111/sq.ft.       1
₹ 5,778/sq.ft.       1
₹ 133,079/sq.ft.     1
₹ 6,410/sq.ft.       1
₹ 26,570/sq.ft.      1
₹ 22,634/sq.ft.      1
₹ 19,286/sq.ft.      1
₹ 24,305/sq.ft.      1
₹ 26,000/sq.ft.      1
₹ 14,072/sq.ft.      1
₹ 7,701/sq.ft.       1
₹ 24,545/sq.ft.      1
₹ 5,658/sq.ft.       1
₹ 7,522/sq.ft.       1
₹ 8,796/sq.ft.       1
₹ 40,135/sq.ft.      1
₹ 23,662/sq.ft.      1
₹ 27,139/sq.ft.      1
₹ 74,000/sq.ft.      1
₹ 3,285/sq.ft.       1
₹ 10,224/sq.ft.      1
₹ 315,789/sq.ft.     1
₹ 6,790/sq.ft.       1
₹ 73,333/sq.ft.      1
₹ 125,000/sq.ft.     1
₹ 22,297/sq.ft.      1
₹ 120,000/sq.ft.     1
₹ 80,000/sq.ft.      1
₹ 211,111/sq.ft.     1
₹ 7,916/sq.ft.       1
₹ 17,955/sq.ft.      1
₹ 25,103/sq.ft.      1
₹ 151/sq.ft.         1
₹ 21,195/sq.ft.      1
₹ 105,263/sq.ft.     1
₹ 23,557/sq.ft.      1
₹ 9,091/sq.ft.       1
₹ 17,574/sq.ft.      1
₹ 41,615/sq.ft.      1
₹ 28,760/sq.ft.      1
₹ 22,006/sq.ft.      1
₹ 27,793/sq.ft.      1
₹ 18,750/sq.ft.      1
₹ 10,463/sq.ft.      1
₹ 10,714/sq.ft.      1
₹ 16,999/sq.ft.      1
₹ 16,244/sq.ft.      1
₹ 12,820/sq.ft.      1
₹ 31,506/sq.ft.      1
₹ 16,389/sq.ft.      1
₹ 32,258/sq.ft.      1
₹ 11,888/sq.ft.      1
₹ 10,378/sq.ft.      1
₹ 11,556/sq.ft.      1
₹ 7,576/sq.ft.       1
₹ 3,874/sq.ft.       1
₹ 11,555/sq.ft.      1
₹ 11,718/sq.ft.      1
₹ 11,464/sq.ft.      1
₹ 35,494/sq.ft.      1
₹ 6,500/sq.ft.       1
₹ 8,784/sq.ft.       1
₹ 14,954/sq.ft.      1
₹ 6,481/sq.ft.       1
₹ 8,642/sq.ft.       1
₹ 10,122/sq.ft.      1
₹ 90,909/sq.ft.      1
₹ 37,313/sq.ft.      1
₹ 6,367/sq.ft.       1
₹ 13,331/sq.ft.      1
₹ 13,623/sq.ft.      1
₹ 35,400/sq.ft.      1
₹ 13,909/sq.ft.      1
₹ 14,245/sq.ft.      1
₹ 54,794/sq.ft.      1
₹ 218,750/sq.ft.     1
₹ 232/sq.ft.         1
₹ 12,400/sq.ft.      1
₹ 229,885/sq.ft.     1
₹ 30,384/sq.ft.      1
₹ 29,311/sq.ft.      1
₹ 13,095/sq.ft.      1
₹ 8,230/sq.ft.       1
₹ 8,730/sq.ft.       1
₹ 11,538/sq.ft.      1
₹ 14,583/sq.ft.      1
₹ 8,125/sq.ft.       1
₹ 10,142/sq.ft.      1
₹ 183,333/sq.ft.     1
₹ 8,012/sq.ft.       1
₹ 7,111/sq.ft.       1
₹ 9,135/sq.ft.       1
₹ 11,904/sq.ft.      1
₹ 245,398/sq.ft.     1
₹ 6,707/sq.ft.       1
₹ 6,648/sq.ft.       1
₹ 12,777/sq.ft.      1
₹ 3,704/sq.ft.       1
₹ 6,667/sq.ft.       1
₹ 2,500/sq.ft.       1
₹ 63,492/sq.ft.      1
₹ 76,000/sq.ft.      1
₹ 19,753/sq.ft.      1
₹ 5,664/sq.ft.       1
₹ 14,720/sq.ft.      1
₹ 4,000/sq.ft.       1
₹ 7,820/sq.ft.       1
₹ 13,499/sq.ft.      1
₹ 98,214/sq.ft.      1
₹ 1,992/sq.ft.       1
₹ 19,818/sq.ft.      1
₹ 3,254/sq.ft.       1
₹ 17,937/sq.ft.      1
₹ 9,500/sq.ft.       1
₹ 26,620/sq.ft.      1
₹ 181,818/sq.ft.     1
₹ 4,222/sq.ft.       1
₹ 14,323/sq.ft.      1
₹ 3,904/sq.ft.       1
₹ 17,500/sq.ft.      1
₹ 16,892/sq.ft.      1
₹ 12,343/sq.ft.      1
₹ 25,543/sq.ft.      1
₹ 11,494/sq.ft.      1
₹ 20,062/sq.ft.      1
₹ 20,233/sq.ft.      1
₹ 11,407/sq.ft.      1
₹ 4,877/sq.ft.       1
₹ 18,333/sq.ft.      1
₹ 6,702/sq.ft.       1
₹ 6,981/sq.ft.       1
₹ 11,194/sq.ft.      1
₹ 3,519/sq.ft.       1
₹ 5,583/sq.ft.       1
₹ 9,074/sq.ft.       1
₹ 5,397/sq.ft.       1
₹ 17,584/sq.ft.      1
₹ 4,251/sq.ft.       1
₹ 8,078/sq.ft.       1
₹ 7,075/sq.ft.       1
₹ 16,667/sq.ft.      1
₹ 21,875/sq.ft.      1
₹ 4,583/sq.ft.       1
₹ 8,101/sq.ft.       1
₹ 7,333/sq.ft.       1
₹ 6,800/sq.ft.       1
₹ 9,210/sq.ft.       1
₹ 14,890/sq.ft.      1
₹ 6,000/sq.ft.       1
₹ 13,750/sq.ft.      1
₹ 26,973/sq.ft.      1
₹ 5,950/sq.ft.       1
₹ 8,702/sq.ft.       1
₹ 45,710/sq.ft.      1
₹ 7,727/sq.ft.       1
₹ 9,103/sq.ft.       1
₹ 16,003/sq.ft.      1
₹ 7,400/sq.ft.       1
₹ 7,479/sq.ft.       1
₹ 7,168/sq.ft.       1
₹ 28,200/sq.ft.      1
₹ 28,898/sq.ft.      1
₹ 1,649/sq.ft.       1
₹ 10,067/sq.ft.      1
₹ 7,539/sq.ft.       1
₹ 6,938/sq.ft.       1
₹ 21,000/sq.ft.      1
₹ 27,971/sq.ft.      1
₹ 12,519/sq.ft.      1
₹ 37,777/sq.ft.      1
₹ 84,000/sq.ft.      1
₹ 9,390/sq.ft.       1
₹ 10,582/sq.ft.      1
₹ 4,260/sq.ft.       1
₹ 14,184/sq.ft.      1
₹ 7,302/sq.ft.       1
₹ 10,610/sq.ft.      1
₹ 308,333/sq.ft.     1
₹ 13,030/sq.ft.      1
₹ 49,500/sq.ft.      1
₹ 7,555/sq.ft.       1
₹ 8,127/sq.ft.       1
₹ 160,000/sq.ft.     1
₹ 10,484/sq.ft.      1
₹ 18,658/sq.ft.      1
₹ 30,968/sq.ft.      1
₹ 14,166/sq.ft.      1
₹ 7,000/sq.ft.       1
₹ 17,857/sq.ft.      1
₹ 6,289/sq.ft.       1
₹ 20,444/sq.ft.      1
₹ 19,737/sq.ft.      1
₹ 17,980/sq.ft.      1
₹ 10,740/sq.ft.      1
₹ 29,629/sq.ft.      1
₹ 40,611/sq.ft.      1
₹ 10,085/sq.ft.      1
₹ 6,034/sq.ft.       1
₹ 11,583/sq.ft.      1
₹ 15,046/sq.ft.      1
₹ 6,813/sq.ft.       1
₹ 9,615/sq.ft.       1
₹ 144,444/sq.ft.     1
₹ 5,160/sq.ft.       1
₹ 24,074/sq.ft.      1
₹ 10,591/sq.ft.      1
₹ 8,155/sq.ft.       1
₹ 38,734/sq.ft.      1
₹ 39,074/sq.ft.      1
₹ 29,444/sq.ft.      1
₹ 44,265/sq.ft.      1
₹ 51,864/sq.ft.      1
₹ 34,307/sq.ft.      1
₹ 14,285/sq.ft.      1
₹ 15,926/sq.ft.      1
₹ 5,777/sq.ft.       1
₹ 5,128/sq.ft.       1
₹ 8,254/sq.ft.       1
₹ 35,294/sq.ft.      1
₹ 8,920/sq.ft.       1
₹ 7,007/sq.ft.       1
₹ 25,463/sq.ft.      1
₹ 5,093/sq.ft.       1
₹ 33,592/sq.ft.      1
₹ 241,666/sq.ft.     1
₹ 27,191/sq.ft.      1
₹ 14,351/sq.ft.      1
₹ 15,437/sq.ft.      1
₹ 11,240/sq.ft.      1
₹ 15,444/sq.ft.      1
₹ 36,911/sq.ft.      1
₹ 8,866/sq.ft.       1
₹ 11,102/sq.ft.      1
₹ 31,915/sq.ft.      1
₹ 10,260/sq.ft.      1
₹ 23,889/sq.ft.      1
₹ 600,000/sq.ft.     1
₹ 41,833/sq.ft.      1
₹ 23,442/sq.ft.      1
₹ 20,988/sq.ft.      1
₹ 13,501/sq.ft.      1
₹ 18,888/sq.ft.      1
₹ 82,540/sq.ft.      1
₹ 26,428/sq.ft.      1
₹ 13,178/sq.ft.      1
₹ 20,741/sq.ft.      1
₹ 1,560/sq.ft.       1
₹ 42,054/sq.ft.      1
₹ 21,495/sq.ft.      1
₹ 11,157/sq.ft.      1
₹ 13,492/sq.ft.      1
₹ 11,600/sq.ft.      1
₹ 18,444/sq.ft.      1
₹ 194,444/sq.ft.     1
₹ 24,455/sq.ft.      1
₹ 23,000/sq.ft.      1
₹ 24,171/sq.ft.      1
₹ 26,298/sq.ft.      1
₹ 24,366/sq.ft.      1
₹ 18,626/sq.ft.      1
₹ 21,296/sq.ft.      1
₹ 16,378/sq.ft.      1
₹ 29,716/sq.ft.      1
₹ 20,690/sq.ft.      1
₹ 45,889/sq.ft.      1
₹ 43,534/sq.ft.      1
₹ 27,741/sq.ft.      1
₹ 7,290/sq.ft.       1
₹ 19,097/sq.ft.      1
₹ 13,542/sq.ft.      1
₹ 400,000/sq.ft.     1
₹ 27,222/sq.ft.      1
₹ 57,206/sq.ft.      1
₹ 38,889/sq.ft.      1
₹ 39,530/sq.ft.      1
₹ 22,429/sq.ft.      1
₹ 32,562/sq.ft.      1
₹ 16,569/sq.ft.      1
₹ 20,068/sq.ft.      1
₹ 17,662/sq.ft.      1
₹ 23,061/sq.ft.      1
₹ 31,686/sq.ft.      1
₹ 178,571/sq.ft.     1
₹ 261,194/sq.ft.     1
₹ 22,812/sq.ft.      1
₹ 6,778/sq.ft.       1
₹ 29,697/sq.ft.      1
₹ 29,293/sq.ft.      1
₹ 235,376/sq.ft.     1
₹ 31,790/sq.ft.      1
₹ 26,111/sq.ft.      1
₹ 40,850/sq.ft.      1
₹ 2,716/sq.ft.       1
₹ 23,437/sq.ft.      1
₹ 19,360/sq.ft.      1
₹ 19,268/sq.ft.      1
₹ 15,989/sq.ft.      1
₹ 23,693/sq.ft.      1
₹ 23,704/sq.ft.      1
₹ 32,253/sq.ft.      1
₹ 20,940/sq.ft.      1
₹ 10,601/sq.ft.      1
₹ 63,554/sq.ft.      1
₹ 27,083/sq.ft.      1
₹ 31,444/sq.ft.      1
₹ 34,846/sq.ft.      1
₹ 40,000/sq.ft.      1
₹ 19,607/sq.ft.      1
₹ 6,849/sq.ft.       1
₹ 8,089/sq.ft.       1
₹ 19,608/sq.ft.      1
₹ 10,926/sq.ft.      1
₹ 17,707/sq.ft.      1
₹ 16,056/sq.ft.      1
₹ 161,849/sq.ft.     1
₹ 30,864/sq.ft.      1
₹ 17,624/sq.ft.      1
₹ 27,333/sq.ft.      1
₹ 16,004/sq.ft.      1
₹ 6,597/sq.ft.       1
₹ 62,222/sq.ft.      1
₹ 26,615/sq.ft.      1
₹ 28,841/sq.ft.      1
₹ 10,035/sq.ft.      1
₹ 23,556/sq.ft.      1
₹ 7,827/sq.ft.       1
₹ 16,666/sq.ft.      1
₹ 35,741/sq.ft.      1
₹ 12,198/sq.ft.      1
₹ 12,837/sq.ft.      1
₹ 29,022/sq.ft.      1
₹ 27,911/sq.ft.      1
₹ 38,611/sq.ft.      1
₹ 31,926/sq.ft.      1
₹ 43,210/sq.ft.      1
₹ 22,075/sq.ft.      1
₹ 16,388/sq.ft.      1
₹ 14,222/sq.ft.      1
₹ 16,990/sq.ft.      1
₹ 25,309/sq.ft.      1
₹ 38,022/sq.ft.      1
₹ 17,692/sq.ft.      1
₹ 35,109/sq.ft.      1
₹ 27,871/sq.ft.      1
₹ 36,883/sq.ft.      1
₹ 19,645/sq.ft.      1
₹ 1,087/sq.ft.       1
₹ 19,820/sq.ft.      1
₹ 15,111/sq.ft.      1
₹ 28,233/sq.ft.      1
₹ 7,870/sq.ft.       1
₹ 16,577/sq.ft.      1
₹ 21,825/sq.ft.      1
₹ 7,756/sq.ft.       1
₹ 25,556/sq.ft.      1
₹ 21,097/sq.ft.      1
₹ 34,568/sq.ft.      1
₹ 20,769/sq.ft.      1
₹ 13,513/sq.ft.      1
₹ 28,549/sq.ft.      1
₹ 28,858/sq.ft.      1
₹ 10,123/sq.ft.      1
₹ 34,037/sq.ft.      1
₹ 20,197/sq.ft.      1
₹ 7,937/sq.ft.       1
₹ 47,167/sq.ft.      1
₹ 11,666/sq.ft.      1
₹ 38,986/sq.ft.      1
₹ 55,556/sq.ft.      1
₹ 16,066/sq.ft.      1
₹ 18,605/sq.ft.      1
₹ 7,582/sq.ft.       1
₹ 8,137/sq.ft.       1
₹ 29,638/sq.ft.      1
₹ 7,172/sq.ft.       1
₹ 7,750/sq.ft.       1
₹ 17,014/sq.ft.      1
₹ 18,620/sq.ft.      1
₹ 17,213/sq.ft.      1
₹ 31,111/sq.ft.      1
₹ 37,778/sq.ft.      1
₹ 29,074/sq.ft.      1
₹ 17,706/sq.ft.      1
₹ 19,231/sq.ft.      1
₹ 41,818/sq.ft.      1
₹ 20,299/sq.ft.      1
₹ 21,367/sq.ft.      1
₹ 173,992/sq.ft.     1
₹ 20,599/sq.ft.      1
₹ 19,293/sq.ft.      1
₹ 12,285/sq.ft.      1
₹ 18,008/sq.ft.      1
₹ 283,333/sq.ft.     1
₹ 31,666/sq.ft.      1
₹ 20,370/sq.ft.      1
₹ 30,247/sq.ft.      1
₹ 22,184/sq.ft.      1
₹ 11,428/sq.ft.      1
₹ 24,510/sq.ft.      1
₹ 27,160/sq.ft.      1
₹ 21,251/sq.ft.      1
₹ 15,432/sq.ft.      1
₹ 21,786/sq.ft.      1
₹ 234,375/sq.ft.     1
₹ 23,504/sq.ft.      1
₹ 9,349/sq.ft.       1
₹ 3,786/sq.ft.       1
₹ 41,315/sq.ft.      1
₹ 30,728/sq.ft.      1
₹ 27,390/sq.ft.      1
₹ 18,250/sq.ft.      1
₹ 16,319/sq.ft.      1
₹ 14,787/sq.ft.      1
₹ 14,667/sq.ft.      1
₹ 6,875/sq.ft.       1
₹ 28,787/sq.ft.      1
₹ 20,026/sq.ft.      1
₹ 23,870/sq.ft.      1
₹ 21,219/sq.ft.      1
₹ 16,600/sq.ft.      1
₹ 18,088/sq.ft.      1
₹ 20,317/sq.ft.      1
₹ 22,331/sq.ft.      1
₹ 12,393/sq.ft.      1
₹ 290,948/sq.ft.     1
₹ 29,333/sq.ft.      1
₹ 40,741/sq.ft.      1
₹ 22,855/sq.ft.      1
₹ 27,132/sq.ft.      1
₹ 22,046/sq.ft.      1
₹ 35,530/sq.ft.      1
₹ 34,351/sq.ft.      1
₹ 51,440/sq.ft.      1
₹ 16,071/sq.ft.      1
₹ 23,240/sq.ft.      1
₹ 33,404/sq.ft.      1
₹ 32,870/sq.ft.      1
₹ 24,005/sq.ft.      1
₹ 24,573/sq.ft.      1
₹ 14,914/sq.ft.      1
₹ 33,200/sq.ft.      1
₹ 34,083/sq.ft.      1
₹ 10,077/sq.ft.      1
₹ 20,115/sq.ft.      1
₹ 18,808/sq.ft.      1
₹ 26,502/sq.ft.      1
₹ 266,666/sq.ft.     1
₹ 24,390/sq.ft.      1
₹ 17,820/sq.ft.      1
₹ 12,037/sq.ft.      1
₹ 19,847/sq.ft.      1
₹ 38,251/sq.ft.      1
₹ 43,066/sq.ft.      1
₹ 12,938/sq.ft.      1
₹ 15,451/sq.ft.      1
₹ 41,762/sq.ft.      1
₹ 29,861/sq.ft.      1
₹ 24,202/sq.ft.      1
₹ 20,349/sq.ft.      1
₹ 20,566/sq.ft.      1
₹ 33,665/sq.ft.      1
₹ 6,230/sq.ft.       1
₹ 47,803/sq.ft.      1
Name: count, dtype: int64

In [ ]:
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 10,000/sq.ft.     19
₹ 8,000/sq.ft.      16
₹ 12,500/sq.ft.     16
₹ 6,666/sq.ft.      13
₹ 5,000/sq.ft.      13
₹ 8,333/sq.ft.      12
₹ 7,500/sq.ft.      12
₹ 6,000/sq.ft.      11
₹ 8,461/sq.ft.       9
₹ 9,000/sq.ft.       8
₹ 7,000/sq.ft.       8
₹ 12,000/sq.ft.      8
₹ 11,111/sq.ft.      7
₹ 6,578/sq.ft.       6
₹ 8,888/sq.ft.       6
₹ 9,230/sq.ft.       6
₹ 8,928/sq.ft.       6
₹ 11,500/sq.ft.      6
₹ 5,500/sq.ft.       6
₹ 7,692/sq.ft.       5
₹ 7,142/sq.ft.       5
₹ 16,000/sq.ft.      5
₹ 6,500/sq.ft.       5
₹ 11,428/sq.ft.      5
₹ 4,666/sq.ft.       5
₹ 4,444/sq.ft.       5
₹ 8,108/sq.ft.       5
₹ 5,384/sq.ft.       5
₹ 5,600/sq.ft.       5
₹ 4,615/sq.ft.       5
₹ 14,242/sq.ft.      5
₹ 7,641/sq.ft.       5
₹ 7,407/sq.ft.       5
₹ 8,205/sq.ft.       5
₹ 8,571/sq.ft.       5
₹ 5,556/sq.ft.       5
₹ 10,714/sq.ft.      5
₹ 7,812/sq.ft.       4
₹ 4,854/sq.ft.       4
₹ 7,317/sq.ft.       4
₹ 13,636/sq.ft.      4
₹ 6,735/sq.ft.       4
₹ 8,358/sq.ft.       4
₹ 8,445/sq.ft.       4
₹ 13,750/sq.ft.      4
₹ 4,500/sq.ft.       4
₹ 6,250/sq.ft.       4
₹ 8,474/sq.ft.       4
₹ 8,784/sq.ft.       4
₹ 4,814/sq.ft.       4
₹ 11,666/sq.ft.      4
₹ 8,139/sq.ft.       4
₹ 10,383/sq.ft.      4
₹ 9,210/sq.ft.       4
₹ 13,913/sq.ft.      4
₹ 7,250/sq.ft.       4
₹ 4,687/sq.ft.       4
₹ 8,484/sq.ft.       4
₹ 8,432/sq.ft.       4
₹ 16,666/sq.ft.      4
₹ 9,822/sq.ft.       4
₹ 5,660/sq.ft.       4
₹ 10,416/sq.ft.      4
₹ 7,496/sq.ft.       4
₹ 7,272/sq.ft.       4
₹ 15,000/sq.ft.      4
₹ 9,090/sq.ft.       4
₹ 8,787/sq.ft.       4
₹ 8,500/sq.ft.       4
₹ 8,043/sq.ft.       4
₹ 8,163/sq.ft.       4
₹ 15,384/sq.ft.      4
₹ 14,418/sq.ft.      4
₹ 16,969/sq.ft.      3
₹ 6,476/sq.ft.       3
₹ 5,325/sq.ft.       3
₹ 13,392/sq.ft.      3
₹ 8,389/sq.ft.       3
₹ 5,878/sq.ft.       3
₹ 16,470/sq.ft.      3
₹ 8,750/sq.ft.       3
₹ 7,948/sq.ft.       3
₹ 7,954/sq.ft.       3
₹ 9,972/sq.ft.       3
₹ 10,638/sq.ft.      3
₹ 6,404/sq.ft.       3
₹ 8,215/sq.ft.       3
₹ 8,078/sq.ft.       3
₹ 14,254/sq.ft.      3
₹ 6,818/sq.ft.       3
₹ 8,222/sq.ft.       3
₹ 10,500/sq.ft.      3
₹ 6,387/sq.ft.       3
₹ 11,000/sq.ft.      3
₹ 7,302/sq.ft.       3
₹ 11,363/sq.ft.      3
₹ 8,080/sq.ft.       3
₹ 7,541/sq.ft.       3
₹ 6,421/sq.ft.       3
₹ 14,430/sq.ft.      3
₹ 5,833/sq.ft.       3
₹ 6,086/sq.ft.       3
₹ 9,011/sq.ft.       3
₹ 7,150/sq.ft.       3
₹ 8,400/sq.ft.       3
₹ 7,586/sq.ft.       3
₹ 5,856/sq.ft.       3
₹ 5,555/sq.ft.       3
₹ 8,532/sq.ft.       3
₹ 7,179/sq.ft.       3
₹ 7,083/sq.ft.       3
₹ 6,593/sq.ft.       3
₹ 8,181/sq.ft.       3
₹ 8,620/sq.ft.       3
₹ 8,606/sq.ft.       3
₹ 5,238/sq.ft.       3
₹ 9,900/sq.ft.       3
₹ 5,397/sq.ft.       3
₹ 5,319/sq.ft.       3
₹ 4,800/sq.ft.       3
₹ 9,500/sq.ft.       3
₹ 6,470/sq.ft.       3
₹ 10,555/sq.ft.      3
₹ 7,467/sq.ft.       3
₹ 7,865/sq.ft.       3
₹ 7,400/sq.ft.       3
₹ 9,473/sq.ft.       3
₹ 5,735/sq.ft.       3
₹ 6,921/sq.ft.       3
₹ 13,000/sq.ft.      3
₹ 6,644/sq.ft.       3
₹ 9,615/sq.ft.       3
₹ 4,820/sq.ft.       3
₹ 14,000/sq.ft.      3
₹ 10,139/sq.ft.      3
₹ 7,549/sq.ft.       3
₹ 4,210/sq.ft.       3
₹ 4,513/sq.ft.       3
₹ 6,542/sq.ft.       3
₹ 8,886/sq.ft.       3
₹ 8,450/sq.ft.       3
₹ 10,204/sq.ft.      3
₹ 7,056/sq.ft.       3
₹ 13,870/sq.ft.      3
₹ 6,667/sq.ft.       3
₹ 4,105/sq.ft.       3
₹ 9,904/sq.ft.       3
₹ 8,148/sq.ft.       3
₹ 7,750/sq.ft.       3
₹ 8,604/sq.ft.       3
₹ 6,178/sq.ft.       2
₹ 9,135/sq.ft.       2
₹ 7,796/sq.ft.       2
₹ 10,476/sq.ft.      2
₹ 5,470/sq.ft.       2
₹ 4,400/sq.ft.       2
₹ 33,198/sq.ft.      2
₹ 7,200/sq.ft.       2
₹ 10,666/sq.ft.      2
₹ 5,189/sq.ft.       2
₹ 5,291/sq.ft.       2
₹ 6,702/sq.ft.       2
₹ 6,616/sq.ft.       2
₹ 15,151/sq.ft.      2
₹ 6,200/sq.ft.       2
₹ 7,846/sq.ft.       2
₹ 7,297/sq.ft.       2
₹ 5,528/sq.ft.       2
₹ 8,903/sq.ft.       2
₹ 6,811/sq.ft.       2
₹ 5,588/sq.ft.       2
₹ 9,128/sq.ft.       2
₹ 11,574/sq.ft.      2
₹ 7,223/sq.ft.       2
₹ 7,608/sq.ft.       2
₹ 6,655/sq.ft.       2
₹ 5,674/sq.ft.       2
₹ 13,343/sq.ft.      2
₹ 14,545/sq.ft.      2
₹ 9,166/sq.ft.       2
₹ 18,000/sq.ft.      2
₹ 4,307/sq.ft.       2
₹ 8,974/sq.ft.       2
₹ 8,670/sq.ft.       2
₹ 8,159/sq.ft.       2
₹ 7,058/sq.ft.       2
₹ 11,715/sq.ft.      2
₹ 7,174/sq.ft.       2
₹ 6,938/sq.ft.       2
₹ 5,671/sq.ft.       2
₹ 19,882/sq.ft.      2
₹ 9,791/sq.ft.       2
₹ 9,620/sq.ft.       2
₹ 6,789/sq.ft.       2
₹ 6,967/sq.ft.       2
₹ 6,024/sq.ft.       2
₹ 5,882/sq.ft.       2
₹ 13,500/sq.ft.      2
₹ 9,909/sq.ft.       2
₹ 9,876/sq.ft.       2
₹ 6,190/sq.ft.       2
₹ 6,206/sq.ft.       2
₹ 15,294/sq.ft.      2
₹ 9,978/sq.ft.       2
₹ 3,695/sq.ft.       2
₹ 11,992/sq.ft.      2
₹ 5,658/sq.ft.       2
₹ 7,758/sq.ft.       2
₹ 7,863/sq.ft.       2
₹ 11,250/sq.ft.      2
₹ 8,504/sq.ft.       2
₹ 7,097/sq.ft.       2
₹ 7,490/sq.ft.       2
₹ 6,076/sq.ft.       2
₹ 15,500/sq.ft.      2
₹ 5,150/sq.ft.       2
₹ 6,111/sq.ft.       2
₹ 7,782/sq.ft.       2
₹ 7,780/sq.ft.       2
₹ 5,111/sq.ft.       2
₹ 5,786/sq.ft.       2
₹ 6,985/sq.ft.       2
₹ 12,777/sq.ft.      2
₹ 8,517/sq.ft.       2
₹ 9,452/sq.ft.       2
₹ 6,927/sq.ft.       2
₹ 11,724/sq.ft.      2
₹ 6,377/sq.ft.       2
₹ 10,531/sq.ft.      2
₹ 5,038/sq.ft.       2
₹ 5,797/sq.ft.       2
₹ 11,627/sq.ft.      2
₹ 6,569/sq.ft.       2
₹ 11,529/sq.ft.      2
₹ 6,217/sq.ft.       2
₹ 9,062/sq.ft.       2
₹ 9,449/sq.ft.       2
₹ 8,053/sq.ft.       2
₹ 8,618/sq.ft.       2
₹ 6,686/sq.ft.       2
₹ 8,972/sq.ft.       2
₹ 7,585/sq.ft.       2
₹ 10,601/sq.ft.      2
₹ 6,510/sq.ft.       2
₹ 41,245/sq.ft.      2
₹ 9,851/sq.ft.       2
₹ 8,075/sq.ft.       2
₹ 7,727/sq.ft.       2
₹ 15,998/sq.ft.      2
₹ 11,700/sq.ft.      2
₹ 6,551/sq.ft.       2
₹ 9,677/sq.ft.       2
₹ 8,720/sq.ft.       2
₹ 6,318/sq.ft.       2
₹ 6,983/sq.ft.       2
₹ 6,739/sq.ft.       2
₹ 6,325/sq.ft.       2
₹ 6,061/sq.ft.       2
₹ 6,429/sq.ft.       2
₹ 5,100/sq.ft.       2
₹ 5,517/sq.ft.       2
₹ 9,025/sq.ft.       2
₹ 6,373/sq.ft.       2
₹ 18,271/sq.ft.      2
₹ 8,252/sq.ft.       2
₹ 16,985/sq.ft.      2
₹ 6,422/sq.ft.       2
₹ 4,909/sq.ft.       2
₹ 8,897/sq.ft.       2
₹ 8,609/sq.ft.       2
₹ 8,524/sq.ft.       2
₹ 9,600/sq.ft.       2
₹ 7,574/sq.ft.       2
₹ 7,225/sq.ft.       2
₹ 9,286/sq.ft.       2
₹ 8,006/sq.ft.       2
₹ 17,619/sq.ft.      2
₹ 8,206/sq.ft.       2
₹ 6,597/sq.ft.       2
₹ 18,181/sq.ft.      2
₹ 4,271/sq.ft.       2
₹ 14,257/sq.ft.      2
₹ 9,333/sq.ft.       2
₹ 14,214/sq.ft.      2
₹ 7,248/sq.ft.       2
₹ 10,603/sq.ft.      2
₹ 7,391/sq.ft.       2
₹ 16,960/sq.ft.      2
₹ 11,516/sq.ft.      2
₹ 13,769/sq.ft.      2
₹ 6,428/sq.ft.       2
₹ 58/sq.ft.          2
₹ 5,463/sq.ft.       2
₹ 10,370/sq.ft.      2
₹ 4,000/sq.ft.       2
₹ 5,899/sq.ft.       2
₹ 11,333/sq.ft.      2
₹ 9,182/sq.ft.       2
₹ 12,782/sq.ft.      2
₹ 8,072/sq.ft.       2
₹ 14,583/sq.ft.      2
₹ 9,259/sq.ft.       2
₹ 10,384/sq.ft.      2
₹ 10,526/sq.ft.      2
₹ 8,582/sq.ft.       2
₹ 8,310/sq.ft.       2
₹ 7,530/sq.ft.       2
₹ 5,405/sq.ft.       2
₹ 11,755/sq.ft.      2
₹ 9,146/sq.ft.       2
₹ 7,396/sq.ft.       2
₹ 4,327/sq.ft.       2
₹ 15,263/sq.ft.      2
₹ 16,747/sq.ft.      2
₹ 8,290/sq.ft.       2
₹ 8,519/sq.ft.       2
₹ 3,911/sq.ft.       2
₹ 6,333/sq.ft.       2
₹ 6,315/sq.ft.       2
₹ 7,631/sq.ft.       2
₹ 11,726/sq.ft.      2
₹ 9,263/sq.ft.       2
₹ 6,189/sq.ft.       2
₹ 13,281/sq.ft.      2
₹ 7,825/sq.ft.       2
₹ 13,224/sq.ft.      2
₹ 9,022/sq.ft.       2
₹ 12,012/sq.ft.      2
₹ 7,185/sq.ft.       2
₹ 14,478/sq.ft.      2
₹ 4,651/sq.ft.       2
₹ 14,800/sq.ft.      2
₹ 8,521/sq.ft.       2
₹ 11,028/sq.ft.      2
₹ 6,134/sq.ft.       2
₹ 16,858/sq.ft.      2
₹ 8,166/sq.ft.       2
₹ 9,027/sq.ft.       2
₹ 6,420/sq.ft.       2
₹ 10,018/sq.ft.      2
₹ 14,237/sq.ft.      2
₹ 8,433/sq.ft.       2
₹ 20,687/sq.ft.      2
₹ 12,212/sq.ft.      2
₹ 13,108/sq.ft.      2
₹ 15,551/sq.ft.      2
₹ 15,416/sq.ft.      2
₹ 5,980/sq.ft.       2
₹ 5,828/sq.ft.       2
₹ 8,518/sq.ft.       2
₹ 6,588/sq.ft.       2
₹ 8,756/sq.ft.       2
₹ 9,482/sq.ft.       2
₹ 5,599/sq.ft.       2
₹ 4,745/sq.ft.       2
₹ 6,382/sq.ft.       2
₹ 14,683/sq.ft.      2
₹ 14,303/sq.ft.      2
₹ 11,505/sq.ft.      2
₹ 5,177/sq.ft.       2
₹ 8,305/sq.ft.       2
₹ 9,589/sq.ft.       2
₹ 5,564/sq.ft.       2
₹ 6,243/sq.ft.       2
₹ 5,681/sq.ft.       2
₹ 7,884/sq.ft.       2
₹ 13,383/sq.ft.      2
₹ 6,053/sq.ft.       2
₹ 4,856/sq.ft.       2
₹ 5,056/sq.ft.       2
₹ 5,641/sq.ft.       2
₹ 5,982/sq.ft.       2
₹ 8,410/sq.ft.       2
₹ 10,516/sq.ft.      2
₹ 10,936/sq.ft.      2
₹ 7,945/sq.ft.       2
₹ 6,049/sq.ft.       2
₹ 8,024/sq.ft.       2
₹ 6,896/sq.ft.       2
₹ 6,153/sq.ft.       2
₹ 9,306/sq.ft.       2
₹ 16,363/sq.ft.      2
₹ 13,709/sq.ft.      2
₹ 8,457/sq.ft.       2
₹ 5,454/sq.ft.       2
₹ 8,424/sq.ft.       2
₹ 7,987/sq.ft.       2
₹ 9,020/sq.ft.       2
₹ 8,412/sq.ft.       2
₹ 8,835/sq.ft.       2
₹ 4,761/sq.ft.       2
₹ 6,465/sq.ft.       2
₹ 6,679/sq.ft.       2
₹ 6,141/sq.ft.       2
₹ 8,376/sq.ft.       2
₹ 8,536/sq.ft.       2
₹ 19,000/sq.ft.      2
₹ 8,324/sq.ft.       2
₹ 14,285/sq.ft.      2
₹ 6,353/sq.ft.       2
₹ 6,406/sq.ft.       2
₹ 6,839/sq.ft.       2
₹ 7,716/sq.ft.       2
₹ 9,743/sq.ft.       2
₹ 5,839/sq.ft.       2
₹ 11,765/sq.ft.      2
₹ 17,039/sq.ft.      2
₹ 8,846/sq.ft.       2
₹ 10,599/sq.ft.      2
₹ 6,338/sq.ft.       2
₹ 8,035/sq.ft.       2
₹ 8,036/sq.ft.       2
₹ 8,611/sq.ft.       2
₹ 14,785/sq.ft.      2
₹ 12,022/sq.ft.      2
₹ 13,270/sq.ft.      2
₹ 19,767/sq.ft.      2
₹ 7,765/sq.ft.       2
₹ 6,402/sq.ft.       2
₹ 9,950/sq.ft.       2
₹ 10,553/sq.ft.      2
₹ 9,742/sq.ft.       2
₹ 13,076/sq.ft.      2
₹ 6,987/sq.ft.       2
₹ 5,744/sq.ft.       2
₹ 8,294/sq.ft.       2
₹ 3,477/sq.ft.       2
₹ 8,814/sq.ft.       2
₹ 8,031/sq.ft.       2
₹ 9,550/sq.ft.       2
₹ 8,237/sq.ft.       2
₹ 14,615/sq.ft.      2
₹ 7,610/sq.ft.       2
₹ 7,350/sq.ft.       2
₹ 9,074/sq.ft.       2
₹ 7,908/sq.ft.       2
₹ 9,007/sq.ft.       2
₹ 8,733/sq.ft.       2
₹ 9,672/sq.ft.       2
₹ 9,797/sq.ft.       2
₹ 9,922/sq.ft.       2
₹ 7,359/sq.ft.       2
₹ 5,521/sq.ft.       2
₹ 6,812/sq.ft.       2
₹ 5,128/sq.ft.       2
₹ 11,727/sq.ft.      2
₹ 10,489/sq.ft.      2
₹ 15,195/sq.ft.      2
₹ 5,929/sq.ft.       2
₹ 8,283/sq.ft.       2
₹ 8,411/sq.ft.       2
₹ 8,834/sq.ft.       2
₹ 6,692/sq.ft.       2
₹ 5,252/sq.ft.       2
₹ 13,928/sq.ft.      2
₹ 7,850/sq.ft.       2
₹ 7,817/sq.ft.       2
₹ 9,565/sq.ft.       2
₹ 15,454/sq.ft.      2
₹ 6,571/sq.ft.       2
₹ 6,774/sq.ft.       2
₹ 11,412/sq.ft.      2
₹ 4,857/sq.ft.       2
₹ 8,632/sq.ft.       2
₹ 5,513/sq.ft.       2
₹ 9,139/sq.ft.       2
₹ 11,336/sq.ft.      2
₹ 6,029/sq.ft.       2
₹ 10,545/sq.ft.      2
₹ 6,313/sq.ft.       2
₹ 19,747/sq.ft.      2
₹ 7,878/sq.ft.       2
₹ 9,105/sq.ft.       2
₹ 10,699/sq.ft.      2
₹ 7,751/sq.ft.       2
₹ 5,725/sq.ft.       2
₹ 9,433/sq.ft.       2
₹ 10,651/sq.ft.      2
₹ 5,808/sq.ft.       2
₹ 4,080/sq.ft.       2
₹ 10,237/sq.ft.      2
₹ 12,444/sq.ft.      2
₹ 5,896/sq.ft.       2
₹ 5,424/sq.ft.       2
₹ 7,857/sq.ft.       2
₹ 8,600/sq.ft.       2
₹ 8,453/sq.ft.       2
₹ 13,430/sq.ft.      2
₹ 16,608/sq.ft.      2
₹ 5,649/sq.ft.       2
₹ 21,538/sq.ft.      2
₹ 9,854/sq.ft.       2
₹ 11,125/sq.ft.      2
₹ 5,820/sq.ft.       2
₹ 6,254/sq.ft.       2
₹ 6,825/sq.ft.       2
₹ 6,647/sq.ft.       2
₹ 9,642/sq.ft.       2
₹ 11,694/sq.ft.      2
₹ 5,614/sq.ft.       2
₹ 12,222/sq.ft.      2
₹ 10,596/sq.ft.      2
₹ 7,014/sq.ft.       2
₹ 5,825/sq.ft.       2
₹ 8,100/sq.ft.       2
₹ 6,455/sq.ft.       2
₹ 8,947/sq.ft.       2
₹ 5,683/sq.ft.       2
₹ 7,449/sq.ft.       2
₹ 13,991/sq.ft.      2
₹ 8,279/sq.ft.       2
₹ 200,000/sq.ft.     2
₹ 6,538/sq.ft.       2
₹ 6,950/sq.ft.       2
₹ 5,714/sq.ft.       2
₹ 7,627/sq.ft.       2
₹ 6,506/sq.ft.       2
₹ 6,722/sq.ft.       2
₹ 12,250/sq.ft.      2
₹ 13,333/sq.ft.      2
₹ 6,859/sq.ft.       2
₹ 7,234/sq.ft.       2
₹ 6,129/sq.ft.       2
₹ 4,723/sq.ft.       2
₹ 4,818/sq.ft.       2
₹ 4,200/sq.ft.       2
₹ 6,361/sq.ft.       2
₹ 6,493/sq.ft.       2
₹ 18,518/sq.ft.      2
₹ 6,209/sq.ft.       2
₹ 5,284/sq.ft.       2
₹ 5,789/sq.ft.       1
₹ 50,000/sq.ft.      1
₹ 5,367/sq.ft.       1
₹ 4,596/sq.ft.       1
₹ 4,033/sq.ft.       1
₹ 4,879/sq.ft.       1
₹ 6,505/sq.ft.       1
₹ 6,761/sq.ft.       1
₹ 4,700/sq.ft.       1
₹ 12,700/sq.ft.      1
₹ 5,257/sq.ft.       1
₹ 6,064/sq.ft.       1
₹ 17,548/sq.ft.      1
₹ 5,576/sq.ft.       1
₹ 4,657/sq.ft.       1
₹ 7,079/sq.ft.       1
₹ 12,110/sq.ft.      1
₹ 11,739/sq.ft.      1
₹ 14,074/sq.ft.      1
₹ 7,146/sq.ft.       1
₹ 12,400/sq.ft.      1
₹ 13,875/sq.ft.      1
₹ 13,846/sq.ft.      1
₹ 6,708/sq.ft.       1
₹ 6,580/sq.ft.       1
₹ 6,514/sq.ft.       1
₹ 13,929/sq.ft.      1
₹ 17,285/sq.ft.      1
₹ 6,819/sq.ft.       1
₹ 9,133/sq.ft.       1
₹ 12,325/sq.ft.      1
₹ 5,541/sq.ft.       1
₹ 14,557/sq.ft.      1
₹ 13,878/sq.ft.      1
₹ 13,888/sq.ft.      1
₹ 9,036/sq.ft.       1
₹ 9,980/sq.ft.       1
₹ 7,065/sq.ft.       1
₹ 5,499/sq.ft.       1
₹ 4,864/sq.ft.       1
₹ 13,528/sq.ft.      1
₹ 9,622/sq.ft.       1
₹ 9,051/sq.ft.       1
₹ 4,022/sq.ft.       1
₹ 7,437/sq.ft.       1
₹ 21,013/sq.ft.      1
₹ 6,523/sq.ft.       1
₹ 14,623/sq.ft.      1
₹ 13,725/sq.ft.      1
₹ 6,953/sq.ft.       1
₹ 8,724/sq.ft.       1
₹ 24,211/sq.ft.      1
₹ 20,533/sq.ft.      1
₹ 15,469/sq.ft.      1
₹ 10,761/sq.ft.      1
₹ 10,994/sq.ft.      1
₹ 12,144/sq.ft.      1
₹ 12,127/sq.ft.      1
₹ 14,536/sq.ft.      1
₹ 11,052/sq.ft.      1
₹ 10,953/sq.ft.      1
₹ 9,117/sq.ft.       1
₹ 9,387/sq.ft.       1
₹ 3,935/sq.ft.       1
₹ 11,860/sq.ft.      1
₹ 9,266/sq.ft.       1
₹ 10,334/sq.ft.      1
₹ 16,580/sq.ft.      1
₹ 16,750/sq.ft.      1
₹ 8,839/sq.ft.       1
₹ 8,759/sq.ft.       1
₹ 14,983/sq.ft.      1
₹ 11,914/sq.ft.      1
₹ 12,571/sq.ft.      1
₹ 8,242/sq.ft.       1
₹ 12,169/sq.ft.      1
₹ 17,484/sq.ft.      1
₹ 7,403/sq.ft.       1
₹ 35,483/sq.ft.      1
₹ 6,215/sq.ft.       1
₹ 14,727/sq.ft.      1
₹ 8,679/sq.ft.       1
₹ 14,090/sq.ft.      1
₹ 6,052/sq.ft.       1
₹ 14,987/sq.ft.      1
₹ 6,060/sq.ft.       1
₹ 8,516/sq.ft.       1
₹ 10,028/sq.ft.      1
₹ 15,007/sq.ft.      1
₹ 9,203/sq.ft.       1
₹ 10,178/sq.ft.      1
₹ 4,531/sq.ft.       1
₹ 5,859/sq.ft.       1
₹ 14,068/sq.ft.      1
₹ 7,789/sq.ft.       1
₹ 10,365/sq.ft.      1
₹ 8,172/sq.ft.       1
₹ 10,080/sq.ft.      1
₹ 10,461/sq.ft.      1
₹ 8,646/sq.ft.       1
₹ 10,595/sq.ft.      1
₹ 4,836/sq.ft.       1
₹ 5,004/sq.ft.       1
₹ 13,678/sq.ft.      1
₹ 12,599/sq.ft.      1
₹ 11,358/sq.ft.      1
₹ 5,418/sq.ft.       1
₹ 8,825/sq.ft.       1
₹ 9,850/sq.ft.       1
₹ 10,224/sq.ft.      1
₹ 10,262/sq.ft.      1
₹ 13,671/sq.ft.      1
₹ 8,922/sq.ft.       1
₹ 5,490/sq.ft.       1
₹ 6,242/sq.ft.       1
₹ 11,451/sq.ft.      1
₹ 8,998/sq.ft.       1
₹ 7,096/sq.ft.       1
₹ 14,179/sq.ft.      1
₹ 9,238/sq.ft.       1
₹ 5,930/sq.ft.       1
₹ 8,062/sq.ft.       1
₹ 6,002/sq.ft.       1
₹ 6,846/sq.ft.       1
₹ 6,286/sq.ft.       1
₹ 15,685/sq.ft.      1
₹ 13,758/sq.ft.      1
₹ 8,204/sq.ft.       1
₹ 16,266/sq.ft.      1
₹ 12,658/sq.ft.      1
₹ 13,580/sq.ft.      1
₹ 20,388/sq.ft.      1
₹ 12,846/sq.ft.      1
₹ 14,843/sq.ft.      1
₹ 6,852/sq.ft.       1
₹ 5,762/sq.ft.       1
₹ 15,531/sq.ft.      1
₹ 12,484/sq.ft.      1
₹ 3,953/sq.ft.       1
₹ 4,308/sq.ft.       1
₹ 6,265/sq.ft.       1
₹ 7,116/sq.ft.       1
₹ 10,162/sq.ft.      1
₹ 6,310/sq.ft.       1
₹ 4,370/sq.ft.       1
₹ 12,190/sq.ft.      1
₹ 13,253/sq.ft.      1
₹ 12,152/sq.ft.      1
₹ 15,185/sq.ft.      1
₹ 5,973/sq.ft.       1
₹ 6,453/sq.ft.       1
₹ 7,230/sq.ft.       1
₹ 6,585/sq.ft.       1
₹ 11,686/sq.ft.      1
₹ 13,571/sq.ft.      1
₹ 7,525/sq.ft.       1
₹ 11,218/sq.ft.      1
₹ 8,270/sq.ft.       1
₹ 11,713/sq.ft.      1
₹ 21,577/sq.ft.      1
₹ 10,529/sq.ft.      1
₹ 10,147/sq.ft.      1
₹ 6,227/sq.ft.       1
₹ 10,727/sq.ft.      1
₹ 5,942/sq.ft.       1
₹ 10,037/sq.ft.      1
₹ 8,395/sq.ft.       1
₹ 5,597/sq.ft.       1
₹ 8,916/sq.ft.       1
₹ 8,875/sq.ft.       1
₹ 5,207/sq.ft.       1
₹ 19,174/sq.ft.      1
₹ 7,590/sq.ft.       1
₹ 6,801/sq.ft.       1
₹ 7,734/sq.ft.       1
₹ 4,355/sq.ft.       1
₹ 4,528/sq.ft.       1
₹ 6,961/sq.ft.       1
₹ 7,646/sq.ft.       1
₹ 10,174/sq.ft.      1
₹ 14,177/sq.ft.      1
₹ 5,867/sq.ft.       1
₹ 5,717/sq.ft.       1
₹ 10,841/sq.ft.      1
₹ 11,174/sq.ft.      1
₹ 6,625/sq.ft.       1
₹ 8,793/sq.ft.       1
₹ 13,352/sq.ft.      1
₹ 15,561/sq.ft.      1
₹ 6,530/sq.ft.       1
₹ 11,817/sq.ft.      1
₹ 12,372/sq.ft.      1
₹ 8,708/sq.ft.       1
₹ 9,512/sq.ft.       1
₹ 7,380/sq.ft.       1
₹ 18,126/sq.ft.      1
₹ 7,180/sq.ft.       1
₹ 7,072/sq.ft.       1
₹ 12,047/sq.ft.      1
₹ 9,039/sq.ft.       1
₹ 8,623/sq.ft.       1
₹ 8,704/sq.ft.       1
₹ 9,365/sq.ft.       1
₹ 10,041/sq.ft.      1
₹ 9,627/sq.ft.       1
₹ 10,786/sq.ft.      1
₹ 10,443/sq.ft.      1
₹ 8,580/sq.ft.       1
₹ 14,563/sq.ft.      1
₹ 15,514/sq.ft.      1
₹ 9,528/sq.ft.       1
₹ 6,826/sq.ft.       1
₹ 12,788/sq.ft.      1
₹ 10,567/sq.ft.      1
₹ 11,470/sq.ft.      1
₹ 11,204/sq.ft.      1
₹ 11,294/sq.ft.      1
₹ 15,906/sq.ft.      1
₹ 3,309/sq.ft.       1
₹ 4,193/sq.ft.       1
₹ 9,497/sq.ft.       1
₹ 4,746/sq.ft.       1
₹ 9,052/sq.ft.       1
₹ 8,023/sq.ft.       1
₹ 7,208/sq.ft.       1
₹ 7,443/sq.ft.       1
₹ 9,030/sq.ft.       1
₹ 6,424/sq.ft.       1
₹ 11,489/sq.ft.      1
₹ 9,655/sq.ft.       1
₹ 9,169/sq.ft.       1
₹ 10,799/sq.ft.      1
₹ 12,589/sq.ft.      1
₹ 10,853/sq.ft.      1
₹ 5,531/sq.ft.       1
₹ 6,019/sq.ft.       1
₹ 6,104/sq.ft.       1
₹ 10,954/sq.ft.      1
₹ 6,888/sq.ft.       1
₹ 9,212/sq.ft.       1
₹ 6,661/sq.ft.       1
₹ 15,160/sq.ft.      1
₹ 12,140/sq.ft.      1
₹ 10,814/sq.ft.      1
₹ 13,790/sq.ft.      1
₹ 6,713/sq.ft.       1
₹ 14,079/sq.ft.      1
₹ 12,235/sq.ft.      1
₹ 7,196/sq.ft.       1
₹ 6,932/sq.ft.       1
₹ 12,178/sq.ft.      1
₹ 9,584/sq.ft.       1
₹ 12,813/sq.ft.      1
₹ 11,764/sq.ft.      1
₹ 16,129/sq.ft.      1
₹ 8,553/sq.ft.       1
₹ 10,755/sq.ft.      1
₹ 6,851/sq.ft.       1
₹ 8,256/sq.ft.       1
₹ 5,026/sq.ft.       1
₹ 7,636/sq.ft.       1
₹ 7,928/sq.ft.       1
₹ 9,393/sq.ft.       1
₹ 8,813/sq.ft.       1
₹ 10,465/sq.ft.      1
₹ 9,563/sq.ft.       1
₹ 13,589/sq.ft.      1
₹ 10,645/sq.ft.      1
₹ 8,541/sq.ft.       1
₹ 15,418/sq.ft.      1
₹ 10,901/sq.ft.      1
₹ 6,163/sq.ft.       1
₹ 7,991/sq.ft.       1
₹ 3,152/sq.ft.       1
₹ 14,375/sq.ft.      1
₹ 16,959/sq.ft.      1
₹ 5,422/sq.ft.       1
₹ 5,607/sq.ft.       1
₹ 6,609/sq.ft.       1
₹ 8,818/sq.ft.       1
₹ 7,554/sq.ft.       1
₹ 11,233/sq.ft.      1
₹ 6,641/sq.ft.       1
₹ 7,339/sq.ft.       1
₹ 12,134/sq.ft.      1
₹ 7,167/sq.ft.       1
₹ 8,320/sq.ft.       1
₹ 11,438/sq.ft.      1
₹ 24,963/sq.ft.      1
₹ 15,510/sq.ft.      1
₹ 12,544/sq.ft.      1
₹ 9,783/sq.ft.       1
₹ 14,950/sq.ft.      1
₹ 7,260/sq.ft.       1
₹ 28,101/sq.ft.      1
₹ 8,051/sq.ft.       1
₹ 13,690/sq.ft.      1
₹ 5,788/sq.ft.       1
₹ 13,125/sq.ft.      1
₹ 5,505/sq.ft.       1
₹ 14,598/sq.ft.      1
₹ 11,227/sq.ft.      1
₹ 6,975/sq.ft.       1
₹ 5,887/sq.ft.       1
₹ 13,318/sq.ft.      1
₹ 12,371/sq.ft.      1
₹ 8,769/sq.ft.       1
₹ 11,868/sq.ft.      1
₹ 12,732/sq.ft.      1
₹ 11,338/sq.ft.      1
₹ 12,533/sq.ft.      1
₹ 5,605/sq.ft.       1
₹ 10,449/sq.ft.      1
₹ 11,050/sq.ft.      1
₹ 10,825/sq.ft.      1
₹ 6,369/sq.ft.       1
₹ 14,040/sq.ft.      1
₹ 7,652/sq.ft.       1
₹ 9,933/sq.ft.       1
₹ 4,961/sq.ft.       1
₹ 18,500/sq.ft.      1
₹ 16,050/sq.ft.      1
₹ 12,818/sq.ft.      1
₹ 7,392/sq.ft.       1
₹ 12,627/sq.ft.      1
₹ 7,220/sq.ft.       1
₹ 26,790/sq.ft.      1
₹ 21,360/sq.ft.      1
₹ 16,486/sq.ft.      1
₹ 11,121/sq.ft.      1
₹ 14,871/sq.ft.      1
₹ 5,747/sq.ft.       1
₹ 6,267/sq.ft.       1
₹ 13,837/sq.ft.      1
₹ 11,966/sq.ft.      1
₹ 12,471/sq.ft.      1
₹ 19,285/sq.ft.      1

In [ ]:
df['price_per_sqft']=='4/sq.ft.'

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
26      False
27      False
28      False
29      False
30      False
31      False
32      False
33      False
34      False
35      False
36      False
37      False
38      False
39      False
40      False
41      False
42      False
43      False
44      False
45      False
46      False
47      False
48      False
49      False
50      False
51      False
52      False
53      False
54      False
55      False
56      False
57      False
58      False
59      False
60      False
61      False
62      False
63      False
64      False
65      False
66      False
67      False
68      False
69      False
70      False
71      False
72      False
73      False
74      False
75      False
76      False
77      False
78      False
79      False
80      False
81      False
82      False
83      False
84      False
85      False
86      False
87      False
88      False
89      False
90      False
91      False
92      False
93      False
94      False
95      False
96      False
97      False
98      False
99      False
100     False
101     False
102     False
103     False
104     False
105     False
106     False
107     False
108     False
109     False
110     False
111     False
112     False
113     False
114     False
115     False
116     False
117     False
118     False
119     False
120     False
121     False
122     False
123     False
124     False
125     False
126     False
127     False
128     False
129     False
130     False
131     False
132     False
133     False
134     False
135     False
136     False
137     False
138     False
139     False
140     False
141     False
142     False
143     False
144     False
145     False
146     False
147     False
148     False
149     False
150     False
151     False
152     False
153     False
154     False
155     False
156     False
157     False
158     False
159     False
160     False
161     False
162     False
163     False
164     False
165     False
166     False
167     False
168     False
169     False
170     False
171     False
172     False
173     False
174     False
175     False
176     False
177     False
178     False
179     False
180     False
181     False
182     False
183     False
184     False
185     False
186     False
187     False
188     False
189     False
190     False
191     False
192     False
193     False
194     False
195     False
196     False
197     False
198     False
199     False
200     False
201     False
202     False
203     False
204     False
205     False
206     False
207     False
208     False
209     False
210     False
211     False
212     False
213     False
214     False
215     False
216     False
217     False
218     False
219     False
220     False
221     False
222     False
223     False
224     False
225     False
226     False
227     False
228     False
229     False
230     False
231     False
232     False
233     False
234     False
235     False
236     False
237     False
238     False
239     False
240     False
241     False
242     False
243     False
244     False
245     False
246     False
247     False
248     False
249     False
250     False
251     False
252     False
253     False
254     False
255     False
256     False
257     False
258     False
259     False
260     False
261     False
262     False
263     False
264     False
265     False
266     False
267     False
268     False
269     False
270     False
271     False
272     False
273     False
274     False
275     False
276     False
277     False
278     False
279     False
280     False
281     False
282     False
283     False
284     False
285     False
286     False
287     False
288     False
289     False
290     False
291     False
292     False
293     False
294     False
295     False
296     False
297     False
298     False
299     False
300     False
301     False
302     False
303     False
304     False
305     False
306     False
307     False
308     False
309     False
310     False
311     False
312     False
313     False
314     False
315     False
316     False
317     False
318     False
319     False
320     False
321     False
322     False
323     False
324     False
325     False
326     False
327     False
328     False
329     False
330     False
331     False
332     False
333     False
334     False
335     False
336     False
337     False
338     False
339     False
340     False
341     False
342     False
343     False
344     False
345     False
346     False
347     False
348     False
349     False
350     False
351     False
352     False
353     False
354     False
355     False
356     False
357     False
358     False
359     False
360     False
361     False
362     False
363     False
364     False
365     False
366     False
367     False
368     False
369     False
370     False
371     False
372     False
373     False
374     False
375     False
376     False
377     False
378     False
379     False
380     False
381     False
382     False
383     False
384     False
385     False
386     False
387     False
388     False
389     False
390     False
391     False
392     False
393     False
394     False
395     False
396     False
397     False
398     False
399     False
400     False
401     False
402     False
403     False
404     False
405     False
406     False
407     False
408     False
409     False
410     False
411     False
412     False
413     False
414     False
415     False
416     False
417     False
418     False
419     False
420     False
421     False
422     False
423     False
424     False
425     False
426     False
427     False
428     False
429     False
430     False
431     False
432     False
433     False
434     False
435     False
436     False
437     False
438     False
439     False
440     False
441     False
442     False
443     False
444     False
445     False
446     False
447     False
448     False
449     False
450     False
451     False
452     False
453     False
454     False
455     False
456     False
457     False
458     False
459     False
460     False
461     False
462     False
463     False
464     False
465     False
466     False
467     False
468     False
469     False
470     False
471     False
472     False
473     False
474     False
475     False
476     False
477     False
478     False
479     False
480     False
481     False
482     False
483     False
484     False
485     False
486     False
487     False
488     False
489     False
490     False
491     False
492     False
493     False
494     False
495     False
496     False
497     False
498     False
499     False
500     False
501     False
502     False
503     False
504     False
505     False
506     False
507     False
508     False
509     False
510     False
511     False
512     False
513     False
514     False
515     False
516     False
517     False
518     False
519     False
520     False
521     False
522     False
523     False
524     False
525     False
526     False
527     False
528     False
529     False
530     False
531     False
532     False
533     False
534     False
535     False
536     False
537     False
538     False
539     False
540     False
541     False
542     False
543     False
544     False
545     False
546     False
547     False
548     False
549     False
550     False
551     False
552     False
553     False
554     False
555     False
556     False
557     False
558     False
559     False
560     False
561     False
562     False
563     False
564     False
565     False
566     False
567     False
568     False
569     False
570     False
571     False
572     False
573     False
574     False
575     False
576     False
577     False
578     False
579     False
580     False
581     False
582     False
583     False
584     False
585     False
586     False
587     False
588     False
589     False
590     False
591     False
592     False
593     False
594     False
595     False
596     False
597     False
598     False
599     False
600     False
601     False
602     False
603     False
604     False
605     False
606     False
607     False
608     False
609     False
610     False
611     False
612     False
613     False
614     False
615     False
616     False
617     False
618     False
619     False
620     False
621     False
622     False
623     False
624     False
625     False
626     False
627     False
628     False
629     False
630     False
631     False
632     False
633     False
634     False
635     False
636     False
637     False
638     False
639     False
640     False
641     False
642     False
643     False
644     False
645     False
646     False
647     False
648     False
649     False
650     False
651     False
652     False
653     False
654     False
655     False
656     False
657     False
658     False
659     False
660     False
661     False
662     False
663     False
664     False
665     False
666     False
667     False
668     False
669     False
670     False
671     False
672     False
673     False
674     False
675     False
676     False
677     False
678     False
679     False
680     False
681     False
682     False
683     False
684     False
685     False
686     False
687     False
688     False
689     False
690     False
691     False
692     False
693     False
694     False
695     False
696     False
697     False
698     False
699     False
700     False
701     False
702     False
703     False
704     False
705     False
706     False
707     False
708     False
709     False
710     False
711     False
712     False
713     False
714     False
715     False
716     False
717     False
718     False
719     False
720     False
721     False
722     False
723     False
724     False
725     False
726     False
727     False
728     False
729     False
730     False
731     False
732     False
733     False
734     False
735     False
736     False
737     False
738     False
739     False
740     False
741     False
742     False
743     False
744     False
745     False
746     False
747     False
748     False
749     False
750     False
751     False
752     False
753     False
754     False
755     False
756     False
757     False
758     False
759     False
760     False
761     False
762     False
763     False
764     False
765     False
766     False
767     False
768     False
769     False
770     False
771     False
772     False
773     False
774     False
775     False
776     False
777     False
778     False
779     False
780     False
781     False
782     False
783     False
784     False
785     False
786     False
787     False
788     False
789     False
790     False
791     False
792     False
793     False
794     False
795     False
796     False
797     False
798     False
799     False
800     False
801     False
802     False
803     False
804     False
805     False
806     False
807     False
808     False
809     False
810     False
811     False
812     False
813     False
814     False
815     False
816     False
817     False
818     False
819     False
820     False
821     False
822     False
823     False
824     False
825     False
826     False
827     False
828     False
829     False
830     False
831     False
832     False
833     False
834     False
835     False
836     False
837     False
838     False
839     False
840     False
841     False
842     False
843     False
844     False
845     False
846     False
847     False
848     False
849     False
850     False
851     False
852     False
853     False
854     False
855     False
856     False
857     False
858     False
859     False
860     False
861     False
862     False
863     False
864     False
865     False
866     False
867     False
868     False
869     False
870     False
871     False
872     False
873     False
874     False
875     False
876     False
877     False
878     False
879     False
880     False
881     False
882     False
883     False
884     False
885     False
886     False
887     False
888     False
889     False
890     False
891     False
892     False
893     False
894     False
895     False
896     False
897     False
898     False
899     False
900     False
901     False
902     False
903     False
904     False
905     False
906     False
907     False
908     False
909     False
910     False
911     False
912     False
913     False
914     False
915     False
916     False
917     False
918     False
919     False
920     False
921     False
922     False
923     False
924     False
925     False
926     False
927     False
928     False
929     False
930     False
931     False
932     False
933     False
934     False
935     False
936     False
937     False
938     False
939     False
940     False
941     False
942     False
943     False
944     False
945     False
946     False
947     False
948     False
949     False
950     False
951     False
952     False
953     False
954     False
955     False
956     False
957     False
958     False
959     False
960     False
961     False
962     False
963     False
964     False
965     False
966     False
967     False
968     False
969     False
970     False
971     False
972     False
973     False
974     False
975     False
976     False
977     False
978     False
979     False
980     False
981     False
982     False
983     False
984     False
985     False
986     False
987     False
988     False
989     False
990     False
991     False
992     False
993     False
994     False
995     False
996     False
997     False
998     False
999     False
1000    False
1001    False
1002    False
1003    False
1004    False
1005    False
1006    False
1007    False
1008    False
1009    False
1010    False
1011    False
1012    False
1013    False
1014    False
1015    False
1016    False
1017    False
1018    False
1019    False
1020    False
1021    False
1022    False
1023    False
1024    False
1025    False
1026    False
1027    False
1028    False
1029    False
1030    False
1031    False
1032    False
1033    False
1034    False
1035    False
1036    False
1037    False
1038    False
1039    False
1040    False
1041    False
1042    False
1043    False
1044    False
1045    False
1046    False
1047    False
1048    False
1049    False
1050    False
1051    False
1052    False
1053    False
1054    False
1055    False
1056    False
1057    False
1058    False
1059    False
1060    False
1061    False
1062    False
1063    False
1064    False
1065    False
1066    False
1067    False
1068    False
1069    False
1070    False
1071    False
1072    False
1073    False
1074    False
1075    False
1076    False
1077    False
1078    False
1079    False
1080    False
1081    False
1082    False
1083    False
1084    False
1085    False
1086    False
1087    False
1088    False
1089    False
1090    False
1091    False
1092    False
1093    False
1094    False
1095    False
1096    False
1097    False
1098    False
1099    False
1100    False
1101    False
1102    False
1103    False
1104    False
1105    False
1106    False
1107    False
1108    False
1109    False
1110    False
1111    False
1112    False
1113    False
1114    False
1115    False
1116    False
1117    False
1118    False
1119    False
1120    False
1121    False
1122    False
1123    False
1124    False
1125    False
1126    False
1127    False
1128    False
1129    False
1130    False
1131    False
1132    False
1133    False
1134    False
1135    False
1136    False
1137    False
1138    False
1139    False
1140    False
1141    False
1142    False
1143    False
1144    False
1145    False
1146    False
1147    False
1148    False
1149    False
1150    False
1151    False
1152    False
1153    False
1154    False
1155    False
1156    False
1157    False
1158    False
1159    False
1160    False
1161    False
1162    False
1163    False
1164    False
1165    False
1166    False
1167    False
1168    False
1169    False
1170    False
1171    False
1172    False
1173    False
1174    False
1175    False
1176    False
1177    False
1178    False
1179    False
1180    False
1181    False
1182    False
1183    False
1184    False
1185    False
1186    False
1187    False
1188    False
1189    False
1190    False
1191    False
1192    False
1193    False
1194    False
1195    False
1196    False
1197    False
1198    False
1199    False
1200    False
1201    False
1202    False
1203    False
1204    False
1205    False
1206    False
1207    False
1208    False
1209    False
1210    False
1211    False
1212    False
1213    False
1214    False
1215    False
1216    False
1217    False
1218    False
1219    False
1220    False
1221    False
1222    False
1223    False
1224    False
1225    False
1226    False
1227    False
1228    False
1229    False
1230    False
1231    False
1232    False
1233    False
1234    False
1235    False
1236    False
1237    False
1238    False
1239    False
1240    False
1241    False
1242    False
1243    False
1244    False
1245    False
1246    False
1247    False
1248    False
1249    False
1250    False
1251    False
1252    False
1253    False
1254    False
1255    False
1256    False
1257    False
1258    False
1259    False
1260    False
1261    False
1262    False
1263    False
1264    False
1265    False
1266    False
1267    False
1268    False
1269    False
1270    False
1271    False
1272    False
1273    False
1274    False
1275    False
1276    False
1277    False
1278    False
1279    False
1280    False
1281    False
1282    False
1283    False
1284    False
1285    False
1286    False
1287    False
1288    False
1289    False
1290    False
1291    False
1292    False
1293    False
1294    False
1295    False
1296    False
1297    False
1298    False
1299    False
1300    False
1301    False
1302    False
1303    False
1304    False
1305    False
1306    False
1307    False
1308    False
1309    False
1310    False
1311    False
1312    False
1313    False
1314    False
1315    False
1316    False
1317    False
1318    False
1319    False
1320    False
1321    False
1322    False
1323    False
1324    False
1325    False
1326    False
1327    False
1328    False
1329    False
1330    False
1331    False
1332    False
1333    False
1334    False
1335    False
1336    False
1337    False
1338    False
1339    False
1340    False
1341    False
1342    False
1343    False
1344    False
1345    False
1346    False
1347    False
1348    False
1349    False
1350    False
1351    False
1352    False
1353    False
1354    False
1355    False
1356    False
1357    False
1358    False
1359    False
1360    False
1361    False
1362    False
1363    False
1364    False
1365    False
1366    False
1367    False
1368    False
1369    False
1370    False
1371    False
1372    False
1373    False
1374    False
1375    False
1376    False
1377    False
1378    False
1379    False
1380    False
1381    False
1382    False
1383    False
1384    False
1385    False
1386    False
1387    False
1388    False
1389    False
1390    False
1391    False
1392    False
1393    False
1394    False
1395    False
1396    False
1397    False
1398    False
1399    False
1400    False
1401    False
1402    False
1403    False
1404    False
1405    False
1406    False
1407    False
1408    False
1409    False
1410    False
1411    False
1412    False
1413    False
1414    False
1415    False
1416    False
1417    False
1418    False
1419    False
1420    False
1421    False
1422    False
1423    False
1424    False
1425    False
1426    False
1427    False
1428    False

In [30]:
df['price_per_sqft'] = df['price_per_sqft'] = (
    df['price_per_sqft']
    .str.split('/')
    .str.get(0)
    .str.replace('₹','', regex=False)
    .str.replace(',','', regex=False)
    .str.strip()
)

df['price_per_sqft'] = pd.to_numeric(df['price_per_sqft'], errors='coerce')

In [31]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [32]:
df['bedRoom'].value_counts()

bedRoom
4 Bedrooms     232
5 Bedrooms     194
3 Bedrooms     146
2 Bedrooms      88
6 Bedrooms      81
9 Bedrooms      45
1 Bedroom       38
8 Bedrooms      33
7 Bedrooms      31
12 Bedrooms     28
10 Bedrooms     21
16 Bedrooms     12
13 Bedrooms      4
11 Bedrooms      2
19 Bedrooms      2
18 Bedrooms      2
21 Bedrooms      1
20 Bedrooms      1
36 Bedrooms      1
34 Bedrooms      1
14 Bedrooms      1
Name: count, dtype: int64

In [33]:
df[df['bedRoom'].isnull()]

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
60,4 Bedroom House for sale in Sector 86 Gurgaon,dlf new town heights,NaN,7718.0,(297 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,8 Bedroom House for sale in B1 Block Sector 57...,independent,NaN,25535.0,(135 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,6 Bedroom House for sale in DLF Phase 1,independent,NaN,1859.0,(420 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,6 Bedroom House for sale in Sushant Lok Phase 3,ansal sushant residency,NaN,17037.0,(251 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,6 Bedroom House for sale in Sushant Lok Phase 3,ansals florence villa,NaN,10579.0,(321 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,4 Bedroom House for sale in DLF Phase 4,independent,NaN,42194.0,(264 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,8 Bedroom House for sale in Uppals Southend,independent,NaN,15625.0,(268 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,6 Bedroom House for sale in Uppals Southend,uppal southend,NaN,15278.0,(268 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,201388.0,(33 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,4 Bedroom House for sale in Malibu Town,independent,NaN,17187.0,(54 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,5 Bedroom House for sale in Sector 33 Gurgaon,unitech uniworld resorts,NaN,NaN,(420 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,5 Bedroom House for sale in DLF Phase 1,independent,NaN,44444.0,(418 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,3 Bedroom House for sale in South City 1,dlf south city 1,NaN,18928.0,(201 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13622.0,(467-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
76,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13909.0,(384-392 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
79,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16058.0,(606-754 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
80,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16058.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
81,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13623.0,(467-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
82,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13910.0,(294-418 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
83,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13910.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
84,4 Bedroom House for sale in Sector 112 Gurgaon,experion windchants,NaN,12027.0,(590-687 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 112 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","Experion windchants in sector 112, gurgaon by ...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
85,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,15700.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
86,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,19708.0,(606 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
87,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16039.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
88,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,NaN,13331.0,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
89,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(468-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
90,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(292-358 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
91,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
94,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,19708.0,(606 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
95,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16039.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
96,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(325 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
97,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
98,4 Bedroom House for sale in Sector 23 Gurgaon,all punjabi welfare association,NaN,16999.0,(139-279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 23 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['HUDA Sector 23 Market', 'Palam triangle', 'R...",All punjabi welfare association in sector-23 g...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5..."
99,4 Bedroom House for sale in Sector 72 Gurgaon,tata primanti,NaN,10714.0,(650-790 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 72 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Omaxe City Cen...","Tata primanti in sector-72, gurgaon by tata ho...",NaN,NaN,"['Environment4.5 out of 5', 'Lifestyle4.5 out ..."
100,4 Bedroom House for sale in Sector 112 Gurgaon,experion windchants,NaN,12027.0,(590-687 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 112 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","Experion windchants in sector 112, gurgaon by ...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
101,5 Bedroom House for sale in Sector 63A Gurgaon,aindependentt raj estates,NaN,NaN,(251-704 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 63A Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Paras Trinity ...","Anant raj estates in sector-63a gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
102,3 Bedroom House for sale in Sector 63A Gurgaon,aindependentt raj estates,NaN,NaN,(211 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 63A Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Paras Trinity ...","Anant raj estates in sector-63a gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
105,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,18750.0,(372-441 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
106,3 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,19000.0,(279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
107,5 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,27793.0,(571-711 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
108,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,22006.0,(372-441 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
109,3 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,19000.0,(279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
110,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,NaN,13333.0,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
111,5 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,NaN,22222.0,(293-381 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
112,4 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,NaN,28760.0,(207 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
113,3 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,NaN,16975.0,(301 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
115,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16058.0,(606-754 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
116,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,15700.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
117,4 Bedroom House for sale in Sector 65 Gurgaon,emaar emerald hills,NaN,NaN,(183 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 65 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Emerald Plaza Shopping Mall', 'Southern Peri...","Emaar emerald hills in sector-65 gurgaon, gurg...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
118,4 Bedroom House for sale in Sector-33 Sohna,central park flower valley,NaN,NaN,(344 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector-33 Sohna, Gurgaon, Haryana",NaN,NaN,NaN,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Central park flower valley in sector-33 sohna,...",NaN,NaN,NaN
123,5 Bedroom House for sale in Sector 111 Gurgaon,puri diplomatic greens,NaN,12828.0,(650 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 111 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,NaN,NaN
124,5 Bedroom House for sale in Sector 111 Gurgaon,puri diplomatic greens,NaN,12842.0,(650 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 111 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,NaN,NaN
128,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,NaN,NaN,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
178,4 Bedroom House for sale in Nirvana Country,unitech nirvana birch court,NaN,32407.0,(301 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,5 Bedroom House for sale in Sector 63 Gurgaon,aindependentt raj manor villas,NaN,37037.0,(251 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,4 Bedroom House for sale in Sector 81 Gurgaon,bestech park view aindependentda,NaN,8181.0,(511 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,12 Bedroom House for sale in Sector 56 Gurgaon,independent,NaN,43333.0,(251 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,2 Bedroom House for sale in Laxman Vihar,huda ashok vihar phase,NaN,7777.0,(42 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,4 Bedroom House for sale in Ghamroj,independent,NaN,481.0,(995 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,8 Bedroom House for sale in Palam Vihar Extension,independent,NaN,3452.0,(390 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,1 Bedroom House for sale in Sector 57 Gurgaon,independent,NaN,24444.0,(209 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,3 Bedroom House for sale in Sector 8 Gurgaon,independent,NaN,100000.0,(6 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,5 Bedroom House for sale in Patel Nagar,independent,NaN,13071.0,(142 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,6 Bedroom House for sale in Patel Nagar,patel nager house no 927/5,NaN,11111.0,(142 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,12 Bedroom House for sale in Pratap Nagar,independent,NaN,102941.0,(16 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,12 Bedroom House for sale in South City 1,independent,NaN,29321.0,(301 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,5 Bedroom House for sale in Sector 23 Gurgaon,independent,NaN,21242.0,(171 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,8 Bedroom House for sale in DLF Phase 3,independent,NaN,24912.0,(264 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,7 Bedroom House for sale in DLF Phase 4,dlf city plots phase 4,NaN,255555.0,(33 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,5 Bedroom House for sale in Maruti Kunj,independent,NaN,9259.0,(151 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,5 Bedroom House for sale in Rajiv Chowk,hans enclave,NaN,4333.0,(139 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,3 Bedroom House for sale in Laxman Vihar,huda ashok vihar phase,NaN,11784.0,(84 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,4 Bedroom House for sale in Madanpuri,independent,NaN,13359.0,(70 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,7 Bedroom House for sale in Sector 11 Gurgaon,independent,NaN,197080.0,(13 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,5 Bedroom House for sale in Shivaji Nagar,independent,NaN,13131.0,(184 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,5 Bedroom House for sale in Sector 81 Gurgaon,bestech park view aindependentda,NaN,NaN,(509-543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 81 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Metro Station Kankrola sec 87', 'Sapphire 83...","Bestech park view ananda in sector-81 gurgaon,...",NaN,NaN,"['Environment4.5 out of 5', 'Lifestyle4 out of..."
312,4 Bedroom House for sale in Sector-33 Sohna,central park flower valley,NaN,NaN,(344 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector-33 Sohna, Gurgaon, Haryana",NaN,NaN,NaN,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Central park flower valley in sector-33 sohna,...",NaN,NaN,NaN

In [34]:
df = df[~df['bedRoom'].isnull()]

In [35]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [36]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype('int')

In [37]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [38]:
df['bathroom'].value_counts()

bathroom
4 Bathrooms     228
3 Bathrooms     165
5 Bathrooms     137
2 Bathrooms     114
6 Bathrooms      82
1 Bathroom       65
9 Bathrooms      42
7 Bathrooms      39
8 Bathrooms      28
12 Bathrooms     22
10 Bathrooms     11
16 Bathrooms      8
13 Bathrooms      4
18 Bathrooms      4
11 Bathrooms      4
17 Bathrooms      3
20 Bathrooms      3
14 Bathrooms      2
21 Bathrooms      1
34 Bathrooms      1
36 Bathrooms      1
Name: count, dtype: int64

In [39]:
df['bathroom'].isnull().sum()

np.int64(0)

In [40]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [41]:
df['bathroom'] = pd.to_numeric(
    df['bathroom'].str.split(' ').str.get(0),
    errors='coerce'
)

In [43]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [44]:
df['balcony'].value_counts()

balcony
3+ Balconies    365
2 Balconies     220
3 Balconies     159
No Balcony      115
1 Balcony       105
Name: count, dtype: int64

In [45]:
df['balcony'].isnull().sum()

np.int64(0)

In [46]:
df['balcony'] = pd.to_numeric(
    df['balcony'].str.split(' ').str.get(0),
    errors='coerce'
)

In [48]:
df.head(10)

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,NaN,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2.0,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,NaN,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,NaN,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,NaN,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
5,20 Bedroom House for sale in Sushant Lok Phase 1,independent,4.50,39062.0,(107 sq.m.) Plot Area,Plot area 128(107.02 sq.m.),20,20,NaN,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",4 Floors,East,1 to 5 Year Old,"['Huda city centre metro station', 'New Life C...",Best for investment purpose. 3l rupees monthly...,"['1 Water Purifier', '1 Fridge', '20 Fan', '1 ...","['Water Storage', 'Park', 'Visitor Parking', '...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
6,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,12.00,37037.0,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),5,5,NaN,"Servant Room,Pooja Room,Store Room","Sector 66 Gurgaon, Gurgaon, Haryana",3 Floors,East,0 to 1 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",Available for sale 5bhk independent house in e...,"['4 Wardrobe', '1 Water Purifier', '6 Fan', '1...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment3 out of 5', 'Lifestyle4 out of 5..."
7,16 Bedroom House for sale in DLF Phase 1,luxury dlf city floors,20.00,48889.0,(418 sq.m.) Plot Area,Plot area 500(418.06 sq.m.),16,16,NaN,Servant Room,"DLF Phase 1, Gurgaon, Haryana",4 Floors,NaN,0 to 1 Year Old,"['Sikandarpur metro station', 'Sikanderpur met...",Prime location on dlf phase - 1 builder floor ...,"['16 Wardrobe', '26 Fan', '1 Exhaust Fan', '16...","['High Ceiling Height', 'Park', 'Visitor Parki...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
8,6 Bedroom House for sale in DLF Phase 2,independent,10.85,38150.0,(264 sq.m.) Plot Area,Plot area 316(264.22 sq.m.),6,6,1.0,Store Room,"DLF Phase 2, Gurgaon, Haryana",3 Floors,North-East,1 to 5 Year Old,"['Vodafone belvedere towers metro station', 'D...","6 bhk kothi in dlf phase 2, gurgaon available ...","['4 Wardrobe', '1 Water Purifier', '5 Fan', '1...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
9,3 Bedroom House for sale in Sushant Lok Phase 1,sushant lok 1 builder floors,1.95,10077.0,(180 sq.m.) Plot Area,Plot area 215(179.77 sq.m.),3,4,NaN,Servant Room,"C Block Small Nos, Sushant Lok Phase 1, Gurgao...",4 Floors,West,0 to 1 Year Old,"['Huda city centre metro station', 'Sector 42-...",Brand new builder floor at very reasonable pri...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [49]:
df['balcony'].value_counts()

balcony
2.0    220
3.0    159
1.0    105
Name: count, dtype: int64

In [50]:
df['additionalRoom'].value_counts().shape

(56,)

In [51]:
df['additionalRoom'].isnull().sum()

np.int64(386)

In [52]:
df['additionalRoom'].fillna('not available',inplace=True)

/tmp/ipykernel_283/1615843200.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['additionalRoom'].fillna('not available',inplace=True)

In [53]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [54]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,NaN,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2.0,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,NaN,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,NaN,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,NaN,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [55]:
df['additionalRoom'].value_counts()

additionalRoom
not available                                    386
servant room                                      81
pooja room,study room,servant room,store room     60
others                                            58
pooja room                                        38
pooja room,study room,servant room                33
pooja room,study room,servant room,others         32
store room                                        31
pooja room,servant room                           24
study room                                        19
study room,servant room                           19
servant room,store room                           15
pooja room,study room                             11
pooja room,others                                 11
pooja room,store room                             11
servant room,others                                8
pooja room,store room,study room,servant room      8
servant room,pooja room                            8
pooja room,servant room,store room                 7
servant room,pooja room,store room                 6
store room,servant room                            6
study room,servant room,pooja room,store room      6
study room,pooja room,servant room                 5
pooja room,servant room,others                     5
servant room,study room                            5
servant room,study room,pooja room,store room      5
study room,servant room,store room                 4
store room,pooja room                              4
pooja room,servant room,study room,store room      4
study room,servant room,store room,pooja room      4
servant room,store room,pooja room                 4
pooja room,study room,others                       4
pooja room,study room,store room                   3
study room,others                                  3
study room,servant room,pooja room                 3
study room,pooja room,servant room,store room      3
store room,pooja room,servant room                 2
pooja room,study room,store room,servant room      2
study room,pooja room,store room                   2
store room,pooja room,study room                   2
servant room,study room,pooja room                 2
study room,pooja room,store room,servant room      2
study room,pooja room                              2
study room,servant room,others                     2
store room,pooja room,study room,servant room      2
servant room,study room,store room,pooja room      1
study room,store room                              1
study room,store room,pooja room                   1
store room,pooja room,servant room,study room      1
servant room,store room,study room,pooja room      1
store room,servant room,study room,pooja room      1
pooja room,store room,servant room                 1
servant room,others,pooja room                     1
study room,store room,servant room,pooja room      1
store room,study room,servant room                 1
store room,servant room,pooja room                 1
study room,others,servant room                     1
Name: count, dtype: int64

In [56]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,NaN,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2.0,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,NaN,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,NaN,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,NaN,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [57]:
df['noOfFloor']

0        3 Floors
1        2 Floors
2        5 Floors
3        5 Floors
4        5 Floors
5        4 Floors
6        3 Floors
7        4 Floors
8        3 Floors
9        4 Floors
10       2 Floors
11       3 Floors
12       4 Floors
13       3 Floors
14       3 Floors
15       3 Floors
16       3 Floors
17       3 Floors
18       3 Floors
19       3 Floors
20       3 Floors
21       3 Floors
22       2 Floors
23            NaN
24       4 Floors
25       3 Floors
26       1 Floors
27       3 Floors
28       3 Floors
29       3 Floors
30       2 Floors
31       3 Floors
32       3 Floors
33       1 Floors
34       2 Floors
35       3 Floors
36       4 Floors
37       1 Floors
38       3 Floors
39       3 Floors
40       2 Floors
41       1 Floors
42       4 Floors
43       4 Floors
44       4 Floors
45       4 Floors
46       2 Floors
47       3 Floors
48       3 Floors
49       2 Floors
50       2 Floors
51            NaN
52       3 Floors
53       2 Floors
54       3 Floors
55       2 Floors
56       2 Floors
57       2 Floors
58       3 Floors
59       3 Floors
73       3 Floors
74       3 Floors
77       1 Floors
78       3 Floors
92       4 Floors
93       2 Floors
103      2 Floors
104      2 Floors
114      3 Floors
119      2 Floors
120      1 Floors
121      3 Floors
122      2 Floors
125      2 Floors
126      1 Floors
127      3 Floors
129      3 Floors
130      1 Floors
131      4 Floors
132      2 Floors
133      1 Floors
134      1 Floors
135      3 Floors
136      2 Floors
137      2 Floors
138      2 Floors
139      3 Floors
140      2 Floors
141      3 Floors
142      3 Floors
143      2 Floors
144      3 Floors
145      2 Floors
146      2 Floors
147      3 Floors
148      2 Floors
149      2 Floors
150      2 Floors
151      2 Floors
152      3 Floors
153      2 Floors
154      2 Floors
155      2 Floors
156      1 Floors
157      2 Floors
158      1 Floors
159      2 Floors
160      1 Floors
161      2 Floors
162      2 Floors
163      2 Floors
164      2 Floors
165      3 Floors
166      4 Floors
167      4 Floors
168      2 Floors
169      4 Floors
170      1 Floors
171      2 Floors
172      2 Floors
173      2 Floors
174      4 Floors
175      4 Floors
176      3 Floors
177      4 Floors
200      3 Floors
201      3 Floors
202      2 Floors
203           NaN
204      1 Floors
205      3 Floors
206      1 Floors
207      1 Floors
208      4 Floors
209      2 Floors
210      3 Floors
211      4 Floors
212      2 Floors
213      1 Floors
214      3 Floors
215      3 Floors
216      3 Floors
217      2 Floors
218      1 Floors
219      3 Floors
220     02 Floors
221      3 Floors
222      2 Floors
223      2 Floors
224      2 Floors
225      1 Floors
226      1 Floors
227      1 Floors
228      2 Floors
229      2 Floors
230      2 Floors
231      1 Floors
232      1 Floors
233      1 Floors
234      3 Floors
235      1 Floors
236      1 Floors
237      3 Floors
238      3 Floors
239      1 Floors
240      3 Floors
241     14 Floors
242     21 Floors
243      1 Floors
244      1 Floors
245      2 Floors
246      3 Floors
247      1 Floors
248      1 Floors
249      1 Floors
250      2 Floors
251      0 Floors
252           NaN
253      3 Floors
254      3 Floors
255      3 Floors
256      1 Floors
257      2 Floors
258      3 Floors
259      3 Floors
260      2 Floors
261      1 Floors
262      3 Floors
263      2 Floors
264      3 Floors
265      1 Floors
266      1 Floors
267      1 Floors
268      3 Floors
269      3 Floors
270           NaN
271      3 Floors
272      1 Floors
273      3 Floors
274     12 Floors
275      1 Floors
276      2 Floors
277      2 Floors
278      2 Floors
279      1 Floors
280      3 Floors
281           NaN
282      3 Floors
283      1 Floors
284      3 Floors
285      2 Floors
286      3 Floors
287      2 Floors
288      0 Floors
289      1 Floors
290      1 Floors
291      1 Floors
292      0 Floors
293      3 Floors
294      1 Floors
297      2 Floors
298      2 Floors
299      1 Floors
300      1 Floors
301      1 Floors
302      2 Floors
303     27 Floors
304      4 Floors
305      3 Floors
306      3 Floors
307      2 Floors
309      1 Floors
310      1 Floors
311      1 Floors
314      1 Floors
315      3 Floors
316      3 Floors
317      4 Floors
318      4 Floors
320      4 Floors
321      1 Floors
322      3 Floors
323      2 Floors
324      3 Floors
332      4 Floors
333      2 Floors
334      1 Floors
335      2 Floors
336      1 Floors
337      2 Floors
338      2 Floors
339      4 Floors
340      1 Floors
341      1 Floors
342      2 Floors
343      3 Floors
344      1 Floors
345      2 Floors
346      3 Floors
347     13 Floors
348      1 Floors
349      1 Floors
350      1 Floors
351      1 Floors
352      3 Floors
357      2 Floors
370      4 Floors
374           NaN
375      3 Floors
376      3 Floors
377      3 Floors
378      6 Floors
379      2 Floors
380      4 Floors
381      1 Floors
382      3 Floors
383      1 Floors
384      1 Floors
385      1 Floors
386      1 Floors
387      2 Floors
388      1 Floors
389      3 Floors
390      1 Floors
391      3 Floors
392      1 Floors
393      4 Floors
394      3 Floors
395      1 Floors
396      3 Floors
397           NaN
398      2 Floors
399      2 Floors
400      3 Floors
401      1 Floors
403      2 Floors
404      2 Floors
405      1 Floors
406      1 Floors
407      1 Floors
408      1 Floors
409      1 Floors
410      3 Floors
411      3 Floors
412      1 Floors
413      3 Floors
414      4 Floors
415      4 Floors
416      2 Floors
417           NaN
418      1 Floors
419      1 Floors
420      3 Floors
421      2 Floors
422      4 Floors
423      2 Floors
424      2 Floors
425      1 Floors
426      1 Floors
427      1 Floors
428      3 Floors
429      3 Floors
430      1 Floors
432      4 Floors
433      1 Floors
434      4 Floors
435      2 Floors
436      2 Floors
437      3 Floors
438      6 Floors
439      2 Floors
440      2 Floors
441      3 Floors
442      2 Floors
443      3 Floors
444      3 Floors
445      4 Floors
446      1 Floors
447      1 Floors
448      1 Floors
449      3 Floors
450      2 Floors
451      2 Floors
452      1 Floors
453      1 Floors
454      1 Floors
455      1 Floors
456      1 Floors
457      2 Floors
458      1 Floors
459      1 Floors
460      3 Floors
461      2 Floors
462      2 Floors
463      1 Floors
464      3 Floors
465      3 Floors
466      2 Floors
467      3 Floors
468      1 Floors
469      1 Floors
470      1 Floors
471      2 Floors
472      3 Floors
473      2 Floors
474      4 Floors
475      3 Floors
476      3 Floors
477      1 Floors
478     10 Floors
479      4 Floors
480      4 Floors
481      1 Floors
482      2 Floors
483      3 Floors
484      2 Floors
485      1 Floors
486      2 Floors
487      1 Floors
488      2 Floors
489      5 Floors
490      1 Floors
491      4 Floors
492      3 Floors
493      2 Floors
495      1 Floors
496      1 Floors
497      3 Floors
498      3 Floors
499      2 Floors
500      1 Floors
501     20 Floors
502      3 Floors
503      3 Floors
504      4 Floors
505      3 Floors
506      3 Floors
507      3 Floors
508      2 Floors
509      2 Floors
510      1 Floors
511      2 Floors
512      3 Floors
513      3 Floors
514      2 Floors
515      2 Floors
516      4 Floors
517      2 Floors
518      3 Floors
519      3 Floors
520      1 Floors
521      4 Floors
522      1 Floors
523      1 Floors
524      2 Floors
525      3 Floors
526      1 Floors
527      1 Floors
528      1 Floors
529      1 Floors
530      1 Floors
531      2 Floors
532      1 Floors
533      3 Floors
534      1 Floors
535      3 Floors
536      3 Floors
537      1 Floors
538      1 Floors
539      2 Floors
540      4 Floors
541      1 Floors
542      1 Floors
543      1 Floors
544      4 Floors
545      2 Floors
546      3 Floors
547      4 Floors
548      2 Floors
549      2 Floors
550      1 Floors
551      2 Floors
552      1 Floors
553      1 Floors
554      3 Floors
555      4 Floors
556      3 Floors
557      4 Floors
558      1 Floors
559      4 Floors
560           NaN
561      2 Floors
562      2 Floors
563      0 Floors
564      2 Floors
565      3 Floors
566      2 Floors
567      3 Floors
568      3 Floors
570      3 Floors
571      3 Floors
572      1 Floors
573      1 Floors
574      3 Floors
575     14 Floors
576      1 Floors
577      3 Floors
578      3 Floors
579      3 Floors
580      4 Floors
581     14 Floors
582     12 Floors
583      1 Floors
584      4 Floors
585      3 Floors
586      4 Floors
587      1 Floors
588      2 Floors
589      3 Floors
590      1 Floors
591      1 Floors
592      2 Floors
593      4 Floors
594           NaN
596      2 Floors
597      3 Floors
598      2 Floors
599      3 Floors
600      2 Floors
601      1 Floors
602      1 Floors
603      1 Floors
604      1 Floors
605      3 Floors
606      1 Floors
607      1 Floors
608      3 Floors
609      1 Floors
610      2 Floors
611      1 Floors
612      2 Floors
613      3 Floors
614      3 Floors
615      3 Floors
616      3 Floors
617      1 Floors
618      1 Floors
619      2 Floors
620      1 Floors
621      3 Floors
622     11 Floors
623      0 Floors
624      3 Floors
625      4 Floors
626      3 Floors
627      3 Floors
628      3 Floors
629      4 Floors
630      1 Floors
631      4 Floors
632      3 Floors
633      1 Floors
634      1 Floors
635      5 Floors
636      4 Floors
637     11 Floors
638      1 Floors
639      2 Floors
640      1 Floors
641     41 Floors
642      1 Floors
643      1 Floors
644      3 Floors
645      1 Floors
646      3 Floors
647      4 Floors
648      1 Floors
649      5 Floors
650      2 Floors
651      2 Floors
652      3 Floors
653      3 Floors
654      2 Floors
655      2 Floors
656      4 Floors
657      3 Floors
658      5 Floors
659      3 Floors
660      1 Floors
661      1 Floors
662      3 Floors
663      2 Floors
664      3 Floors
665      1 Floors
666           NaN
667      3 Floors
669      1 Floors
670      2 Floors
671      3 Floors
672      4 Floors
673      4 Floors
674      4 Floors
675      2 Floors
676      2 Floors
677      3 Floors
678      1 Floors
679      2 Floors
680      2 Floors
681      2 Floors
682      2 Floors
683      1 Floors
684      3 Floors
685      4 Floors
686      2 Floors
687      1 Floors
688      2 Floors
689      1 Floors
690      1 Floors
691      3 Floors
692      4 Floors
693      3 Floors
694      4 Floors
695      4 Floors
696      3 Floors
697      3 Floors
698      3 Floors
699      3 Floors
700      3 Floors
701      3 Floors
702      1 Floors
703      3 Floors
704      3 Floors
705      2 Floors
706      3 Floors
707      3 Floors
708      4 Floors
709           NaN
710      3 Floors
711      2 Floors
712      2 Floors
713      4 Floors
714      1 Floors
715      3 Floors
716      4 Floors
717      2 Floors
718      3 Floors
719      3 Floors
720      3 Floors
721      2 Floors
722      3 Floors
723      2 Floors
724      2 Floors
725      4 Floors
726     10 Floors
727      3 Floors
728      4 Floors
729      2 Floors
730      4 Floors
731      2 Floors
732      3 Floors
733      3 Floors
734      3 Floors
735      2 Floors
736      1 Floors
737      4 Floors
738      2 Floors
739      4 Floors
740      2 Floors
741      3 Floors
742      4 Floors
743      2 Floors
744      2 Floors
745      2 Floors
746      3 Floors
747      4 Floors
748      5 Floors
749      4 Floors
750      4 Floors
751      3 Floors
752      3 Floors
753      3 Floors
754      4 Floors
755      2 Floors
756      2 Floors
757      2 Floors
758      4 Floors
759      4 Floors
760     51 Floors
761      3 Floors
762      3 Floors
763      2 Floors
764      3 Floors
765      2 Floors
766      2 Floors
767      2 Floors
768      3 Floors
769      1 Floors
770      3 Floors
771      2 Floors
772      2 Floors
773      4 Floors
774      3 Floors
775      4 Floors
776      3 Floors
777      2 Floors
778      4 Floors
779      2 Floors
780      3 Floors
781      1 Floors
782      2 Floors
783      1 Floors
784      3 Floors
785      3 Floors
786      4 Floors
787      3 Floors
788      3 Floors
789      2 Floors
790      3 Floors
791      2 Floors
792      4 Floors
793      2 Floors
794      2 Floors
795      3 Floors
796      4 Floors
797      2 Floors
798      2 Floors
799      4 Floors
800      3 Floors
801      2 Floors
802      3 Floors
803      2 Floors
804      2 Floors
805      4 Floors
806      2 Floors
807      3 Floors
808      3 Floors
809      2 Floors
810      2 Floors
811      2 Floors
812      2 Floors
813      3 Floors
814      4 Floors
815      2 Floors
816      2 Floors
817      2 Floors
818      4 Floors
819      3 Floors
832           NaN
833      4 Floors
834      4 Floors
835      3 Floors
836      3 Floors
837      4 Floors
838      3 Floors
839      3 Floors
840      2 Floors
841      4 Floors
842      3 Floors
843      3 Floors
844      4 Floors
845      4 Floors
846      3 Floors
847      4 Floors
848      4 Floors
849      3 Floors
850      4 Floors
851      1 Floors
852      3 Floors
853      2 Floors
854      4 Floors
855           NaN
856      2 Floors
857      2 Floors
858      2 Floors
859      4 Floors
860      3 Floors
861      4 Floors
862           NaN
863      3 Floors
864      4 Floors
865           NaN
866      2 Floors
867      2 Floors
868      2 Floors
869      3 Floors
870      2 Floors
872      3 Floors
873      4 Floors
874      4 Floors
875      3 Floors
876      3 Floors
877      3 Floors
878      3 Floors
879      2 Floors
880      2 Floors
881      2 Floors
882      2 Floors
883     16 Floors
884      4 Floors
885      2 Floors
886      3 Floors
887      1 Floors
888      2 Floors
889      2 Floors
890      3 Floors
891      3 Floors
892      3 Floors
893      1 Floors
895      1 Floors
896      1 Floors
897      2 Floors
898      3 Floors
899      3 Floors
900      4 Floors
901      3 Floors
902      2 Floors
903      4 Floors
904      2 Floors
905      3 Floors
906      2 Floors
907      2 Floors
908      4 Floors
909      4 Floors
910      2 Floors
911      3 Floors
912      2 Floors
913      4 Floors
914      4 Floors
915      4 Floors
916      4 Floors
917      2 Floors
918      2 Floors
919      2 Floors
920      2 Floors
921      3 Floors
922      2 Floors
923      3 Floors
924      2 Floors
925      2 Floors
926      3 Floors
927      3 Floors
928      4 Floors
929      4 Floors
930      2 Floors
931      3 Floors
932      2 Floors
933      3 Floors
934      4 Floors
935      3 Floors
936      3 Floors
937      1 Floors
938      2 Floors
939      3 Floors
940      3 Floors
941      2 Floors
942      3 Floors
943      2 Floors
944      3 Floors
945      4 Floors
946      2 Floors
947      3 Floors
948      4 Floors
949      3 Floors
950      3 Floors
951      3 Floors
952      4 Floors
953      3 Floors
954      2 Floors
955      2 Floors
956      2 Floors
957      3 Floors
958      3 Floors
959      3 Floors
960      1 Floors
961      3 Floors
962      2 Floors
963      4 Floors
964      4 Floors
965      3 Floors
966      3 Floors
967      2 Floors
968      4 Floors
969      3 Floors
970      2 Floors
971      2 Floors
972      3 Floors
973      2 Floors
974      2 Floors
975      2 Floors
976      2 Floors
977      2 Floors
978      2 Floors
979      3 Floors
980      6 Floors
981      1 Floors
982      2 Floors
983      2 Floors
984      4 Floors
985      3 Floors
986      3 Floors
987      2 Floors
988      2 Floors
989      4 Floors
990      3 Floors
991      2 Floors
992      2 Floors
993      2 Floors
994      2 Floors
995      2 Floors
996      3 Floors
997      4 Floors
998      4 Floors
999      3 Floors
1000     3 Floors
1001     3 Floors
1002     2 Floors
1003          NaN
1004     4 Floors
1005     3 Floors
1006     2 Floors
1007     2 Floors
1008     2 Floors
1009     2 Floors
1010     2 Floors
1011     2 Floors
1012     2 Floors
1013     2 Floors
1014     2 Floors
1015     3 Floors
1016          NaN
1017     3 Floors
1018     2 Floors
1019     1 Floors
1020     3 Floors
1021     2 Floors
1022     3 Floors
1023     1 Floors
1024     2 Floors
1025     2 Floors
1026     2 Floors
1027     2 Floors
1028     3 Floors
1029     2 Floors
1030     3 Floors
1031     3 Floors
1032     2 Floors
1033     3 Floors
1034    33 Floors
1035     3 Floors
1036     2 Floors
1037     3 Floors
1038     3 Floors
1039     2 Floors
1040     3 Floors
1041     2 Floors
1042     2 Floors
1043     2 Floors
1044     2 Floors
1045     2 Floors
1046     1 Floors
1047     3 Floors
1048     3 Floors
1049     3 Floors
1050     4 Floors
1051     4 Floors
1052     0 Floors
1053     4 Floors
1054     4 Floors
1055     2 Floors
1056     2 Floors
1057     3 Floors
1058     3 Floors
1059     2 Floors
1060     4 Floors
1061     4 Floors
1062     3 Floors
1063     3 Floors
1064     3 Floors
1065     2 Floors
1066     4 Floors
1067     3 Floors
1068     4 Floors
1069     5 Floors
1070     3 Floors
1071     2 Floors
1072     3 Floors
1073     2 Floors
1074     3 Floors
1075     2 Floors
1076     3 Floors
1077     3 Floors
1078     3 Floors
1079     2 Floors
1080     3 Floors
1081     3 Floors
1082     3 Floors
1083     2 Floors
1084     2 Floors
1085     2 Floors
1086     2 Floors
1087     2 Floors
1088     2 Floors
1089     2 Floors
1090     2 Floors
Name: noOfFloor, dtype: object

In [59]:
df['noOfFloor'].isnull().sum()

np.int64(19)

In [60]:
df[df['noOfFloor'].isnull()]

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
23,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,8.50,26235.0,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),4,4,2.0,"pooja room,servant room,store room","Sector 48 Gurgaon, Gurgaon, Haryana",NaN,East,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Three side open villa in tatvam villa sector-4...,"['1 Chimney', '1 Modular Kitchen', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
51,8 Bedroom House for sale in Palam Vihar,independent,5.60,17284.0,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),8,6,NaN,"pooja room,study room,servant room,store room","Palam Vihar, Gurgaon, Haryana",NaN,South-West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",360 sq. Yards plot area near by global foyer m...,"['1 Fan', '1 Dining Table', '1 Light', '1 Modu...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
203,3 Bedroom House for sale in DLF Phase 3,independent,1.45,26852.0,(50 sq.m.) Plot Area,Plot area 60(50.17 sq.m.),3,3,1.0,not available,"DLF Phase 3, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...",Interested to sell independent house/villa.Pla...,NaN,['Private Garden / Terrace'],"['Environment4 out of 5', 'Lifestyle5 out of 5..."
252,3 Bedroom House for sale in Ashok Vihar,independent,1.50,10288.0,(135 sq.m.) Plot Area,Plot area 162(135.45 sq.m.)Built Up area: 210 ...,3,3,NaN,not available,"800 Lane 8 Ashok Vihar Part 1, Ashok Vihar, Gu...",NaN,NaN,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Ground floor and partial first floor built up,[],NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
270,2 Bedroom House for sale in Laxman Vihar Phase 2,independent,4.12,8889.0,(431 sq.m.) Plot Area,Plot area 515(430.61 sq.m.),2,1,NaN,not available,"Laxman Vihar Phase 2, Gurgaon, Haryana",NaN,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Shre...","Property next to dhanwapur underpass, which is...",[],NaN,NaN
281,3 Bedroom House for sale in New Palam Vihar Ph...,independent,2.50,5472.0,(372 sq.m.) Plot Area,Plot area 4000(371.61 sq.m.),3,2,1.0,not available,"B-245, New Palam Vihar Phase 2, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",100 mtr from dwarka express way. On 40ft road,NaN,['Park'],NaN
374,4 Bedroom House for sale in Laxman Vihar,independent,0.65,11111.0,(54 sq.m.) Plot Area,Plot area 65(54.35 sq.m.),4,2,2.0,not available,"Laxman Vihar, Gurgaon, Haryana",NaN,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Well maintained two storeyed independent house...,"['1 Wardrobe', '1 Exhaust Fan', '10 Light', '1...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
397,1 Bedroom House for sale in Sushant Lok Phase 1,ansal sushant lok plots,3.30,26570.0,(115 sq.m.) Plot Area,Plot area 138(115.39 sq.m.),1,1,NaN,not available,"Sushant Lok Phase 1, Gurgaon, Haryana",NaN,NaN,By 2027,"['Iffco chowk metro station', 'Huda city centr...","Close proximity to gold souk , huda city centr...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
417,2 Bedroom House for sale in Bhawani Enclave,independent,1.10,73333.0,(14 sq.m.) Plot Area,Plot area 150(13.94 sq.m.),2,2,1.0,others,"Bhawani Enclave, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['State bank ATM', 'Shri Multispeciality Hospi...","2 side open, 1 drawing room, 1 shop, 1 small r...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,NaN
560,2 Bedroom House for sale in Jacobpura,jacob pura,0.35,9722.0,(33 sq.m.) Built-up Area,Built Up area: 360 (33.45 sq.m.),2,1,NaN,not available,"15/3, Jacobpura, Jacobpura, Gurgaon, Haryana",NaN,NaN,10+ Year Old,NaN,Independece house for sale in jacobpura near k...,[],NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
594,6 Bedroom House for sale in DLF Phase 2,independent,13.00,45710.0,(264 sq.m.) Plot Area,Plot area 316(264.22 sq.m.),6,8,NaN,"pooja room,servant room,study room,store room","DLF Phase 2, Gurgaon, Haryana",NaN,NaN,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Esic...",An impeccable opportunity is here for those wh...,"['1 Water Purifier', '1 Fridge', '1 Sofa', '1 ...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
666,3 Bedroom House for sale in New Colony,independent,6.50,15046.0,(401 sq.m.) Plot Area,Plot area 480(401.34 sq.m.),3,2,NaN,not available,"New Colony, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Geeta Nursing Home Gurgaon', 'Chiranjiv Hosp...",Old construction house in new colony gurgaon.,[],['Private Garden / Terrace'],"['Environment4 out of 5', 'Lifestyle4 out of 5..."
709,12 Bedroom House for sale in Sector 46 Gurgaon,independent,6.81,36911.0,(171 sq.m.) Plot Area,Plot area 205(171.41 sq.m.),12,14,NaN,"servant room,others","Sector 46 Gurgaon, Gurgaon, Haryana",NaN,East,0 to 1 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...",204 sqyds newly floor wise building with basem...,"['14 Wardrobe', '15 Fan', '1 Exhaust Fan', '13...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
832,4 Bedroom House for sale in Sector 86 Gurgaon,dlf new town heights,2.47,7718.0,(297 sq.m.) Plot Area,Plot area 3200(297.29 sq.m.)Built Up area: 280...,4,4,NaN,"pooja room,servant room","Sector 86 Gurgaon, Gurgaon, Haryana",NaN,West,5 to 10 Year Old,"['City Square', 'Vatika Town Square', 'Bharat ...",This is beautiful 4 bhk villa in dlf new town ...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '2 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
855,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,8.50,26235.0,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),4,4,1.0,not available,"4 Bed And 4 Bathroom, Sector 48 Gurgaon, Gurga...",NaN,NaN,1 to 5 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",360 sq yard 4 bhk residential villa for sale i...,"['4 Bed', '4 Fan', '1 Exhaust Fan', '4 Light',...","['Maintenance Staff', 'Water Storage', 'Separa...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
862,4 Bedroom House for sale in Sushant Lok Phase 1,ansal sushant lok,10.50,27911.0,(350 sq.m.) Plot Area,Plot area 418(349.5 sq.m.),4,4,2.0,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",NaN,North-East,10+ Year Old,"['Huda city centre metro station', 'New Life C...",Ansal villa for sale 418 sqyd in d block gated...,"['6 Fan', '6 Light', 'No AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
865,4 Bedroom House for sale in Sector 26 Gurgaon,independent,4.60,12198.0,(350 sq.m.) Plot Area,Plot area 419(350.34 sq.m.),4,4,NaN,not available,"F-5/10, Sector 26 Gurgaon, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...",On the lookout for a spacious house in gurgaon...,[],"['Maintenance Staff', 'Park', 'Visitor Parking...",NaN
1003,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,9.00,21251.0,(521 sq.m.) Plot Area,Plot area 5605(520.72 sq.m.)Built Up area: 520...,4,4,NaN,"pooja room,servant room,store room","Sector 66 Gurgaon, Gurgaon, Haryana",NaN,South-West,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",A lifestyle designed to satiate all your sense...,"['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment3 out of 5', 'Safety4 out of 5', ..."
1016,12 Bedroom House for sale in Uppals Southend,uppal southend,6.75,290948.0,(22 sq.m.) Plot Area,Plot area 232(21.55 sq.m.),12,12,NaN,"pooja room,study room,servant room,others","Uppals Southend, Gurgaon, Haryana",NaN,West,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Address... Uppal southend sector 49 s block si...,"['22 Wardrobe', '24 Fan', '1 Exhaust Fan', '33...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."

In [61]:
df['noOfFloor'] = df['noOfFloor'].str.split(' ').str.get(0)

In [63]:
df.rename(columns={'noOfFloor':'floorNum'},inplace=True)

In [64]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,NaN,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2.0,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,NaN,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,NaN,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,NaN,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [65]:
df['facing'].value_counts()

facing
East          178
North-East    158
North         109
West           75
North-West     44
South-East     39
South          34
South-West     24
Name: count, dtype: int64

In [66]:
df['facing'].isnull().sum()

np.int64(303)

In [67]:
df['facing'].fillna('NA',inplace=True)

/tmp/ipykernel_283/3692945726.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('NA',inplace=True)

In [68]:
df['facing'].value_counts()

facing
NA            303
East          178
North-East    158
North         109
West           75
North-West     44
South-East     39
South          34
South-West     24
Name: count, dtype: int64

In [69]:
df['area'] = round((df['price']*10000000)/df['price_per_sqft'])

In [70]:
df.insert(loc=1,column='property_type',value='house')

In [71]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,NaN,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,independent,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2.0,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NA,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,independent,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,NaN,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,independent,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,NaN,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,independent,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,NaN,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 964 entries, 0 to 1090
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    964 non-null    object
 1   property_type    964 non-null    object
 2   society          964 non-null    object
 3   price            945 non-null    float64
 4   price_per_sqft   945 non-null    float64
 5   area             945 non-null    float64
 6   areaWithType     964 non-null    object
 7   bedRoom          964 non-null    int64
 8   bathroom         964 non-null    int64
 9   balcony          484 non-null    float64
 10  additionalRoom   964 non-null    object
 11  address          959 non-null    object
 12  floorNum         945 non-null    object
 13  facing           964 non-null    object
 14  agePossession    964 non-null    object
 15  nearbyLocations  848 non-null    object
 16  description      964 non-null    object
 17  furnishDetails   729 non-null    object
 18  features         662 non-null    object
 19  rating           843 non-null    object
dtypes: float64(4), int64(2), object(14)
memory usage: 158.2+ KB

In [73]:
df.shape

(964, 20)

In [74]:
df.to_csv('house_cleaned.csv',index=False)