<a href="https://colab.research.google.com/github/anshuman4515/Capstone-project/blob/main/data_preprocessing_level2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

In [5]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [6]:
df=pd.read_csv('/content/gurgaon_properties')

In [7]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 Bedroom House for sale in Sohna,house,signature global park,0.85,7589.0,1120.0,Built Up area: 1120 (104.05 sq.m.),3.0,2.0,2.0,not available,"Signature Global Park 4 Phase Ii, Sector 36 So...",1.0,NaN,Jun 2024,"['Sector 55-56 metro', 'Global city centre', '...",Property is park facing with plc. Corner and p...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1,3 BHK Flat in Sector 102 Gurgaon,flat,Conscient Heritage Max4.3 ★,1.75,9062.0,1931.0,Super Built up area 1931(179.4 sq.m.),3.0,4.0,NaN,servant room,"Abcd, Sector 102 Gurgaon, Gurgaon, Haryana",16.0,South,1 to 5 Year Old,"['Huda Metro Station', 'Ocus Medley Mall', 'Th...",National standard football field with flood li...,"['1 Stove', '5 AC', '1 Modular Kitchen', '1 Ch...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
2,2 BHK Flat in Sector 108 Gurgaon,flat,Raheja Vedaanta3.6 ★,0.70,4666.0,1500.0,Built Up area: 1468 (136.38 sq.m.)Carpet area:...,2.0,2.0,1.0,not available,"Sector 108, Sector 108 Gurgaon, Gurgaon, Haryana",10.0,West,5 to 10 Year Old,NaN,"2 bath, semi furnished, 10th floor (Of 16), ov...",NaN,NaN,"['Green Area4 out of 5', 'Amenities4 out of 5'..."
3,4 BHK Flat in Sector 84 Gurgaon,flat,Alpha Corp GurgaonOne 844.0 ★,2.24,6523.0,3434.0,Super Built up area 3434(319.03 sq.m.)Carpet a...,4.0,4.0,3.0,servant room,"Sector 84 Gurgaon, Gurgaon, Haryana",12.0,West,1 to 5 Year Old,"['Delhi Public School', 'Raheja Market', 'Sapp...",Check out this 4 bhk apartment for sale in alp...,NaN,"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction5 out of..."
4,4 BHK Flat in Sector 110 Gurgaon,flat,Indiabulls Enigma,3.40,10000.0,3400.0,Super Built up area 3400(315.87 sq.m.)Built Up...,4.0,5.0,3.0,servant room,"Sector 110 Gurgaon, Gurgaon, Haryana",10.0,South-West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...",Spacious 4 bhk flat in indiabulls enigma at se...,"['6 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Water purifier', 'Security / Fire Alarm', 'P...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [8]:
df.shape

(3962, 20)

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3962 entries, 0 to 3961
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3962 non-null   object
 1   property_type    3962 non-null   object
 2   society          3961 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3962 non-null   object
 7   bedRoom          3961 non-null   float64
 8   bathroom         3961 non-null   float64
 9   balcony          2522 non-null   float64
 10  additionalRoom   3962 non-null   object
 11  address          3951 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2785 non-null   object
 14  agePossession    3961 non-null   object
 15  nearbyLocations  3755 non-null   object
 16  description      3962 non-null   object
 17  furnishDetails   2930 non-null   object
 18  features         3253 non-null   object
 19  rating           3512 non-null   object
dtypes: float64(7), object(13)
memory usage: 619.2+ KB

In [13]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                21
price_per_sqft       21
area                 21
areaWithType          0
bedRoom               1
bathroom              1
balcony            1440
additionalRoom        0
address              11
floorNum             22
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [14]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [15]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 Bedroom House for sale in Sohna,house,signature global park,Sohna,0.85,7589.0,1120.0,Built Up area: 1120 (104.05 sq.m.),3.0,2.0,2.0,not available,"Signature Global Park 4 Phase Ii, Sector 36 So...",1.0,NaN,Jun 2024,"['Sector 55-56 metro', 'Global city centre', '...",Property is park facing with plc. Corner and p...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1,3 BHK Flat in Sector 102 Gurgaon,flat,Conscient Heritage Max4.3 ★,Sector 102,1.75,9062.0,1931.0,Super Built up area 1931(179.4 sq.m.),3.0,4.0,NaN,servant room,"Abcd, Sector 102 Gurgaon, Gurgaon, Haryana",16.0,South,1 to 5 Year Old,"['Huda Metro Station', 'Ocus Medley Mall', 'Th...",National standard football field with flood li...,"['1 Stove', '5 AC', '1 Modular Kitchen', '1 Ch...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
2,2 BHK Flat in Sector 108 Gurgaon,flat,Raheja Vedaanta3.6 ★,Sector 108,0.70,4666.0,1500.0,Built Up area: 1468 (136.38 sq.m.)Carpet area:...,2.0,2.0,1.0,not available,"Sector 108, Sector 108 Gurgaon, Gurgaon, Haryana",10.0,West,5 to 10 Year Old,NaN,"2 bath, semi furnished, 10th floor (Of 16), ov...",NaN,NaN,"['Green Area4 out of 5', 'Amenities4 out of 5'..."
3,4 BHK Flat in Sector 84 Gurgaon,flat,Alpha Corp GurgaonOne 844.0 ★,Sector 84,2.24,6523.0,3434.0,Super Built up area 3434(319.03 sq.m.)Carpet a...,4.0,4.0,3.0,servant room,"Sector 84 Gurgaon, Gurgaon, Haryana",12.0,West,1 to 5 Year Old,"['Delhi Public School', 'Raheja Market', 'Sapp...",Check out this 4 bhk apartment for sale in alp...,NaN,"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction5 out of..."
4,4 BHK Flat in Sector 110 Gurgaon,flat,Indiabulls Enigma,Sector 110,3.40,10000.0,3400.0,Super Built up area 3400(315.87 sq.m.)Built Up...,4.0,5.0,3.0,servant room,"Sector 110 Gurgaon, Gurgaon, Haryana",10.0,South-West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...",Spacious 4 bhk flat in indiabulls enigma at se...,"['6 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Water purifier', 'Security / Fire Alarm', 'P...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [16]:
df['sector'] = df['sector'].str.lower()

In [17]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 Bedroom House for sale in Sohna,house,signature global park,sohna,0.85,7589.0,1120.0,Built Up area: 1120 (104.05 sq.m.),3.0,2.0,2.0,not available,"Signature Global Park 4 Phase Ii, Sector 36 So...",1.0,NaN,Jun 2024,"['Sector 55-56 metro', 'Global city centre', '...",Property is park facing with plc. Corner and p...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1,3 BHK Flat in Sector 102 Gurgaon,flat,Conscient Heritage Max4.3 ★,sector 102,1.75,9062.0,1931.0,Super Built up area 1931(179.4 sq.m.),3.0,4.0,NaN,servant room,"Abcd, Sector 102 Gurgaon, Gurgaon, Haryana",16.0,South,1 to 5 Year Old,"['Huda Metro Station', 'Ocus Medley Mall', 'Th...",National standard football field with flood li...,"['1 Stove', '5 AC', '1 Modular Kitchen', '1 Ch...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
2,2 BHK Flat in Sector 108 Gurgaon,flat,Raheja Vedaanta3.6 ★,sector 108,0.70,4666.0,1500.0,Built Up area: 1468 (136.38 sq.m.)Carpet area:...,2.0,2.0,1.0,not available,"Sector 108, Sector 108 Gurgaon, Gurgaon, Haryana",10.0,West,5 to 10 Year Old,NaN,"2 bath, semi furnished, 10th floor (Of 16), ov...",NaN,NaN,"['Green Area4 out of 5', 'Amenities4 out of 5'..."
3,4 BHK Flat in Sector 84 Gurgaon,flat,Alpha Corp GurgaonOne 844.0 ★,sector 84,2.24,6523.0,3434.0,Super Built up area 3434(319.03 sq.m.)Carpet a...,4.0,4.0,3.0,servant room,"Sector 84 Gurgaon, Gurgaon, Haryana",12.0,West,1 to 5 Year Old,"['Delhi Public School', 'Raheja Market', 'Sapp...",Check out this 4 bhk apartment for sale in alp...,NaN,"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction5 out of..."
4,4 BHK Flat in Sector 110 Gurgaon,flat,Indiabulls Enigma,sector 110,3.40,10000.0,3400.0,Super Built up area 3400(315.87 sq.m.)Built Up...,4.0,5.0,3.0,servant room,"Sector 110 Gurgaon, Gurgaon, Haryana",10.0,South-West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...",Spacious 4 bhk flat in indiabulls enigma at se...,"['6 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Water purifier', 'Security / Fire Alarm', 'P...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [18]:
df['sector'] = df['sector'].str.lower()

In [19]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [20]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [21]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [22]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [23]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [24]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [25]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [26]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [27]:
a

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 81                      90
sector 65                      90
sector 90                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 56                      57
sector 95                      57
sector 48                      56
sector 89                      56
sector 2                       55
sector 70a                     54
sector 43                      53
sector 70                      53
sector 37c                     53
sector-33 sohna road           51
sector 84                      51
sector 26                      50
sector 67                      48
sector 49                      48
sector 66                      46
sector 103                     45
sector 25                      43
sector 113                     43
sector 82                      42
sector 61                      42
sector 28                      42
sector 106                     38
sector 4                       36
sector 7                       33
sector 99a                     32
sector 54                      31
sector 68                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 12                      25
sector 112                     24
sector 24                      24
sector 57                      24
sector 88a                     23
sector 33                      23
sector 105                     23
sector 67a                     22
sector 111                     22
sector 11                      21
sector 22                      20
sector 82a                     20
sector 3                       20
sector 47                      19
sector 78                      19
sector 63a                     18
sector 74                      18
gwal pahari                    18
sector 62                      17
sector 91                      17
sector 110                     16
sector 99                      16
sector 60                      15
sector 63                      15
sector 14                      15
sector 53                      14
sector 1 manesar               14
sector 52                      14
sector 76                      14
sector 9                       13
sector 4 phase 2               13
sector 36a                     13
sector 46                      13
sector 38                      12
sohna road road                12
sector 93                      12
sector 31                      12
sector 39                      12
sector 9a                      11
sector 3 phase 3 extension     11
sector 41                      11
sector 13                      10
sector 1a manesar              10
sector 55                       9
sector 3 phase 2                9
manesar                         9
sector 95a                      9
sector 17                       8
sector 8                        8
mehrauli  road                  8
dwarka expressway               8
sector 10a                      8
sector 2 extension              8
sector 6                        8
sector 89 a                     8
c block sector 43               8
sector 59                       8
sector 40                       8
sector 51                       7
sector 58                       7
sector 36 sohna road            7
sector 1                        6
sector 5                        6
jyoti park                      6
sector 21                       6
sector 80                       5
sector 30                       5
sushant lok phase 2             5
subhash nagar                   5
dayanand colony                 5
greenwood city                  5
chakkarpur                      5
sector 23a                      5
ansal plaza                     5
new sector 2                    5
new                             4
sector 3a                       4
sector 36                       4
sector 45                       4
sector 12a                      4
sector 88b                      3
sector 110 a                    3
sector 15                       3
sector 27                       3
patel nagar                     3
sector 17b                      3
sector 23                       3
b block sector 43               3
sector 73                       3
sector 17a                      3
a block sector 43               3
maruti kunj                     3
Name: count, dtype: int64

In [28]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 65                      90
sector 81                      90
sector 90                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 56                      57
sector 95                      57
sector 48                      56
sector 89                      56
sector 2                       55
sector 70a                     54
sector 43                      53
sector 37c                     53
sector 70                      53
sector 84                      51
sector-33 sohna road           51
sector 26                      50
sector 49                      48
sector 67                      48
sector 66                      46
sector 103                     45
sector 25                      43
sector 113                     43
sector 61                      42
sector 82                      42
sector 28                      42
sector 106                     38
sector 4                       36
sector 7                       33
sector 99a                     32
sector 54                      31
sector 68                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 12                      25
sector 112                     24
sector 24                      24
sector 57                      24
sector 105                     23
sector 88a                     23
sector 33                      23
sector 111                     22
sector 67a                     22
sector 11                      21
sector 82a                     20
sector 3                       20
sector 22                      20
sector 78                      19
sector 47                      19
sector 74                      18
sector 63a                     18
gwal pahari                    18
sector 91                      17
sector 62                      17
sector 99                      16
sector 110                     16
sector 63                      15
sector 60                      15
sector 14                      15
sector 76                      14
sector 1 manesar               14
sector 52                      14
sector 53                      14
sector 4 phase 2               13
sector 9                       13
sector 46                      13
sector 36a                     13
sector 39                      12
sector 93                      12
sector 38                      12
sohna road road                12
sector 31                      12
sector 9a                      11
sector 3 phase 3 extension     11
sector 41                      11
sector 1a manesar              10
sector 13                      10
sector 3 phase 2                9
manesar                         9
sector 95a                      9
sector 55                       9
sector 2 extension              8
sector 59                       8
mehrauli  road                  8
sector 17                       8
sector 89 a                     8
sector 40                       8
sector 10a                      8
sector 6                        8
sector 8                        8
dwarka expressway               8
c block sector 43               8
sector 36 sohna road            7
sector 51                       7
sector 58                       7
sector 1                        6
sector 21                       6
sector 5                        6
jyoti park                      6
dayanand colony                 5
greenwood city                  5
subhash nagar                   5
sector 23a                      5
sushant lok phase 2             5
chakkarpur                      5
new sector 2                    5
ansal plaza                     5
sector 30                       5
sector 80                       5
sector 3a                       4
sector 12a                      4
sector 36                       4
sector 45                       4
new                             4
b block sector 43               3
sector 15                       3
sector 88b                      3
sector 110 a                    3
maruti kunj                     3
sector 73                       3
a block sector 43               3
sector 27                       3
sector 23                       3
patel nagar                     3
sector 17a                      3
sector 17b                      3
Name: count, dtype: int64

In [29]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [30]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [31]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
856,2 BHK Flat in New Gurgaon,flat,Green Court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2.0,2.0,1.0,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
2530,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2.0,2.0,2.0,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
3095,4 BHK Flat in New Gurgaon,flat,Sare Homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4.0,4.0,3.0,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
3725,4 BHK Flat in New Gurgaon,flat,Dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4.0,4.0,2.0,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN

In [32]:
df.loc[955,'sector'] = 'sector 37'
df.loc[2800,'sector'] = 'sector 92'
df.loc[2838,'sector'] = 'sector 90'
df.loc[2857,'sector'] = 'sector 76'

In [33]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1447,2 BHK Flat in New Palam Vihar,flat,Ompee K S Residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2.0,2.0,2.0,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
1922,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3.0,2.0,2.0,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2137,2 BHK Flat in New Palam Vihar,flat,My Home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2.0,2.0,1.0,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
2525,2 BHK Flat in New Palam Vihar,flat,My Home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2.0,1.0,1.0,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
3535,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2.0,2.0,2.0,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [35]:
df.loc[[311,1072,1486,3040,3875],'sector'] = 'sector 110'

In [36]:
df.shape

(3803, 21)

In [37]:
df.duplicated().sum()

np.int64(0)

In [38]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 Bedroom House for sale in Sohna,house,signature global park,sohna road,0.85,7589.0,1120.0,Built Up area: 1120 (104.05 sq.m.),3.0,2.0,2.0,not available,"Signature Global Park 4 Phase Ii, Sector 36 So...",1.0,NaN,Jun 2024,"['Sector 55-56 metro', 'Global city centre', '...",Property is park facing with plc. Corner and p...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1,3 BHK Flat in Sector 102 Gurgaon,flat,Conscient Heritage Max4.3 ★,sector 102,1.75,9062.0,1931.0,Super Built up area 1931(179.4 sq.m.),3.0,4.0,NaN,servant room,"Abcd, Sector 102 Gurgaon, Gurgaon, Haryana",16.0,South,1 to 5 Year Old,"['Huda Metro Station', 'Ocus Medley Mall', 'Th...",National standard football field with flood li...,"['1 Stove', '5 AC', '1 Modular Kitchen', '1 Ch...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
2,2 BHK Flat in Sector 108 Gurgaon,flat,Raheja Vedaanta3.6 ★,sector 108,0.70,4666.0,1500.0,Built Up area: 1468 (136.38 sq.m.)Carpet area:...,2.0,2.0,1.0,not available,"Sector 108, Sector 108 Gurgaon, Gurgaon, Haryana",10.0,West,5 to 10 Year Old,NaN,"2 bath, semi furnished, 10th floor (Of 16), ov...",NaN,NaN,"['Green Area4 out of 5', 'Amenities4 out of 5'..."
3,4 BHK Flat in Sector 84 Gurgaon,flat,Alpha Corp GurgaonOne 844.0 ★,sector 84,2.24,6523.0,3434.0,Super Built up area 3434(319.03 sq.m.)Carpet a...,4.0,4.0,3.0,servant room,"Sector 84 Gurgaon, Gurgaon, Haryana",12.0,West,1 to 5 Year Old,"['Delhi Public School', 'Raheja Market', 'Sapp...",Check out this 4 bhk apartment for sale in alp...,NaN,"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area5 out of 5', 'Construction5 out of..."
4,4 BHK Flat in Sector 110 Gurgaon,flat,Indiabulls Enigma,sector 110,3.40,10000.0,3400.0,Super Built up area 3400(315.87 sq.m.)Built Up...,4.0,5.0,3.0,servant room,"Sector 110 Gurgaon, Gurgaon, Haryana",10.0,South-West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...",Spacious 4 bhk flat in indiabulls enigma at se...,"['6 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Water purifier', 'Security / Fire Alarm', 'P...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [39]:
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [40]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
2290,house,independent,sector 9,0.60,10753.0,558.0,Plot area 62(51.84 sq.m.),2.0,2.0,1.0,not available,1.0,North-East,5 to 10 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Esic...",NaN,['Park']
3497,flat,ATS Kocoon,sector 109,2.20,10501.0,2095.0,Super Built up area 2095(194.63 sq.m.)Built Up...,3.0,4.0,3.0,servant room,13.0,West,1 to 5 Year Old,"['Jagdish Super Market', 'Dwarka', 'Euro Inter...","['4 AC', '1 Modular Kitchen', 'No Bed', 'No Ch...","['Water purifier', 'Security / Fire Alarm', 'F..."
222,flat,Smart World Gems,sector 89,0.90,8159.0,1103.0,Super Built up area 1103(102.47 sq.m.),2.0,2.0,2.0,"study room,others",2.0,East,Within 6 months,"['Sant Soordas Sihi Metro Station', 'Airia Mal...",NaN,"['Intercom Facility', 'Lift(s)', 'Maintenance ..."
623,house,eldeco mansionz,sector 48,4.95,20599.0,2403.0,Plot area 267(223.25 sq.m.),7.0,7.0,NaN,"pooja room,study room,servant room,store room",2.0,South,10+ Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","['11 Fan', '1 Exhaust Fan', '6 Geyser', '30 Li...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
1706,house,independent,sector 4,0.65,11111.0,585.0,Plot area 65(54.35 sq.m.),4.0,2.0,2.0,not available,NaN,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","['1 Wardrobe', '1 Exhaust Fan', '10 Light', '1...",NaN

In [41]:
df.duplicated().sum()

np.int64(121)

In [42]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)