<a href="https://colab.research.google.com/github/anshuman4515/Capstone-project/blob/main/data_preprocessing_flats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [4]:
df = pd.read_csv('/content/flats - flats.csv')
df.sample(5)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
1522,4 BHK Flat in Sector 85 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,SS The Leaf3.8 ★,2.1 Crore,"₹ 7,467/sq.ft.",Super Built up area 2812(261.24 sq.m.)Built Up...,4 Bedrooms,4 Bathrooms,3 Balconies,"Pooja Room,Study Room,Servant Room","Sector 85 Gurgaon, Gurgaon, Haryana",7th of 15 Floors,North,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...",Ss is one of the most popular destination for ...,"['6 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4.5 out of 5', 'Construction4.5 ou...",F70087658
2431,2 BHK Flat in Sector 90 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Shree Vardhman Flora3.8 ★,80 Lac,"₹ 5,925/sq.ft.",Built Up area: 1350 (125.42 sq.m.),2 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Shree Vardhman Flora, Sector 90, Gurgaon, Sect...",Ground of 1 Floors,NaN,undefined,"['IRIS Broadway Mall', 'Dwarka Expressway', 'S...",Best 2 bhk apartment for modern-Day lifestyle ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area5 out of 5', 'Construction5 out of...",A69240906
335,3 BHK Flat in Nirvana Country,https://www.99acres.com/3-bhk-bedroom-apartmen...,The Close North4.0 ★,3 Crore,"₹ 11,516/sq.ft.",Super Built up area 2605(242.01 sq.m.),3 Bedrooms,3 Bathrooms,3+ Balconies,Servant Room,"Nirvana Country, Gurgaon, Haryana",14th of 18 Floors,North,10+ Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...","This beautiful 3 bhk flat in nirvana country, ...","['3 Wardrobe', '1 Water Purifier', '7 Fan', '1...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4 out of...",U69330420
2740,1 BHK Flat in Sector 56 Gurgaon,https://www.99acres.com/1-bhk-bedroom-apartmen...,Sobha Smriti Apartments,50 Lac,"₹ 8,333/sq.ft.",Carpet area: 600 (55.74 sq.m.),1 Bedroom,1 Bathroom,2 Balconies,NaN,"Sector 56, Sector 56 Gurgaon, Gurgaon, Haryana",3rd of 3 Floors,NaN,undefined,"['Sector 54 chowk metro station', 'Sector metr...",1bhk multistorey apartment for resale in sobha...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Safety4 out of 5', 'Lifestyle5 out of 5', 'E...",E68021668
564,3 BHK Flat in Sector 83 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Emaar Palm Gardens4.1 ★,1.73 Crore,"₹ 9,105/sq.ft.",Super Built up area 1900(176.52 sq.m.)Built Up...,3 Bedrooms,3 Bathrooms,3 Balconies,Servant Room,"305, Sector 83 Gurgaon, Gurgaon, Haryana",5th of 16 Floors,West,1 to 5 Year Old,"[""V'Lante Mall"", 'NH 48 Gurugram', 'iGrow Mont...",Check out this 3 bhk apartment for sale in ema...,"['3 Wardrobe', '9 Fan', '1 Exhaust Fan', '3 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of...",C69392058

In [5]:
df.shape

(3028, 20)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3028 entries, 0 to 3027
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3028 non-null   object
 1   link             3028 non-null   object
 2   society          3027 non-null   object
 3   price            3008 non-null   object
 4   area             3015 non-null   object
 5   areaWithType     3009 non-null   object
 6   bedRoom          3009 non-null   object
 7   bathroom         3009 non-null   object
 8   balcony          3009 non-null   object
 9   additionalRoom   1695 non-null   object
 10  address          3003 non-null   object
 11  floorNum         3007 non-null   object
 12  facing           2128 non-null   object
 13  agePossession    3008 non-null   object
 14  nearbyLocations  2914 non-null   object
 15  description      3009 non-null   object
 16  furnishDetails   2204 non-null   object
 17  features         2595 non-null   object
 18  rating           2677 non-null   object
 19  property_id      3009 non-null   object
dtypes: object(20)
memory usage: 473.3+ KB

In [9]:
df.isnull().sum()

property_name         0
link                  0
society               1
price                20
area                 13
areaWithType         19
bedRoom              19
bathroom             19
balcony              19
additionalRoom     1333
address              25
floorNum             21
facing              900
agePossession        20
nearbyLocations     114
description          19
furnishDetails      824
features            433
rating              351
property_id          19
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.head()

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,https://www.99acres.com/2-bhk-bedroom-apartmen...,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,https://www.99acres.com/2-bhk-bedroom-apartmen...,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [15]:
df.drop(columns=['link','property_id'], inplace=True)

In [17]:
df.rename(columns={'area':'price_per_sqft'},inplace=True)
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [18]:
df['society'].value_counts()

society
SS The Leaf3.8 ★                                     73
Tulip Violet4.3 ★                                    40
Shapoorji Pallonji Joyville Gurugram4.0 ★            39
Signature Global Park4.0 ★                           36
Shree Vardhman Victoria3.8 ★                         35
Tulip Violet4.2 ★                                    33
Smart World Gems                                     32
Smart World Orchard                                  32
Emaar MGF Emerald Floors Premier3.8 ★                32
Paras Dews                                           31
DLF The Ultima4.0 ★                                  31
DLF Regal Gardens3.9 ★                               30
M3M Woodshire4.0 ★                                   29
Shree Vardhman Flora3.8 ★                            29
Signature Global Solera3.7 ★                         28
La Vida by Tata Housing                              28
Godrej Nature Plus                                   27
Emaar Gurgaon Greens4.1 ★                            25
BPTP Terra3.8 ★                                      25
DLF New Town Heights 13.9 ★                          24
Vatika Gurgaon 213.7 ★                               24
Eldeco Accolade3.8 ★                                 24
Experion The Heartsong3.9 ★                          24
Bestech Park View Residency3.9 ★                     23
M3M Heights                                          22
Tata Primanti4.1 ★                                   22
Emaar Palm Gardens4.1 ★                              22
ATS Triumph3.9 ★                                     22
ROF Ananda                                           21
Sare Crescent Parc3.5 ★                              21
Godrej 1014.0 ★                                      20
Experion Windchants3.8 ★                             20
Supertech Araville                                   19
Antriksh Heights3.7 ★                                19
Sare Homes                                           19
Ambience Creacions                                   18
ATS Tourmaline3.9 ★                                  18
Sobha City                                           18
CHD Avenue 713.6 ★                                   18
Indiabulls Centrum Park3.7 ★                         18
Mapsko Mount Ville4.1 ★                              18
M3M Golfestate4.4 ★                                  17
Conscient Heritage Max4.3 ★                          17
M3M Skywalk                                          17
Pareena Coban Residences                             17
GLS Arawali Homes3.8 ★                               17
Godrej Summit3.7 ★                                   17
Godrej Oasis3.9 ★                                    16
Bestech Park View Grand Spa4.3 ★                     16
HCBS Sports Ville3.6 ★                               16
M3M Merlin3.7 ★                                      16
Umang Monsoon Breeze                                 16
Corona Optus3.9 ★                                    15
Emaar MGF The Palm Drive4.1 ★                        15
Ansal Heights 86                                     15
MVN Athens3.7 ★                                      14
Vatika The Seven Lamps3.8 ★                          14
Ireo Victory Valley4.1 ★                             14
The Close North4.0 ★                                 14
Ireo Skyon4.0 ★                                      14
Indiabulls Enigma                                    14
Ramsons Kshitij3.7 ★                                 14
Orchid Petals4.1 ★                                   14
Imperia The Esfera                                   14
Umang Winter Hills3.9 ★                              14
DLF The Primus3.9 ★                                  14
Ireo The Corridors                                   13
Central Park Flower Valley                           13
Puri Emerald Bay3.7 ★                                13
Bestech Park View Ananda4.2 ★                        13
TARC Maceo3.8 ★                                      11
Alpha Corp GurgaonOne 844.0 ★                        11
SBTL Caladium                                        11
Godrej Aria3.8 ★                                     11
Adani M2K Oyster Grande3.9 ★                         11
Raheja Vedaanta3.6 ★                                 11
DLF The Skycourt4.2 ★                                11
M3M Soulitude                                        11
Breez Global Hill View                               11
ATS Kocoon                                           10
Puri Diplomatic Greens4.0 ★                          10
Breez Global Heights4.2 ★                            10
DLF New Town Heights 24.0 ★                          10
Pivotal Devaan                                       10
Ramprastha The Edge Towers3.5 ★                      10
Zara Aavaas                                          10
Pyramid Urban Homes 2                                10
ILD Greens4.1 ★                                      10
Capital Residences 360                               10
Signature Global Synera3.4 ★                         10
Emaar MGF Palm Hills4.0 ★                            10
Godrej Air                                           10
Pareena Mi Casa                                       9
Parsvnath Green Ville3.9 ★                            9
Vatika City4.1 ★                                      9
Microtek Greenburg3.8 ★                               9
AIPL The Peaceful Homes3.9 ★                          9
Bestech Park View Sanskruti4.2 ★                      9
The Lions CGHS                                        8
Vatika Lifestyle Homes3.8 ★                           8
Tulip Ivory3.5 ★                                      8
ss                                                    8
Bestech Altura                                        8
M3M Skycity                                           8
Orris Aster Court Premier                             8
AVL 36 Gurgaon3.7 ★                                   8
Emaar Digihomes                                       8
Birla Navya                                           8
GLS Avenue 51                                         8
M3M Capital                                           8
Assotech Blith                                        8
Emaar Imperial Gardens3.8 ★                           7
Orris Carnation Residency3.7 ★                        7
Vipul Lavanya3.9 ★                                    7
AIPL Zen Residences                                   7
Sare Green ParC Phase 3                               7
Signature Global Orchard Avenue3.6 ★                  7
Mapsko Casa Bella3.8 ★                                7
Sare Crescent Parc Royal Greens Phase 1               7
Signature Global City                                 7
Trisara Our Homes 3                                   7
Ansal Housing Highland Park                           7
Signature Andour Heights3.8 ★                         7
Ireo The Grand Arch4.0 ★                              7
Signature The Roselia3.6 ★                            6
Hero Homes                                            6
Shapoorji Pallonji Joyville Gurugram                  6
Signature Global City 63A                             6
M3M Sierra 68                                         6
Pyramid Urban                                         6
Ashiana Mulberry                                      6
DLF Regency Park 13.6 ★                               6
Sidhartha NCR One Phase 14.2 ★                        6
Bestech Park View City4.1 ★                           6
Parsvnath Exotica3.7 ★                                6
Suncity Vatsal Valley                                 6
Greenopolis                                           6
Bestech Park View Spa Next4.0 ★                       6
HSIIDC Sidco Aravali                                  6
Supertech Hues                                        6
Pioneer Araya3.8 ★                                    6
Mapsko Royale Ville3.7 ★                              6
BPTP Astaire Gardens3.7 ★                             6
Signature Global Park 4                               6
Kiran Residency                                       6
DLF Park Place4.1 ★                                   5
Ireo Uptown4.1 ★                                      5
Vatika Sovereign Park                                 5
Signature Global Grand IVA3.9 ★                       5
Silverglades The Melia                                5
Godrej Habitat                                        5
Signature Global City 92                              5
Adani Brahma Samsara Vilasa                           5
DLF Regency Park 24.0 ★                               5
Signature Global the Millennia                        5
Pioneer Park3.8 ★                                     5
Emaar MGF Emerald Estate3.8 ★                         5
Krisumi Waterfall Residences                          5
Green Court3.7 ★                                      5
Satya The Hermitage3.5 ★                              5
Pareena Laxmi Apartments3.6 ★                         5
Vatika City Homes3.9 ★                                5
Central Park Flower Valley Aqua Front Towers          5
Conscient Elevate                                     5
Apna Enclave                                          5
Signature Global City 81                              5
Central Park Resorts4.4 ★                             5
Signature Global City 37D Ph 2                        5
Ashiana Anmol3.5 ★                                    5
ATS Marigold                                          5
Tulip Monsella                                        5
M3M The Marina4.0 ★                                   5
Essel Towers                                          5
Godrej Frontier3.7 ★                                  4
Tata Gurgaon Gateway3.8 ★                             4
HSIIDC Sidco Shivalik Apartments3.8 ★                 4
Corona Gracieux                                       4
Unitech Fresco3.8 ★                                   4
Ramprastha Primera                                    4
Prime Habitat                                         4
Godrej Icon                                           4
Orris Aster Court                                     4
Ramprastha Skyz                                       4
Signature The Serenas                                 4
Emaar Palm Heights                                    4
Sare Petioles                                         4
SS The Coralwood3.4 ★                                 4
Krrish Provence Estate                                4
DLF New Town Heights3.7 ★                             4
Lotus Homz4.0 ★                                       4
Raheja Navodaya3.6 ★                                  4
DLF The Skycourt                                      4
ILD Grand                                             4
Unitech Vistas                                        4
Railway Officers RPF Society                          4
Global Hill View                                      4
Adani Aangan Arcade                                   3
Sare Green Parc                                       3
Chintels Paradiso3.9 ★                                3
Smriti Apartment                                      3
Tulip White3.5 ★                                      3
DLF Belvedere Towers3.8 ★                             3
Jammu and Kashmir Bank Employees CGHS3.7 ★            3
DLF Carlton Estate4.0 ★                               3
Kendriya Vihar4.1 ★                                   3
Unitech Heritage City                                 3
Signature Global Solera 2                             3
Pivotal Riddhi Siddhi                                 3
SS Almeria                                            3
Whiteland Blissville                                  3
Tulip Petals3.6 ★                                     3
Spaze Privvy The Address3.9 ★                         3
Unitech Uniworld Gardens3.8 ★                         3
Vatika Independent Floors3.8 ★                        3
Piedmont Taksila heights3.6 ★                         3
Krrish Florence Estate                                3
Shri Ram Apartments                                   3
Raheja Atharva3.6 ★                                   3
Tulip Purple                                          3
Siddhartha Apartment                                  3
Ambience Lagoon3.9 ★                                  3
Paras Quartier                                        3
DLF The Arbour                                        3
Unitech Sunbreeze                                     3
AIPL Club Residences                                  3
Sapphire Eighty Three                                 3
DLF The Grove                                         3
Sukhshanti Apartment                                  3
Bestech Park View City 23.9 ★                         3
Apex Our Homes                                        3
Suncity Platinum Towers                               3
Spaze Privy AT43.9 ★                                  3
Conscient Habitat3.6 ★                                3
Puri Diplomatic Greens3.9 ★                           3
Raheja Revanta                                        3
Maxworth City Residences                              3
Dhoot Time Residency4.0 ★                             3
Sunischit Apartments                                  3
Tulip Lemon3.9 ★                                      3
Spaze Privy3.9 ★                                      3
Deepak Minda                                          3
Unitech The Residences3.7 ★                           3
ATS Kocoon4.2 ★                                       3
Vatika Xpressions                                     3
Raheja Sampada                                        3
Sidhartha NCR One                                     3
Satya Element One                                     3
Mahindra Aura4.2 ★                                    3
Valley View Estate                                    3
The Roselia 2                                         3
Shree Arihant Apartment                               3
Sidhartha NCR Greens4.3 ★                             3
Sare Green Parc 2                                     3
DLF Express Greens3.9 ★                               3
Shri Banke Bihari Society3.8 ★                        3
Pyramid Elite                                         3
Brisk Lumbini Terrace Homes                           3
My Home                                               3
AFNHB Jalvayu Vihar3.7 ★                              3
Essel Tower                                           3
DLF Royalton Tower                                    3
Guru Gram Haryana CGHS4.1 ★                           3
Raheja Atlantis3.8 ★                                  2
Central Park 2 Bellevue                               2
Ansal API Esencia3.7 ★                                2
AWHO Shanti Vihar4.0 ★                                2
ROF Aalayas3.8 ★                                      2
M3M Sky Lofts                                         2
Maruti Vihar                                          2
Tulsiani Easy in Homes                                2
ss residency                                          2
Unitech Uniworld Gardens 23.4 ★                       2
BPTP Pedestal                                         2
MRG World Ultimus                                     2
Landmark The Residency                                2
Vasant Appartments                                    2
Chanderlok Society                                    2
Uphar lakshya homes                                   2
Signature Global The Millennia 3                      2
Tulip Orange3.9 ★                                     2
Viridian The Plaza 106                                2
Vatika Emilia Floors3.7 ★                             2
SS Hibiscus                                           2
The Penthouses at the Hibiscus                        2
Pioneer Urban Presidia                                2
M3M Latitude                                          2
Today Callidora                                       2
Housing Board Colony                                  2
Sahara Grace                                          2
Aqua Front Towers                                     2
Mahindra Luminare4.0 ★                                2
lagoon apartment                                      2
Vatika INXT Floors                                    2
Ashiana Anmol                                         2
Ganga Apartment                                       2
Suncity Avenue 76                                     2
Ansal Heights3.2 ★                                    2
M3M Urbana                                            2
CGHS Airport Apartment                                2
Ansal API Celebrity Suites                            2
Supertech Hill Town                                   2
Palam Vihar Society                                   2
Elan The Presidential                                 2
Oriental Valley CHS                                   2
Suncity Heights3.7 ★                                  2
Ramprastha The Atrium3.4 ★                            2
Supertech Hilltown                                    2
Godrej Nature Plus Serenity                           2
NBCC Heights3.9 ★                                     2
Park Royal Apartment                                  2
Mapsko Paradise3.9 ★                                  2
Adani Aangan Galleria                                 2
HCBS Sports Ville                                     2
Emaar MGF Palm Studios                                2
The Close South3.9 ★                                  2
Orchid Island4.2 ★                                    2
Tulip Leaf                                            2
Tulip Violet                                          2
Ardee City3.8 ★                                       2
Suposhaa Smartworld Orchard                           2
Bestech Spa Signature                                 2
Raheja Vanya                                          2
Ramprastha City                                       2
Samaspurkunj                                          2
Apartment                                             2
Vipul World Floors                                    2
Milan CGHS 9                                          2
Element One Service                                   2
Emaar MGF The Enclave                                 2
Breeze Global Heights                                 2
Bestech Park View Sanskruti4.1 ★                      2
Vipul Belmonte3.9 ★                                   2
M3M Ikonic                                            2
BPTP Freedom Park Life4.0 ★                           2
Mittal Surya Vihar                                    2
Residency Grand                                       2
DLF The Crest3.6 ★                                    2
Green Campus CHS                                      2
Puri The Aravallis                                    2
Professors Enclave CGHS                               2
Surendra Avenue 69                                    2
Ambience Caitriona                                    2
Bhagwati Sadan                                        2
Sidhivinayak Apartments                               2
DLF The Belaire3.9 ★                                  2
DLF The Icon3.7 ★                                     2
BPTP Amstoria3.8 ★                                    2
Suncity Avenue 1023.9 ★                               2
Lavanya Apartments                                    2
om appartments                                        2
Dlf City                                              2
Shapoorji Pallonji Joyville                           2
Paras Irene3.7 ★                                      2
Silverglades Hightown Residences                      2
BPTP Mansions Park Prime                              2
Godrej Aria , sector 79 , Gurgaon                     2
Spire Woods Now Ananda by Alpha corp                  1

In [19]:
df['price'].value_counts()

price
1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.2 Crore           59
1.5 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.55 Crore          40
1.9 Crore           40
1.65 Crore          38
75 Lac              38
1.7 Crore           37
1.8 Crore           37
80 Lac              36
2.2 Crore           34
50 Lac              33
1.15 Crore          33
85 Lac              31
1.45 Crore          31
1.05 Crore          30
40 Lac              29
60 Lac              29
2.5 Crore           29
45 Lac              26
2.1 Crore           26
65 Lac              25
2.35 Crore          23
1.85 Crore          23
35 Lac              23
3 Crore             22
70 Lac              21
55 Lac              20
2.25 Crore          20
3.5 Crore           19
2.4 Crore           18
2.3 Crore           18
30 Lac              17
2.65 Crore          16
1.38 Crore          15
2.6 Crore           15
2.45 Crore          14
2.15 Crore          14
3.4 Crore           14
92 Lac              13
2.7 Crore           13
82 Lac              13
78 Lac              13
1.32 Crore          13
3.25 Crore          13
38 Lac              13
1.95 Crore          12
42 Lac              12
2.8 Crore           12
1.42 Crore          12
5 Crore             12
Price on Request    11
88 Lac              11
32 Lac              11
1.08 Crore          11
25 Lac              11
28 Lac              10
1.12 Crore          10
26 Lac              10
2.55 Crore          10
1.78 Crore          10
87 Lac              10
1.28 Crore          10
1.68 Crore           9
2.05 Crore           9
3.45 Crore           9
4 Crore              9
1.72 Crore           9
22 Lac               9
99 Lac               9
2.85 Crore           9
36 Lac               9
20 Lac               8
1.54 Crore           8
1.76 Crore           8
98 Lac               8
6 Crore              8
1.18 Crore           8
6.5 Crore            8
4.25 Crore           8
1.26 Crore           8
2.75 Crore           8
3.2 Crore            8
48 Lac               8
86 Lac               8
27 Lac               8
56 Lac               8
1.99 Crore           7
79 Lac               7
46 Lac               7
72 Lac               7
2.9 Crore            7
1.19 Crore           7
1.27 Crore           7
3.3 Crore            7
39 Lac               7
3.7 Crore            7
1.02 Crore           7
1.36 Crore           7
97 Lac               7
1.29 Crore           7
1.49 Crore           6
37 Lac               6
1.01 Crore           6
1.07 Crore           6
96 Lac               6
5.5 Crore            6
1.51 Crore           6
1.34 Crore           6
43 Lac               6
1.13 Crore           6
4.1 Crore            6
71.5 Lac             6
3.65 Crore           6
54 Lac               6
3.05 Crore           6
1.39 Crore           6
1.14 Crore           6
3.35 Crore           6
1.59 Crore           6
21 Lac               6
1.16 Crore           6
3.9 Crore            6
2.95 Crore           6
1.98 Crore           6
1.62 Crore           5
1.83 Crore           5
68 Lac               5
1.92 Crore           5
64 Lac               5
4.5 Crore            5
93 Lac               5
1.44 Crore           5
24 Lac               5
1.69 Crore           5
1.91 Crore           5
1.43 Crore           5
1.17 Crore           5
2.22 Crore           5
1.82 Crore           5
1.79 Crore           5
2.78 Crore           5
2.29 Crore           5
49 Lac               5
1.33 Crore           5
2.12 Crore           5
1.93 Crore           5
1.24 Crore           5
66 Lac               5
6.75 Crore           5
3.75 Crore           5
29 Lac               5
1.47 Crore           5
58 Lac               4
89 Lac               4
1.23 Crore           4
6.15 Crore           4
67 Lac               4
5.9 Crore            4
62 Lac               4
7 Crore              4
4.85 Crore           4
5.25 Crore           4
1.37 Crore           4
73 Lac               4
36.5 Lac             4
33 Lac               4
1.64 Crore           4
3.6 Crore            4
4.3 Crore            4
1.22 Crore           4
31 Lac               4
1.66 Crore           4
3.1 Crore            4
74 Lac               4
41.5 Lac             4
28.5 Lac             4
2.09 Crore           4
1.71 Crore           4
1.73 Crore           4
1.58 Crore           4
1.31 Crore           4
3.95 Crore           4
1.77 Crore           4
1.52 Crore           4
1.48 Crore           4
5.6 Crore            4
47 Lac               3
2.08 Crore           3
69 Lac               3
94 Lac               3
2.01 Crore           3
1.57 Crore           3
1.88 Crore           3
84 Lac               3
83 Lac               3
64.5 Lac             3
2.51 Crore           3
51 Lac               3
5.8 Crore            3
1.63 Crore           3
4.2 Crore            3
72.5 Lac             3
1.09 Crore           3
4.8 Crore            3
2.28 Crore           3
3.49 Crore           3
91 Lac               3
1.21 Crore           3
2.36 Crore           3
34 Lac               3
1.67 Crore           3
3.8 Crore            3
2.03 Crore           3
1.04 Crore           3
3.15 Crore           3
3.85 Crore           3
2.33 Crore           3
2.79 Crore           3
1.41 Crore           3
52 Lac               3
2.24 Crore           3
4.75 Crore           3
41 Lac               2
2.41 Crore           2
4.26 Crore           2
14 Crore             2
2.02 Crore           2
2.91 Crore           2
27.75 Lac            2
52.56 Lac            2
4.55 Crore           2
11 Crore             2
7.5 Crore            2
27.1 Lac             2
2.04 Crore           2
25.5 Lac             2
5.7 Crore            2
2.58 Crore           2
2.14 Crore           2
56.2 Lac             2
31.5 Lac             2
3.55 Crore           2
98.5 Lac             2
87.5 Lac             2
59 Lac               2
88.5 Lac             2
71 Lac               2
4.7 Crore            2
4.45 Crore           2
3.29 Crore           2
1.56 Crore           2
2.99 Crore           2
2.26 Crore           2
2.13 Crore           2
2.17 Crore           2
8.5 Crore            2
8 Crore              2
1.46 Crore           2
53.5 Lac             2
2.52 Crore           2
2.23 Crore           2
6.2 Crore            2
4.49 Crore           2
3.32 Crore           2
3.21 Crore           2
4.6 Crore            2
1.87 Crore           2
77.5 Lac             2
53 Lac               2
2.87 Crore           2
2.57 Crore           2
5.2 Crore            2
99.5 Lac             1
3.83 Crore           1
6.16 Crore           1
5.3 Crore            1
2.72 Crore           1
2.98 Crore           1
66.99 Lac            1
2.48 Crore           1
89.5 Lac             1
2.21 Crore           1
97.04 Lac            1
3.23 Crore           1
94.5 Lac             1
82.5 Lac             1
3.99 Crore           1
9 Crore              1
2.44 Crore           1
7.9 Crore            1
6.02 Crore           1
29.8 Lac             1
61 Lac               1
54.8 Lac             1
3.98 Crore           1
2.54 Crore           1
15 Crore             1
39.5 Lac             1
4.02 Crore           1
7.8 Crore            1
1.97 Crore           1
price                1
3.87 Crore           1
4.95 Crore           1
5.31 Crore           1
5.4 Crore            1
55.6 Lac             1
98.1 Lac             1
2.63 Crore           1
95.75 Lac            1
3.46 Crore           1
3.19 Crore           1
3.67 Crore           1
8.25 Crore           1
4.63 Crore           1
4.4 Crore            1
29.5 Lac             1
68.85 Lac            1
98.88 Lac            1
3.78 Crore           1
37.5 Lac             1
2.69 Crore           1
4.78 Crore           1
3.63 Crore           1
80.5 Lac             1
68.5 Lac             1
85.5 Lac             1
93.75 Lac            1
94.25 Lac            1
4.79 Crore           1
31.75 Lac            1
55.5 Lac             1
2.37 Crore           1
23.5 Lac             1
27.5 Lac             1
2.82 Crore           1
54.99 Lac            1
7.15 Crore           1
35.5 Lac             1
10.75 Crore          1
4.94 Crore           1
1.06 Crore           1
2.11 Crore           1
5.75 Crore           1
6.1 Crore            1
8.35 Crore           1
81 Lac               1
26.1 Lac             1
9.14 Crore           1
20.5 Lac             1
17.5 Lac             1
24.5 Lac             1
10 Crore             1
29.99 Lac            1
79.9 Lac             1
23 Lac               1
71.2 Lac             1
11.25 Crore          1
6.3 Crore            1
5.49 Crore           1
2.97 Crore           1
1.11 Crore           1
6.44 Crore           1
7.56 Crore           1
4.67 Crore           1
4.86 Crore           1
2.62 Crore           1
90.5 Lac             1
52.5 Lac             1
53.2 Lac             1
42.5 Lac             1
2.61 Crore           1
65.5 Lac             1
6.25 Crore           1
2.77 Crore           1
47.5 Lac             1
4.16 Crore           1
4.52 Crore           1
1.74 Crore           1
9.3 Crore            1
4.21 Crore           1
97.5 Lac             1
2.64 Crore           1
2.49 Crore           1
63.4 Lac             1
2.06 Crore           1
2.07 Crore           1
44 Lac               1
2.32 Crore           1
1.86 Crore           1
85.75 Lac            1
8.44 Crore           1
1.84 Crore           1
13.2 Crore           1
2.92 Crore           1
2.38 Crore           1
5.15 Crore           1
16 Lac               1
49.5 Lac             1
9.2 Crore            1
9.95 Crore           1
86.99 Lac            1
87.99 Lac            1
37.1 Lac             1
2.86 Crore           1
7.4 Crore            1
86.92 Lac            1
64.45 Lac            1
2.34 Crore           1
3.79 Crore           1
3.39 Crore           1
94.99 Lac            1
88.4 Lac             1
3.72 Crore           1
57 Lac               1
95.5 Lac             1
96.07 Lac            1
19 Lac               1
70.85 Lac            1
7.52 Crore           1
40.3 Lac             1
32.5 Lac             1
2.96 Crore           1
1.53 Crore           1
26.9 Lac             1
26.5 Lac             1
73.53 Lac            1
89.77 Lac            1
62.5 Lac             1
Name: count, dtype: int64

In [20]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [21]:
df.shape

(3028, 18)

In [22]:
df[df['price'] == 'Price on Request']

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
25,5 BHK Flat in Sector 1 Gurgaon,The New People Apartments,Price on Request,NaN,Built Up area: 4500 (418.06 sq.m.),5 Bedrooms,1 Bathroom,No Balcony,NaN,"Sector 1, Sector 1 Gurgaon, Gurgaon, Haryana",Ground of 1 Floors,NaN,undefined,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Best in class property available at sector 1 l...,NaN,NaN,NaN
1645,4 BHK Flat in Sector 50 Gurgaon,SS Hibiscus,Price on Request,NaN,Carpet area: 4800 (445.93 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"Sector 50 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,East,5 to 10 Year Old,"['Baani Square', 'SS Plaza', 'Good Earth City ...",4bedroom 4800sq.Ft middle floor apartment avai...,"['4 Fan', '8 Light', 'No AC', 'No Bed', 'No Ch...","['Lift(s)', 'Water purifier', 'Swimming Pool',...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1973,1 BHK Flat in Sector 31 Gurgaon,Raheja Atlantis3.8 ★,Price on Request,NaN,Carpet area: 650 (60.39 sq.m.),1 Bedroom,1 Bathroom,1 Balcony,"Pooja Room,Study Room,Servant Room","Yes, Sector 31 Gurgaon, Gurgaon, Haryana",3rd of 15 Floors,East,0 to 1 Year Old,"['Huda Metro Station', 'Reliance Fresh, Indira...",It is my property and good condition and good ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction4 out of..."
2055,2 BHK Flat in Sector 79 Gurgaon,Supertech Araville,Price on Request,NaN,Built Up area: 1295 (120.31 sq.m.),2 Bedrooms,2 Bathrooms,No Balcony,NaN,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",15th of 15 Floors,NaN,undefined,NaN,"2 bath, unfurnished, 15th floor (Of 18), super...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle3 out of 5..."
2358,2 BHK Flat in Sector 37D Gurgaon,The Millennia 2,Price on Request,NaN,Carpet area: 552 (51.28 sq.m.),2 Bedrooms,1 Bathroom,1 Balcony,NaN,"Sector 37D Gurgaon, Gurgaon, Haryana",13rd of 13 Floors,NaN,undefined,"['Shri Balaji Hospital and Trauma Center', 'Sh...","1 bath, unfurnished, 13th floor (Of 13), at se...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2523,2 BHK Flat in Sector 95A Gurgaon,The Roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4.5 out of..."
2550,3 BHK Flat in Sector-2 Sohna,Supertech Hilltown,Price on Request,NaN,Built Up area: 1720 (159.79 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"Sohna Sector 2,gurgaon, Sector-2 Sohna, Gurgao...",4th of 4 Floors,North-East,undefined,NaN,"3 bath, unfurnished, 4th floor (Of 4), overloo...",NaN,NaN,NaN
2641,2 BHK Flat in Sector 95A Gurgaon,The Roselia 2,Price on Request,NaN,Carpet area: 593 (55.09 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Sector 95a, Pataudi Road, Sector 95A Gurgaon, ...",14th of 14 Floors,NaN,undefined,NaN,Best in class property available at sector 95a...,NaN,NaN,"['Environment5 out of 5', 'Safety5 out of 5', ..."
2960,3 BHK Flat in Sector 104 Gurgaon,Godrej Summit3.7 ★,Price on Request,NaN,Super Built up area 1647(153.01 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"1402, Sector 104 Gurgaon, Gurgaon, Haryana",14th of 17 Floors,NaN,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",We are the proud owners of this 3 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Management3 out of 5', 'Green Area4.5 out of..."
2973,4 BHK Flat in Gwal Pahari,Krrish Provence Estate,Price on Request,NaN,Built Up area: 5800 (538.84 sq.m.),4 Bedrooms,5 Bathrooms,1 Balcony,NaN,"Gwal Pahari, Gurgaon, Haryana",17th of 24 Floors,NaN,Under Construction,"['Tniy Toons School', 'Pathways School Gurgoan...",Residential apartment for sell.Located on 17th...,NaN,NaN,NaN
2974,4 BHK Flat in Sector 95 Gurgaon,Sidhartha NCR One Phase 24.1 ★,Price on Request,NaN,Super Built up area 2354(218.69 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",Ground of 3 Floors,North,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","North facing entry, Very good layout, Excellen...",[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Management4 out of 5', 'Green Area4 out of 5..."

In [25]:
df = df[df['price'] != 'Price on Request']

In [26]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [29]:
def treat_price(x):
    try:
        if len(x) >= 2 and x[1] == 'Lac':
            return round(float(x[0]) / 100, 2)
        else:
            return float(x[0])
    except:
        return None

In [30]:
df['price'] = df['price'].str.split(' ').apply(treat_price)

In [31]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [32]:
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 10,000/sq.ft.     19
₹ 8,000/sq.ft.      16
₹ 12,500/sq.ft.     16
₹ 6,666/sq.ft.      13
₹ 5,000/sq.ft.      13
₹ 8,333/sq.ft.      12
₹ 7,500/sq.ft.      12
₹ 6,000/sq.ft.      11
₹ 8,461/sq.ft.       9
₹ 9,000/sq.ft.       8
₹ 7,000/sq.ft.       8
₹ 12,000/sq.ft.      8
₹ 11,111/sq.ft.      7
₹ 6,578/sq.ft.       6
₹ 8,888/sq.ft.       6
₹ 9,230/sq.ft.       6
₹ 8,928/sq.ft.       6
₹ 11,500/sq.ft.      6
₹ 5,500/sq.ft.       6
₹ 7,692/sq.ft.       5
₹ 7,142/sq.ft.       5
₹ 16,000/sq.ft.      5
₹ 6,500/sq.ft.       5
₹ 11,428/sq.ft.      5
₹ 4,666/sq.ft.       5
₹ 4,444/sq.ft.       5
₹ 8,108/sq.ft.       5
₹ 5,384/sq.ft.       5
₹ 5,600/sq.ft.       5
₹ 4,615/sq.ft.       5
₹ 14,242/sq.ft.      5
₹ 7,641/sq.ft.       5
₹ 7,407/sq.ft.       5
₹ 8,205/sq.ft.       5
₹ 8,571/sq.ft.       5
₹ 5,556/sq.ft.       5
₹ 10,714/sq.ft.      5
₹ 7,812/sq.ft.       4
₹ 4,854/sq.ft.       4
₹ 7,317/sq.ft.       4
₹ 13,636/sq.ft.      4
₹ 6,735/sq.ft.       4
₹ 8,358/sq.ft.       4
₹ 8,445/sq.ft.       4
₹ 13,750/sq.ft.      4
₹ 4,500/sq.ft.       4
₹ 6,250/sq.ft.       4
₹ 8,474/sq.ft.       4
₹ 8,784/sq.ft.       4
₹ 4,814/sq.ft.       4
₹ 11,666/sq.ft.      4
₹ 8,139/sq.ft.       4
₹ 10,383/sq.ft.      4
₹ 9,210/sq.ft.       4
₹ 13,913/sq.ft.      4
₹ 7,250/sq.ft.       4
₹ 4,687/sq.ft.       4
₹ 8,484/sq.ft.       4
₹ 8,432/sq.ft.       4
₹ 16,666/sq.ft.      4
₹ 9,822/sq.ft.       4
₹ 5,660/sq.ft.       4
₹ 10,416/sq.ft.      4
₹ 7,496/sq.ft.       4
₹ 7,272/sq.ft.       4
₹ 15,000/sq.ft.      4
₹ 9,090/sq.ft.       4
₹ 8,787/sq.ft.       4
₹ 8,500/sq.ft.       4
₹ 8,043/sq.ft.       4
₹ 8,163/sq.ft.       4
₹ 15,384/sq.ft.      4
₹ 14,418/sq.ft.      4
₹ 16,969/sq.ft.      3
₹ 6,476/sq.ft.       3
₹ 5,325/sq.ft.       3
₹ 13,392/sq.ft.      3
₹ 8,389/sq.ft.       3
₹ 5,878/sq.ft.       3
₹ 16,470/sq.ft.      3
₹ 8,750/sq.ft.       3
₹ 7,948/sq.ft.       3
₹ 7,954/sq.ft.       3
₹ 9,972/sq.ft.       3
₹ 10,638/sq.ft.      3
₹ 6,404/sq.ft.       3
₹ 8,215/sq.ft.       3
₹ 8,078/sq.ft.       3
₹ 14,254/sq.ft.      3
₹ 6,818/sq.ft.       3
₹ 8,222/sq.ft.       3
₹ 10,500/sq.ft.      3
₹ 6,387/sq.ft.       3
₹ 11,000/sq.ft.      3
₹ 7,302/sq.ft.       3
₹ 11,363/sq.ft.      3
₹ 8,080/sq.ft.       3
₹ 7,541/sq.ft.       3
₹ 6,421/sq.ft.       3
₹ 14,430/sq.ft.      3
₹ 5,833/sq.ft.       3
₹ 6,086/sq.ft.       3
₹ 9,011/sq.ft.       3
₹ 7,150/sq.ft.       3
₹ 8,400/sq.ft.       3
₹ 7,586/sq.ft.       3
₹ 5,856/sq.ft.       3
₹ 5,555/sq.ft.       3
₹ 8,532/sq.ft.       3
₹ 7,179/sq.ft.       3
₹ 7,083/sq.ft.       3
₹ 6,593/sq.ft.       3
₹ 8,181/sq.ft.       3
₹ 8,620/sq.ft.       3
₹ 8,606/sq.ft.       3
₹ 5,238/sq.ft.       3
₹ 9,900/sq.ft.       3
₹ 5,397/sq.ft.       3
₹ 5,319/sq.ft.       3
₹ 4,800/sq.ft.       3
₹ 9,500/sq.ft.       3
₹ 6,470/sq.ft.       3
₹ 10,555/sq.ft.      3
₹ 7,467/sq.ft.       3
₹ 7,865/sq.ft.       3
₹ 7,400/sq.ft.       3
₹ 9,473/sq.ft.       3
₹ 5,735/sq.ft.       3
₹ 6,921/sq.ft.       3
₹ 13,000/sq.ft.      3
₹ 6,644/sq.ft.       3
₹ 9,615/sq.ft.       3
₹ 4,820/sq.ft.       3
₹ 14,000/sq.ft.      3
₹ 10,139/sq.ft.      3
₹ 7,549/sq.ft.       3
₹ 4,210/sq.ft.       3
₹ 4,513/sq.ft.       3
₹ 6,542/sq.ft.       3
₹ 8,886/sq.ft.       3
₹ 8,450/sq.ft.       3
₹ 10,204/sq.ft.      3
₹ 7,056/sq.ft.       3
₹ 13,870/sq.ft.      3
₹ 6,667/sq.ft.       3
₹ 4,105/sq.ft.       3
₹ 9,904/sq.ft.       3
₹ 8,148/sq.ft.       3
₹ 7,750/sq.ft.       3
₹ 8,604/sq.ft.       3
₹ 6,178/sq.ft.       2
₹ 9,135/sq.ft.       2
₹ 7,796/sq.ft.       2
₹ 10,476/sq.ft.      2
₹ 5,470/sq.ft.       2
₹ 4,400/sq.ft.       2
₹ 33,198/sq.ft.      2
₹ 7,200/sq.ft.       2
₹ 10,666/sq.ft.      2
₹ 5,189/sq.ft.       2
₹ 5,291/sq.ft.       2
₹ 6,702/sq.ft.       2
₹ 6,616/sq.ft.       2
₹ 15,151/sq.ft.      2
₹ 6,200/sq.ft.       2
₹ 7,846/sq.ft.       2
₹ 7,297/sq.ft.       2
₹ 5,528/sq.ft.       2
₹ 8,903/sq.ft.       2
₹ 6,811/sq.ft.       2
₹ 5,588/sq.ft.       2
₹ 9,128/sq.ft.       2
₹ 11,574/sq.ft.      2
₹ 7,223/sq.ft.       2
₹ 7,608/sq.ft.       2
₹ 6,655/sq.ft.       2
₹ 5,674/sq.ft.       2
₹ 13,343/sq.ft.      2
₹ 14,545/sq.ft.      2
₹ 9,166/sq.ft.       2
₹ 18,000/sq.ft.      2
₹ 4,307/sq.ft.       2
₹ 8,974/sq.ft.       2
₹ 8,670/sq.ft.       2
₹ 8,159/sq.ft.       2
₹ 7,058/sq.ft.       2
₹ 11,715/sq.ft.      2
₹ 7,174/sq.ft.       2
₹ 6,938/sq.ft.       2
₹ 5,671/sq.ft.       2
₹ 19,882/sq.ft.      2
₹ 9,791/sq.ft.       2
₹ 9,620/sq.ft.       2
₹ 6,789/sq.ft.       2
₹ 6,967/sq.ft.       2
₹ 6,024/sq.ft.       2
₹ 5,882/sq.ft.       2
₹ 13,500/sq.ft.      2
₹ 9,909/sq.ft.       2
₹ 9,876/sq.ft.       2
₹ 6,190/sq.ft.       2
₹ 6,206/sq.ft.       2
₹ 15,294/sq.ft.      2
₹ 9,978/sq.ft.       2
₹ 3,695/sq.ft.       2
₹ 11,992/sq.ft.      2
₹ 5,658/sq.ft.       2
₹ 7,758/sq.ft.       2
₹ 7,863/sq.ft.       2
₹ 11,250/sq.ft.      2
₹ 8,504/sq.ft.       2
₹ 7,097/sq.ft.       2
₹ 7,490/sq.ft.       2
₹ 6,076/sq.ft.       2
₹ 15,500/sq.ft.      2
₹ 5,150/sq.ft.       2
₹ 6,111/sq.ft.       2
₹ 7,782/sq.ft.       2
₹ 7,780/sq.ft.       2
₹ 5,111/sq.ft.       2
₹ 5,786/sq.ft.       2
₹ 6,985/sq.ft.       2
₹ 12,777/sq.ft.      2
₹ 8,517/sq.ft.       2
₹ 9,452/sq.ft.       2
₹ 6,927/sq.ft.       2
₹ 11,724/sq.ft.      2
₹ 6,377/sq.ft.       2
₹ 10,531/sq.ft.      2
₹ 5,038/sq.ft.       2
₹ 5,797/sq.ft.       2
₹ 11,627/sq.ft.      2
₹ 6,569/sq.ft.       2
₹ 11,529/sq.ft.      2
₹ 6,217/sq.ft.       2
₹ 9,062/sq.ft.       2
₹ 9,449/sq.ft.       2
₹ 8,053/sq.ft.       2
₹ 8,618/sq.ft.       2
₹ 6,686/sq.ft.       2
₹ 8,972/sq.ft.       2
₹ 7,585/sq.ft.       2
₹ 10,601/sq.ft.      2
₹ 6,510/sq.ft.       2
₹ 41,245/sq.ft.      2
₹ 9,851/sq.ft.       2
₹ 8,075/sq.ft.       2
₹ 7,727/sq.ft.       2
₹ 15,998/sq.ft.      2
₹ 11,700/sq.ft.      2
₹ 6,551/sq.ft.       2
₹ 9,677/sq.ft.       2
₹ 8,720/sq.ft.       2
₹ 6,318/sq.ft.       2
₹ 6,983/sq.ft.       2
₹ 6,739/sq.ft.       2
₹ 6,325/sq.ft.       2
₹ 6,061/sq.ft.       2
₹ 6,429/sq.ft.       2
₹ 5,100/sq.ft.       2
₹ 5,517/sq.ft.       2
₹ 9,025/sq.ft.       2
₹ 6,373/sq.ft.       2
₹ 18,271/sq.ft.      2
₹ 8,252/sq.ft.       2
₹ 16,985/sq.ft.      2
₹ 6,422/sq.ft.       2
₹ 4,909/sq.ft.       2
₹ 8,897/sq.ft.       2
₹ 8,609/sq.ft.       2
₹ 8,524/sq.ft.       2
₹ 9,600/sq.ft.       2
₹ 7,574/sq.ft.       2
₹ 7,225/sq.ft.       2
₹ 9,286/sq.ft.       2
₹ 8,006/sq.ft.       2
₹ 17,619/sq.ft.      2
₹ 8,206/sq.ft.       2
₹ 6,597/sq.ft.       2
₹ 18,181/sq.ft.      2
₹ 4,271/sq.ft.       2
₹ 14,257/sq.ft.      2
₹ 9,333/sq.ft.       2
₹ 14,214/sq.ft.      2
₹ 7,248/sq.ft.       2
₹ 10,603/sq.ft.      2
₹ 7,391/sq.ft.       2
₹ 16,960/sq.ft.      2
₹ 11,516/sq.ft.      2
₹ 13,769/sq.ft.      2
₹ 6,428/sq.ft.       2
₹ 58/sq.ft.          2
₹ 5,463/sq.ft.       2
₹ 10,370/sq.ft.      2
₹ 4,000/sq.ft.       2
₹ 5,899/sq.ft.       2
₹ 11,333/sq.ft.      2
₹ 9,182/sq.ft.       2
₹ 12,782/sq.ft.      2
₹ 8,072/sq.ft.       2
₹ 14,583/sq.ft.      2
₹ 9,259/sq.ft.       2
₹ 10,384/sq.ft.      2
₹ 10,526/sq.ft.      2
₹ 8,582/sq.ft.       2
₹ 8,310/sq.ft.       2
₹ 7,530/sq.ft.       2
₹ 5,405/sq.ft.       2
₹ 11,755/sq.ft.      2
₹ 9,146/sq.ft.       2
₹ 7,396/sq.ft.       2
₹ 4,327/sq.ft.       2
₹ 15,263/sq.ft.      2
₹ 16,747/sq.ft.      2
₹ 8,290/sq.ft.       2
₹ 8,519/sq.ft.       2
₹ 3,911/sq.ft.       2
₹ 6,333/sq.ft.       2
₹ 6,315/sq.ft.       2
₹ 7,631/sq.ft.       2
₹ 11,726/sq.ft.      2
₹ 9,263/sq.ft.       2
₹ 6,189/sq.ft.       2
₹ 13,281/sq.ft.      2
₹ 7,825/sq.ft.       2
₹ 13,224/sq.ft.      2
₹ 9,022/sq.ft.       2
₹ 12,012/sq.ft.      2
₹ 7,185/sq.ft.       2
₹ 14,478/sq.ft.      2
₹ 4,651/sq.ft.       2
₹ 14,800/sq.ft.      2
₹ 8,521/sq.ft.       2
₹ 11,028/sq.ft.      2
₹ 6,134/sq.ft.       2
₹ 16,858/sq.ft.      2
₹ 8,166/sq.ft.       2
₹ 9,027/sq.ft.       2
₹ 6,420/sq.ft.       2
₹ 10,018/sq.ft.      2
₹ 14,237/sq.ft.      2
₹ 8,433/sq.ft.       2
₹ 20,687/sq.ft.      2
₹ 12,212/sq.ft.      2
₹ 13,108/sq.ft.      2
₹ 15,551/sq.ft.      2
₹ 15,416/sq.ft.      2
₹ 5,980/sq.ft.       2
₹ 5,828/sq.ft.       2
₹ 8,518/sq.ft.       2
₹ 6,588/sq.ft.       2
₹ 8,756/sq.ft.       2
₹ 9,482/sq.ft.       2
₹ 5,599/sq.ft.       2
₹ 4,745/sq.ft.       2
₹ 6,382/sq.ft.       2
₹ 14,683/sq.ft.      2
₹ 14,303/sq.ft.      2
₹ 11,505/sq.ft.      2
₹ 5,177/sq.ft.       2
₹ 8,305/sq.ft.       2
₹ 9,589/sq.ft.       2
₹ 5,564/sq.ft.       2
₹ 6,243/sq.ft.       2
₹ 5,681/sq.ft.       2
₹ 7,884/sq.ft.       2
₹ 13,383/sq.ft.      2
₹ 6,053/sq.ft.       2
₹ 4,856/sq.ft.       2
₹ 5,056/sq.ft.       2
₹ 5,641/sq.ft.       2
₹ 5,982/sq.ft.       2
₹ 8,410/sq.ft.       2
₹ 10,516/sq.ft.      2
₹ 10,936/sq.ft.      2
₹ 7,945/sq.ft.       2
₹ 6,049/sq.ft.       2
₹ 8,024/sq.ft.       2
₹ 6,896/sq.ft.       2
₹ 6,153/sq.ft.       2
₹ 9,306/sq.ft.       2
₹ 16,363/sq.ft.      2
₹ 13,709/sq.ft.      2
₹ 8,457/sq.ft.       2
₹ 5,454/sq.ft.       2
₹ 8,424/sq.ft.       2
₹ 7,987/sq.ft.       2
₹ 9,020/sq.ft.       2
₹ 8,412/sq.ft.       2
₹ 8,835/sq.ft.       2
₹ 4,761/sq.ft.       2
₹ 6,465/sq.ft.       2
₹ 6,679/sq.ft.       2
₹ 6,141/sq.ft.       2
₹ 8,376/sq.ft.       2
₹ 8,536/sq.ft.       2
₹ 19,000/sq.ft.      2
₹ 8,324/sq.ft.       2
₹ 14,285/sq.ft.      2
₹ 6,353/sq.ft.       2
₹ 6,406/sq.ft.       2
₹ 6,839/sq.ft.       2
₹ 7,716/sq.ft.       2
₹ 9,743/sq.ft.       2
₹ 5,839/sq.ft.       2
₹ 11,765/sq.ft.      2
₹ 17,039/sq.ft.      2
₹ 8,846/sq.ft.       2
₹ 10,599/sq.ft.      2
₹ 6,338/sq.ft.       2
₹ 8,035/sq.ft.       2
₹ 8,036/sq.ft.       2
₹ 8,611/sq.ft.       2
₹ 14,785/sq.ft.      2
₹ 12,022/sq.ft.      2
₹ 13,270/sq.ft.      2
₹ 19,767/sq.ft.      2
₹ 7,765/sq.ft.       2
₹ 6,402/sq.ft.       2
₹ 9,950/sq.ft.       2
₹ 10,553/sq.ft.      2
₹ 9,742/sq.ft.       2
₹ 13,076/sq.ft.      2
₹ 6,987/sq.ft.       2
₹ 5,744/sq.ft.       2
₹ 8,294/sq.ft.       2
₹ 3,477/sq.ft.       2
₹ 8,814/sq.ft.       2
₹ 8,031/sq.ft.       2
₹ 9,550/sq.ft.       2
₹ 8,237/sq.ft.       2
₹ 14,615/sq.ft.      2
₹ 7,610/sq.ft.       2
₹ 7,350/sq.ft.       2
₹ 9,074/sq.ft.       2
₹ 7,908/sq.ft.       2
₹ 9,007/sq.ft.       2
₹ 8,733/sq.ft.       2
₹ 9,672/sq.ft.       2
₹ 9,797/sq.ft.       2
₹ 9,922/sq.ft.       2
₹ 7,359/sq.ft.       2
₹ 5,521/sq.ft.       2
₹ 6,812/sq.ft.       2
₹ 5,128/sq.ft.       2
₹ 11,727/sq.ft.      2
₹ 10,489/sq.ft.      2
₹ 15,195/sq.ft.      2
₹ 5,929/sq.ft.       2
₹ 8,283/sq.ft.       2
₹ 8,411/sq.ft.       2
₹ 8,834/sq.ft.       2
₹ 6,692/sq.ft.       2
₹ 5,252/sq.ft.       2
₹ 13,928/sq.ft.      2
₹ 7,850/sq.ft.       2
₹ 7,817/sq.ft.       2
₹ 9,565/sq.ft.       2
₹ 15,454/sq.ft.      2
₹ 6,571/sq.ft.       2
₹ 6,774/sq.ft.       2
₹ 11,412/sq.ft.      2
₹ 4,857/sq.ft.       2
₹ 8,632/sq.ft.       2
₹ 5,513/sq.ft.       2
₹ 9,139/sq.ft.       2
₹ 11,336/sq.ft.      2
₹ 6,029/sq.ft.       2
₹ 10,545/sq.ft.      2
₹ 6,313/sq.ft.       2
₹ 19,747/sq.ft.      2
₹ 7,878/sq.ft.       2
₹ 9,105/sq.ft.       2
₹ 10,699/sq.ft.      2
₹ 7,751/sq.ft.       2
₹ 5,725/sq.ft.       2
₹ 9,433/sq.ft.       2
₹ 10,651/sq.ft.      2
₹ 5,808/sq.ft.       2
₹ 4,080/sq.ft.       2
₹ 10,237/sq.ft.      2
₹ 12,444/sq.ft.      2
₹ 5,896/sq.ft.       2
₹ 5,424/sq.ft.       2
₹ 7,857/sq.ft.       2
₹ 8,600/sq.ft.       2
₹ 8,453/sq.ft.       2
₹ 13,430/sq.ft.      2
₹ 16,608/sq.ft.      2
₹ 5,649/sq.ft.       2
₹ 21,538/sq.ft.      2
₹ 9,854/sq.ft.       2
₹ 11,125/sq.ft.      2
₹ 5,820/sq.ft.       2
₹ 6,254/sq.ft.       2
₹ 6,825/sq.ft.       2
₹ 6,647/sq.ft.       2
₹ 9,642/sq.ft.       2
₹ 11,694/sq.ft.      2
₹ 5,614/sq.ft.       2
₹ 12,222/sq.ft.      2
₹ 10,596/sq.ft.      2
₹ 7,014/sq.ft.       2
₹ 5,825/sq.ft.       2
₹ 8,100/sq.ft.       2
₹ 6,455/sq.ft.       2
₹ 8,947/sq.ft.       2
₹ 5,683/sq.ft.       2
₹ 7,449/sq.ft.       2
₹ 13,991/sq.ft.      2
₹ 8,279/sq.ft.       2
₹ 200,000/sq.ft.     2
₹ 6,538/sq.ft.       2
₹ 6,950/sq.ft.       2
₹ 5,714/sq.ft.       2
₹ 7,627/sq.ft.       2
₹ 6,506/sq.ft.       2
₹ 6,722/sq.ft.       2
₹ 12,250/sq.ft.      2
₹ 13,333/sq.ft.      2
₹ 6,859/sq.ft.       2
₹ 7,234/sq.ft.       2
₹ 6,129/sq.ft.       2
₹ 4,723/sq.ft.       2
₹ 4,818/sq.ft.       2
₹ 4,200/sq.ft.       2
₹ 6,361/sq.ft.       2
₹ 6,493/sq.ft.       2
₹ 18,518/sq.ft.      2
₹ 6,209/sq.ft.       2
₹ 5,284/sq.ft.       2
₹ 5,789/sq.ft.       1
₹ 50,000/sq.ft.      1
₹ 5,367/sq.ft.       1
₹ 4,596/sq.ft.       1
₹ 4,033/sq.ft.       1
₹ 4,879/sq.ft.       1
₹ 6,505/sq.ft.       1
₹ 6,761/sq.ft.       1
₹ 4,700/sq.ft.       1
₹ 12,700/sq.ft.      1
₹ 5,257/sq.ft.       1
₹ 6,064/sq.ft.       1
₹ 17,548/sq.ft.      1
₹ 5,576/sq.ft.       1
₹ 4,657/sq.ft.       1
₹ 7,079/sq.ft.       1
₹ 12,110/sq.ft.      1
₹ 11,739/sq.ft.      1
₹ 14,074/sq.ft.      1
₹ 7,146/sq.ft.       1
₹ 12,400/sq.ft.      1
₹ 13,875/sq.ft.      1
₹ 13,846/sq.ft.      1
₹ 6,708/sq.ft.       1
₹ 6,580/sq.ft.       1
₹ 6,514/sq.ft.       1
₹ 13,929/sq.ft.      1
₹ 17,285/sq.ft.      1
₹ 6,819/sq.ft.       1
₹ 9,133/sq.ft.       1
₹ 12,325/sq.ft.      1
₹ 5,541/sq.ft.       1
₹ 14,557/sq.ft.      1
₹ 13,878/sq.ft.      1
₹ 13,888/sq.ft.      1
₹ 9,036/sq.ft.       1
₹ 9,980/sq.ft.       1
₹ 7,065/sq.ft.       1
₹ 5,499/sq.ft.       1
₹ 4,864/sq.ft.       1
₹ 13,528/sq.ft.      1
₹ 9,622/sq.ft.       1
₹ 9,051/sq.ft.       1
₹ 4,022/sq.ft.       1
₹ 7,437/sq.ft.       1
₹ 21,013/sq.ft.      1
₹ 6,523/sq.ft.       1
₹ 14,623/sq.ft.      1
₹ 13,725/sq.ft.      1
₹ 6,953/sq.ft.       1
₹ 8,724/sq.ft.       1
₹ 24,211/sq.ft.      1
₹ 20,533/sq.ft.      1
₹ 15,469/sq.ft.      1
₹ 10,761/sq.ft.      1
₹ 10,994/sq.ft.      1
₹ 12,144/sq.ft.      1
₹ 12,127/sq.ft.      1
₹ 14,536/sq.ft.      1
₹ 11,052/sq.ft.      1
₹ 10,953/sq.ft.      1
₹ 9,117/sq.ft.       1
₹ 9,387/sq.ft.       1
₹ 3,935/sq.ft.       1
₹ 11,860/sq.ft.      1
₹ 9,266/sq.ft.       1
₹ 10,334/sq.ft.      1
₹ 16,580/sq.ft.      1
₹ 16,750/sq.ft.      1
₹ 8,839/sq.ft.       1
₹ 8,759/sq.ft.       1
₹ 14,983/sq.ft.      1
₹ 11,914/sq.ft.      1
₹ 12,571/sq.ft.      1
₹ 8,242/sq.ft.       1
₹ 12,169/sq.ft.      1
₹ 17,484/sq.ft.      1
₹ 7,403/sq.ft.       1
₹ 35,483/sq.ft.      1
₹ 6,215/sq.ft.       1
₹ 14,727/sq.ft.      1
₹ 8,679/sq.ft.       1
₹ 14,090/sq.ft.      1
₹ 6,052/sq.ft.       1
₹ 14,987/sq.ft.      1
₹ 6,060/sq.ft.       1
₹ 8,516/sq.ft.       1
₹ 10,028/sq.ft.      1
₹ 15,007/sq.ft.      1
₹ 9,203/sq.ft.       1
₹ 10,178/sq.ft.      1
₹ 4,531/sq.ft.       1
₹ 5,859/sq.ft.       1
₹ 14,068/sq.ft.      1
₹ 7,789/sq.ft.       1
₹ 10,365/sq.ft.      1
₹ 8,172/sq.ft.       1
₹ 10,080/sq.ft.      1
₹ 10,461/sq.ft.      1
₹ 8,646/sq.ft.       1
₹ 10,595/sq.ft.      1
₹ 4,836/sq.ft.       1
₹ 5,004/sq.ft.       1
₹ 13,678/sq.ft.      1
₹ 12,599/sq.ft.      1
₹ 11,358/sq.ft.      1
₹ 5,418/sq.ft.       1
₹ 8,825/sq.ft.       1
₹ 9,850/sq.ft.       1
₹ 10,224/sq.ft.      1
₹ 10,262/sq.ft.      1
₹ 13,671/sq.ft.      1
₹ 8,922/sq.ft.       1
₹ 5,490/sq.ft.       1
₹ 6,242/sq.ft.       1
₹ 11,451/sq.ft.      1
₹ 8,998/sq.ft.       1
₹ 7,096/sq.ft.       1
₹ 14,179/sq.ft.      1
₹ 9,238/sq.ft.       1
₹ 5,930/sq.ft.       1
₹ 8,062/sq.ft.       1
₹ 6,002/sq.ft.       1
₹ 6,846/sq.ft.       1
₹ 6,286/sq.ft.       1
₹ 15,685/sq.ft.      1
₹ 13,758/sq.ft.      1
₹ 8,204/sq.ft.       1
₹ 16,266/sq.ft.      1
₹ 12,658/sq.ft.      1
₹ 13,580/sq.ft.      1
₹ 20,388/sq.ft.      1
₹ 12,846/sq.ft.      1
₹ 14,843/sq.ft.      1
₹ 6,852/sq.ft.       1
₹ 5,762/sq.ft.       1
₹ 15,531/sq.ft.      1
₹ 12,484/sq.ft.      1
₹ 3,953/sq.ft.       1
₹ 4,308/sq.ft.       1
₹ 6,265/sq.ft.       1
₹ 7,116/sq.ft.       1
₹ 10,162/sq.ft.      1
₹ 6,310/sq.ft.       1
₹ 4,370/sq.ft.       1
₹ 12,190/sq.ft.      1
₹ 13,253/sq.ft.      1
₹ 12,152/sq.ft.      1
₹ 15,185/sq.ft.      1
₹ 5,973/sq.ft.       1
₹ 6,453/sq.ft.       1
₹ 7,230/sq.ft.       1
₹ 6,585/sq.ft.       1
₹ 11,686/sq.ft.      1
₹ 13,571/sq.ft.      1
₹ 7,525/sq.ft.       1
₹ 11,218/sq.ft.      1
₹ 8,270/sq.ft.       1
₹ 11,713/sq.ft.      1
₹ 21,577/sq.ft.      1
₹ 10,529/sq.ft.      1
₹ 10,147/sq.ft.      1
₹ 6,227/sq.ft.       1
₹ 10,727/sq.ft.      1
₹ 5,942/sq.ft.       1
₹ 10,037/sq.ft.      1
₹ 8,395/sq.ft.       1
₹ 5,597/sq.ft.       1
₹ 8,916/sq.ft.       1
₹ 8,875/sq.ft.       1
₹ 5,207/sq.ft.       1
₹ 19,174/sq.ft.      1
₹ 7,590/sq.ft.       1
₹ 6,801/sq.ft.       1
₹ 7,734/sq.ft.       1
₹ 4,355/sq.ft.       1
₹ 4,528/sq.ft.       1
₹ 6,961/sq.ft.       1
₹ 7,646/sq.ft.       1
₹ 10,174/sq.ft.      1
₹ 14,177/sq.ft.      1
₹ 5,867/sq.ft.       1
₹ 5,717/sq.ft.       1
₹ 10,841/sq.ft.      1
₹ 11,174/sq.ft.      1
₹ 6,625/sq.ft.       1
₹ 8,793/sq.ft.       1
₹ 13,352/sq.ft.      1
₹ 15,561/sq.ft.      1
₹ 6,530/sq.ft.       1
₹ 11,817/sq.ft.      1
₹ 12,372/sq.ft.      1
₹ 8,708/sq.ft.       1
₹ 9,512/sq.ft.       1
₹ 7,380/sq.ft.       1
₹ 18,126/sq.ft.      1
₹ 7,180/sq.ft.       1
₹ 7,072/sq.ft.       1
₹ 12,047/sq.ft.      1
₹ 9,039/sq.ft.       1
₹ 8,623/sq.ft.       1
₹ 8,704/sq.ft.       1
₹ 9,365/sq.ft.       1
₹ 10,041/sq.ft.      1
₹ 9,627/sq.ft.       1
₹ 10,786/sq.ft.      1
₹ 10,443/sq.ft.      1
₹ 8,580/sq.ft.       1
₹ 14,563/sq.ft.      1
₹ 15,514/sq.ft.      1
₹ 9,528/sq.ft.       1
₹ 6,826/sq.ft.       1
₹ 12,788/sq.ft.      1
₹ 10,567/sq.ft.      1
₹ 11,470/sq.ft.      1
₹ 11,204/sq.ft.      1
₹ 11,294/sq.ft.      1
₹ 15,906/sq.ft.      1
₹ 3,309/sq.ft.       1
₹ 4,193/sq.ft.       1
₹ 9,497/sq.ft.       1
₹ 4,746/sq.ft.       1
₹ 9,052/sq.ft.       1
₹ 8,023/sq.ft.       1
₹ 7,208/sq.ft.       1
₹ 7,443/sq.ft.       1
₹ 9,030/sq.ft.       1
₹ 6,424/sq.ft.       1
₹ 11,489/sq.ft.      1
₹ 9,655/sq.ft.       1
₹ 9,169/sq.ft.       1
₹ 10,799/sq.ft.      1
₹ 12,589/sq.ft.      1
₹ 10,853/sq.ft.      1
₹ 5,531/sq.ft.       1
₹ 6,019/sq.ft.       1
₹ 6,104/sq.ft.       1
₹ 10,954/sq.ft.      1
₹ 6,888/sq.ft.       1
₹ 9,212/sq.ft.       1
₹ 6,661/sq.ft.       1
₹ 15,160/sq.ft.      1
₹ 12,140/sq.ft.      1
₹ 10,814/sq.ft.      1
₹ 13,790/sq.ft.      1
₹ 6,713/sq.ft.       1
₹ 14,079/sq.ft.      1
₹ 12,235/sq.ft.      1
₹ 7,196/sq.ft.       1
₹ 6,932/sq.ft.       1
₹ 12,178/sq.ft.      1
₹ 9,584/sq.ft.       1
₹ 12,813/sq.ft.      1
₹ 11,764/sq.ft.      1
₹ 16,129/sq.ft.      1
₹ 8,553/sq.ft.       1
₹ 10,755/sq.ft.      1
₹ 6,851/sq.ft.       1
₹ 8,256/sq.ft.       1
₹ 5,026/sq.ft.       1
₹ 7,636/sq.ft.       1
₹ 7,928/sq.ft.       1
₹ 9,393/sq.ft.       1
₹ 8,813/sq.ft.       1
₹ 10,465/sq.ft.      1
₹ 9,563/sq.ft.       1
₹ 13,589/sq.ft.      1
₹ 10,645/sq.ft.      1
₹ 8,541/sq.ft.       1
₹ 15,418/sq.ft.      1
₹ 10,901/sq.ft.      1
₹ 6,163/sq.ft.       1
₹ 7,991/sq.ft.       1
₹ 3,152/sq.ft.       1
₹ 14,375/sq.ft.      1
₹ 16,959/sq.ft.      1
₹ 5,422/sq.ft.       1
₹ 5,607/sq.ft.       1
₹ 6,609/sq.ft.       1
₹ 8,818/sq.ft.       1
₹ 7,554/sq.ft.       1
₹ 11,233/sq.ft.      1
₹ 6,641/sq.ft.       1
₹ 7,339/sq.ft.       1
₹ 12,134/sq.ft.      1
₹ 7,167/sq.ft.       1
₹ 8,320/sq.ft.       1
₹ 11,438/sq.ft.      1
₹ 24,963/sq.ft.      1
₹ 15,510/sq.ft.      1
₹ 12,544/sq.ft.      1
₹ 9,783/sq.ft.       1
₹ 14,950/sq.ft.      1
₹ 7,260/sq.ft.       1
₹ 28,101/sq.ft.      1
₹ 8,051/sq.ft.       1
₹ 13,690/sq.ft.      1
₹ 5,788/sq.ft.       1
₹ 13,125/sq.ft.      1
₹ 5,505/sq.ft.       1
₹ 14,598/sq.ft.      1
₹ 11,227/sq.ft.      1
₹ 6,975/sq.ft.       1
₹ 5,887/sq.ft.       1
₹ 13,318/sq.ft.      1
₹ 12,371/sq.ft.      1
₹ 8,769/sq.ft.       1
₹ 11,868/sq.ft.      1
₹ 12,732/sq.ft.      1
₹ 11,338/sq.ft.      1
₹ 12,533/sq.ft.      1
₹ 5,605/sq.ft.       1
₹ 10,449/sq.ft.      1
₹ 11,050/sq.ft.      1
₹ 10,825/sq.ft.      1
₹ 6,369/sq.ft.       1
₹ 14,040/sq.ft.      1
₹ 7,652/sq.ft.       1
₹ 9,933/sq.ft.       1
₹ 4,961/sq.ft.       1
₹ 18,500/sq.ft.      1
₹ 16,050/sq.ft.      1
₹ 12,818/sq.ft.      1
₹ 7,392/sq.ft.       1
₹ 12,627/sq.ft.      1
₹ 7,220/sq.ft.       1
₹ 26,790/sq.ft.      1
₹ 21,360/sq.ft.      1
₹ 16,486/sq.ft.      1
₹ 11,121/sq.ft.      1
₹ 14,871/sq.ft.      1
₹ 5,747/sq.ft.       1
₹ 6,267/sq.ft.       1
₹ 13,837/sq.ft.      1
₹ 11,966/sq.ft.      1
₹ 12,471/sq.ft.      1
₹ 19,285/sq.ft.      1

In [33]:
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 10,000/sq.ft.     19
₹ 8,000/sq.ft.      16
₹ 12,500/sq.ft.     16
₹ 6,666/sq.ft.      13
₹ 5,000/sq.ft.      13
₹ 8,333/sq.ft.      12
₹ 7,500/sq.ft.      12
₹ 6,000/sq.ft.      11
₹ 8,461/sq.ft.       9
₹ 9,000/sq.ft.       8
₹ 7,000/sq.ft.       8
₹ 12,000/sq.ft.      8
₹ 11,111/sq.ft.      7
₹ 6,578/sq.ft.       6
₹ 8,888/sq.ft.       6
₹ 9,230/sq.ft.       6
₹ 8,928/sq.ft.       6
₹ 11,500/sq.ft.      6
₹ 5,500/sq.ft.       6
₹ 7,692/sq.ft.       5
₹ 7,142/sq.ft.       5
₹ 16,000/sq.ft.      5
₹ 6,500/sq.ft.       5
₹ 11,428/sq.ft.      5
₹ 4,666/sq.ft.       5
₹ 4,444/sq.ft.       5
₹ 8,108/sq.ft.       5
₹ 5,384/sq.ft.       5
₹ 5,600/sq.ft.       5
₹ 4,615/sq.ft.       5
₹ 14,242/sq.ft.      5
₹ 7,641/sq.ft.       5
₹ 7,407/sq.ft.       5
₹ 8,205/sq.ft.       5
₹ 8,571/sq.ft.       5
₹ 5,556/sq.ft.       5
₹ 10,714/sq.ft.      5
₹ 7,812/sq.ft.       4
₹ 4,854/sq.ft.       4
₹ 7,317/sq.ft.       4
₹ 13,636/sq.ft.      4
₹ 6,735/sq.ft.       4
₹ 8,358/sq.ft.       4
₹ 8,445/sq.ft.       4
₹ 13,750/sq.ft.      4
₹ 4,500/sq.ft.       4
₹ 6,250/sq.ft.       4
₹ 8,474/sq.ft.       4
₹ 8,784/sq.ft.       4
₹ 4,814/sq.ft.       4
₹ 11,666/sq.ft.      4
₹ 8,139/sq.ft.       4
₹ 10,383/sq.ft.      4
₹ 9,210/sq.ft.       4
₹ 13,913/sq.ft.      4
₹ 7,250/sq.ft.       4
₹ 4,687/sq.ft.       4
₹ 8,484/sq.ft.       4
₹ 8,432/sq.ft.       4
₹ 16,666/sq.ft.      4
₹ 9,822/sq.ft.       4
₹ 5,660/sq.ft.       4
₹ 10,416/sq.ft.      4
₹ 7,496/sq.ft.       4
₹ 7,272/sq.ft.       4
₹ 15,000/sq.ft.      4
₹ 9,090/sq.ft.       4
₹ 8,787/sq.ft.       4
₹ 8,500/sq.ft.       4
₹ 8,043/sq.ft.       4
₹ 8,163/sq.ft.       4
₹ 15,384/sq.ft.      4
₹ 14,418/sq.ft.      4
₹ 16,969/sq.ft.      3
₹ 6,476/sq.ft.       3
₹ 5,325/sq.ft.       3
₹ 13,392/sq.ft.      3
₹ 8,389/sq.ft.       3
₹ 5,878/sq.ft.       3
₹ 16,470/sq.ft.      3
₹ 8,750/sq.ft.       3
₹ 7,948/sq.ft.       3
₹ 7,954/sq.ft.       3
₹ 9,972/sq.ft.       3
₹ 10,638/sq.ft.      3
₹ 6,404/sq.ft.       3
₹ 8,215/sq.ft.       3
₹ 8,078/sq.ft.       3
₹ 14,254/sq.ft.      3
₹ 6,818/sq.ft.       3
₹ 8,222/sq.ft.       3
₹ 10,500/sq.ft.      3
₹ 6,387/sq.ft.       3
₹ 11,000/sq.ft.      3
₹ 7,302/sq.ft.       3
₹ 11,363/sq.ft.      3
₹ 8,080/sq.ft.       3
₹ 7,541/sq.ft.       3
₹ 6,421/sq.ft.       3
₹ 14,430/sq.ft.      3
₹ 5,833/sq.ft.       3
₹ 6,086/sq.ft.       3
₹ 9,011/sq.ft.       3
₹ 7,150/sq.ft.       3
₹ 8,400/sq.ft.       3
₹ 7,586/sq.ft.       3
₹ 5,856/sq.ft.       3
₹ 5,555/sq.ft.       3
₹ 8,532/sq.ft.       3
₹ 7,179/sq.ft.       3
₹ 7,083/sq.ft.       3
₹ 6,593/sq.ft.       3
₹ 8,181/sq.ft.       3
₹ 8,620/sq.ft.       3
₹ 8,606/sq.ft.       3
₹ 5,238/sq.ft.       3
₹ 9,900/sq.ft.       3
₹ 5,397/sq.ft.       3
₹ 5,319/sq.ft.       3
₹ 4,800/sq.ft.       3
₹ 9,500/sq.ft.       3
₹ 6,470/sq.ft.       3
₹ 10,555/sq.ft.      3
₹ 7,467/sq.ft.       3
₹ 7,865/sq.ft.       3
₹ 7,400/sq.ft.       3
₹ 9,473/sq.ft.       3
₹ 5,735/sq.ft.       3
₹ 6,921/sq.ft.       3
₹ 13,000/sq.ft.      3
₹ 6,644/sq.ft.       3
₹ 9,615/sq.ft.       3
₹ 4,820/sq.ft.       3
₹ 14,000/sq.ft.      3
₹ 10,139/sq.ft.      3
₹ 7,549/sq.ft.       3
₹ 4,210/sq.ft.       3
₹ 4,513/sq.ft.       3
₹ 6,542/sq.ft.       3
₹ 8,886/sq.ft.       3
₹ 8,450/sq.ft.       3
₹ 10,204/sq.ft.      3
₹ 7,056/sq.ft.       3
₹ 13,870/sq.ft.      3
₹ 6,667/sq.ft.       3
₹ 4,105/sq.ft.       3
₹ 9,904/sq.ft.       3
₹ 8,148/sq.ft.       3
₹ 7,750/sq.ft.       3
₹ 8,604/sq.ft.       3
₹ 6,178/sq.ft.       2
₹ 9,135/sq.ft.       2
₹ 7,796/sq.ft.       2
₹ 10,476/sq.ft.      2
₹ 5,470/sq.ft.       2
₹ 4,400/sq.ft.       2
₹ 33,198/sq.ft.      2
₹ 7,200/sq.ft.       2
₹ 10,666/sq.ft.      2
₹ 5,189/sq.ft.       2
₹ 5,291/sq.ft.       2
₹ 6,702/sq.ft.       2
₹ 6,616/sq.ft.       2
₹ 15,151/sq.ft.      2
₹ 6,200/sq.ft.       2
₹ 7,846/sq.ft.       2
₹ 7,297/sq.ft.       2
₹ 5,528/sq.ft.       2
₹ 8,903/sq.ft.       2
₹ 6,811/sq.ft.       2
₹ 5,588/sq.ft.       2
₹ 9,128/sq.ft.       2
₹ 11,574/sq.ft.      2
₹ 7,223/sq.ft.       2
₹ 7,608/sq.ft.       2
₹ 6,655/sq.ft.       2
₹ 5,674/sq.ft.       2
₹ 13,343/sq.ft.      2
₹ 14,545/sq.ft.      2
₹ 9,166/sq.ft.       2
₹ 18,000/sq.ft.      2
₹ 4,307/sq.ft.       2
₹ 8,974/sq.ft.       2
₹ 8,670/sq.ft.       2
₹ 8,159/sq.ft.       2
₹ 7,058/sq.ft.       2
₹ 11,715/sq.ft.      2
₹ 7,174/sq.ft.       2
₹ 6,938/sq.ft.       2
₹ 5,671/sq.ft.       2
₹ 19,882/sq.ft.      2
₹ 9,791/sq.ft.       2
₹ 9,620/sq.ft.       2
₹ 6,789/sq.ft.       2
₹ 6,967/sq.ft.       2
₹ 6,024/sq.ft.       2
₹ 5,882/sq.ft.       2
₹ 13,500/sq.ft.      2
₹ 9,909/sq.ft.       2
₹ 9,876/sq.ft.       2
₹ 6,190/sq.ft.       2
₹ 6,206/sq.ft.       2
₹ 15,294/sq.ft.      2
₹ 9,978/sq.ft.       2
₹ 3,695/sq.ft.       2
₹ 11,992/sq.ft.      2
₹ 5,658/sq.ft.       2
₹ 7,758/sq.ft.       2
₹ 7,863/sq.ft.       2
₹ 11,250/sq.ft.      2
₹ 8,504/sq.ft.       2
₹ 7,097/sq.ft.       2
₹ 7,490/sq.ft.       2
₹ 6,076/sq.ft.       2
₹ 15,500/sq.ft.      2
₹ 5,150/sq.ft.       2
₹ 6,111/sq.ft.       2
₹ 7,782/sq.ft.       2
₹ 7,780/sq.ft.       2
₹ 5,111/sq.ft.       2
₹ 5,786/sq.ft.       2
₹ 6,985/sq.ft.       2
₹ 12,777/sq.ft.      2
₹ 8,517/sq.ft.       2
₹ 9,452/sq.ft.       2
₹ 6,927/sq.ft.       2
₹ 11,724/sq.ft.      2
₹ 6,377/sq.ft.       2
₹ 10,531/sq.ft.      2
₹ 5,038/sq.ft.       2
₹ 5,797/sq.ft.       2
₹ 11,627/sq.ft.      2
₹ 6,569/sq.ft.       2
₹ 11,529/sq.ft.      2
₹ 6,217/sq.ft.       2
₹ 9,062/sq.ft.       2
₹ 9,449/sq.ft.       2
₹ 8,053/sq.ft.       2
₹ 8,618/sq.ft.       2
₹ 6,686/sq.ft.       2
₹ 8,972/sq.ft.       2
₹ 7,585/sq.ft.       2
₹ 10,601/sq.ft.      2
₹ 6,510/sq.ft.       2
₹ 41,245/sq.ft.      2
₹ 9,851/sq.ft.       2
₹ 8,075/sq.ft.       2
₹ 7,727/sq.ft.       2
₹ 15,998/sq.ft.      2
₹ 11,700/sq.ft.      2
₹ 6,551/sq.ft.       2
₹ 9,677/sq.ft.       2
₹ 8,720/sq.ft.       2
₹ 6,318/sq.ft.       2
₹ 6,983/sq.ft.       2
₹ 6,739/sq.ft.       2
₹ 6,325/sq.ft.       2
₹ 6,061/sq.ft.       2
₹ 6,429/sq.ft.       2
₹ 5,100/sq.ft.       2
₹ 5,517/sq.ft.       2
₹ 9,025/sq.ft.       2
₹ 6,373/sq.ft.       2
₹ 18,271/sq.ft.      2
₹ 8,252/sq.ft.       2
₹ 16,985/sq.ft.      2
₹ 6,422/sq.ft.       2
₹ 4,909/sq.ft.       2
₹ 8,897/sq.ft.       2
₹ 8,609/sq.ft.       2
₹ 8,524/sq.ft.       2
₹ 9,600/sq.ft.       2
₹ 7,574/sq.ft.       2
₹ 7,225/sq.ft.       2
₹ 9,286/sq.ft.       2
₹ 8,006/sq.ft.       2
₹ 17,619/sq.ft.      2
₹ 8,206/sq.ft.       2
₹ 6,597/sq.ft.       2
₹ 18,181/sq.ft.      2
₹ 4,271/sq.ft.       2
₹ 14,257/sq.ft.      2
₹ 9,333/sq.ft.       2
₹ 14,214/sq.ft.      2
₹ 7,248/sq.ft.       2
₹ 10,603/sq.ft.      2
₹ 7,391/sq.ft.       2
₹ 16,960/sq.ft.      2
₹ 11,516/sq.ft.      2
₹ 13,769/sq.ft.      2
₹ 6,428/sq.ft.       2
₹ 58/sq.ft.          2
₹ 5,463/sq.ft.       2
₹ 10,370/sq.ft.      2
₹ 4,000/sq.ft.       2
₹ 5,899/sq.ft.       2
₹ 11,333/sq.ft.      2
₹ 9,182/sq.ft.       2
₹ 12,782/sq.ft.      2
₹ 8,072/sq.ft.       2
₹ 14,583/sq.ft.      2
₹ 9,259/sq.ft.       2
₹ 10,384/sq.ft.      2
₹ 10,526/sq.ft.      2
₹ 8,582/sq.ft.       2
₹ 8,310/sq.ft.       2
₹ 7,530/sq.ft.       2
₹ 5,405/sq.ft.       2
₹ 11,755/sq.ft.      2
₹ 9,146/sq.ft.       2
₹ 7,396/sq.ft.       2
₹ 4,327/sq.ft.       2
₹ 15,263/sq.ft.      2
₹ 16,747/sq.ft.      2
₹ 8,290/sq.ft.       2
₹ 8,519/sq.ft.       2
₹ 3,911/sq.ft.       2
₹ 6,333/sq.ft.       2
₹ 6,315/sq.ft.       2
₹ 7,631/sq.ft.       2
₹ 11,726/sq.ft.      2
₹ 9,263/sq.ft.       2
₹ 6,189/sq.ft.       2
₹ 13,281/sq.ft.      2
₹ 7,825/sq.ft.       2
₹ 13,224/sq.ft.      2
₹ 9,022/sq.ft.       2
₹ 12,012/sq.ft.      2
₹ 7,185/sq.ft.       2
₹ 14,478/sq.ft.      2
₹ 4,651/sq.ft.       2
₹ 14,800/sq.ft.      2
₹ 8,521/sq.ft.       2
₹ 11,028/sq.ft.      2
₹ 6,134/sq.ft.       2
₹ 16,858/sq.ft.      2
₹ 8,166/sq.ft.       2
₹ 9,027/sq.ft.       2
₹ 6,420/sq.ft.       2
₹ 10,018/sq.ft.      2
₹ 14,237/sq.ft.      2
₹ 8,433/sq.ft.       2
₹ 20,687/sq.ft.      2
₹ 12,212/sq.ft.      2
₹ 13,108/sq.ft.      2
₹ 15,551/sq.ft.      2
₹ 15,416/sq.ft.      2
₹ 5,980/sq.ft.       2
₹ 5,828/sq.ft.       2
₹ 8,518/sq.ft.       2
₹ 6,588/sq.ft.       2
₹ 8,756/sq.ft.       2
₹ 9,482/sq.ft.       2
₹ 5,599/sq.ft.       2
₹ 4,745/sq.ft.       2
₹ 6,382/sq.ft.       2
₹ 14,683/sq.ft.      2
₹ 14,303/sq.ft.      2
₹ 11,505/sq.ft.      2
₹ 5,177/sq.ft.       2
₹ 8,305/sq.ft.       2
₹ 9,589/sq.ft.       2
₹ 5,564/sq.ft.       2
₹ 6,243/sq.ft.       2
₹ 5,681/sq.ft.       2
₹ 7,884/sq.ft.       2
₹ 13,383/sq.ft.      2
₹ 6,053/sq.ft.       2
₹ 4,856/sq.ft.       2
₹ 5,056/sq.ft.       2
₹ 5,641/sq.ft.       2
₹ 5,982/sq.ft.       2
₹ 8,410/sq.ft.       2
₹ 10,516/sq.ft.      2
₹ 10,936/sq.ft.      2
₹ 7,945/sq.ft.       2
₹ 6,049/sq.ft.       2
₹ 8,024/sq.ft.       2
₹ 6,896/sq.ft.       2
₹ 6,153/sq.ft.       2
₹ 9,306/sq.ft.       2
₹ 16,363/sq.ft.      2
₹ 13,709/sq.ft.      2
₹ 8,457/sq.ft.       2
₹ 5,454/sq.ft.       2
₹ 8,424/sq.ft.       2
₹ 7,987/sq.ft.       2
₹ 9,020/sq.ft.       2
₹ 8,412/sq.ft.       2
₹ 8,835/sq.ft.       2
₹ 4,761/sq.ft.       2
₹ 6,465/sq.ft.       2
₹ 6,679/sq.ft.       2
₹ 6,141/sq.ft.       2
₹ 8,376/sq.ft.       2
₹ 8,536/sq.ft.       2
₹ 19,000/sq.ft.      2
₹ 8,324/sq.ft.       2
₹ 14,285/sq.ft.      2
₹ 6,353/sq.ft.       2
₹ 6,406/sq.ft.       2
₹ 6,839/sq.ft.       2
₹ 7,716/sq.ft.       2
₹ 9,743/sq.ft.       2
₹ 5,839/sq.ft.       2
₹ 11,765/sq.ft.      2
₹ 17,039/sq.ft.      2
₹ 8,846/sq.ft.       2
₹ 10,599/sq.ft.      2
₹ 6,338/sq.ft.       2
₹ 8,035/sq.ft.       2
₹ 8,036/sq.ft.       2
₹ 8,611/sq.ft.       2
₹ 14,785/sq.ft.      2
₹ 12,022/sq.ft.      2
₹ 13,270/sq.ft.      2
₹ 19,767/sq.ft.      2
₹ 7,765/sq.ft.       2
₹ 6,402/sq.ft.       2
₹ 9,950/sq.ft.       2
₹ 10,553/sq.ft.      2
₹ 9,742/sq.ft.       2
₹ 13,076/sq.ft.      2
₹ 6,987/sq.ft.       2
₹ 5,744/sq.ft.       2
₹ 8,294/sq.ft.       2
₹ 3,477/sq.ft.       2
₹ 8,814/sq.ft.       2
₹ 8,031/sq.ft.       2
₹ 9,550/sq.ft.       2
₹ 8,237/sq.ft.       2
₹ 14,615/sq.ft.      2
₹ 7,610/sq.ft.       2
₹ 7,350/sq.ft.       2
₹ 9,074/sq.ft.       2
₹ 7,908/sq.ft.       2
₹ 9,007/sq.ft.       2
₹ 8,733/sq.ft.       2
₹ 9,672/sq.ft.       2
₹ 9,797/sq.ft.       2
₹ 9,922/sq.ft.       2
₹ 7,359/sq.ft.       2
₹ 5,521/sq.ft.       2
₹ 6,812/sq.ft.       2
₹ 5,128/sq.ft.       2
₹ 11,727/sq.ft.      2
₹ 10,489/sq.ft.      2
₹ 15,195/sq.ft.      2
₹ 5,929/sq.ft.       2
₹ 8,283/sq.ft.       2
₹ 8,411/sq.ft.       2
₹ 8,834/sq.ft.       2
₹ 6,692/sq.ft.       2
₹ 5,252/sq.ft.       2
₹ 13,928/sq.ft.      2
₹ 7,850/sq.ft.       2
₹ 7,817/sq.ft.       2
₹ 9,565/sq.ft.       2
₹ 15,454/sq.ft.      2
₹ 6,571/sq.ft.       2
₹ 6,774/sq.ft.       2
₹ 11,412/sq.ft.      2
₹ 4,857/sq.ft.       2
₹ 8,632/sq.ft.       2
₹ 5,513/sq.ft.       2
₹ 9,139/sq.ft.       2
₹ 11,336/sq.ft.      2
₹ 6,029/sq.ft.       2
₹ 10,545/sq.ft.      2
₹ 6,313/sq.ft.       2
₹ 19,747/sq.ft.      2
₹ 7,878/sq.ft.       2
₹ 9,105/sq.ft.       2
₹ 10,699/sq.ft.      2
₹ 7,751/sq.ft.       2
₹ 5,725/sq.ft.       2
₹ 9,433/sq.ft.       2
₹ 10,651/sq.ft.      2
₹ 5,808/sq.ft.       2
₹ 4,080/sq.ft.       2
₹ 10,237/sq.ft.      2
₹ 12,444/sq.ft.      2
₹ 5,896/sq.ft.       2
₹ 5,424/sq.ft.       2
₹ 7,857/sq.ft.       2
₹ 8,600/sq.ft.       2
₹ 8,453/sq.ft.       2
₹ 13,430/sq.ft.      2
₹ 16,608/sq.ft.      2
₹ 5,649/sq.ft.       2
₹ 21,538/sq.ft.      2
₹ 9,854/sq.ft.       2
₹ 11,125/sq.ft.      2
₹ 5,820/sq.ft.       2
₹ 6,254/sq.ft.       2
₹ 6,825/sq.ft.       2
₹ 6,647/sq.ft.       2
₹ 9,642/sq.ft.       2
₹ 11,694/sq.ft.      2
₹ 5,614/sq.ft.       2
₹ 12,222/sq.ft.      2
₹ 10,596/sq.ft.      2
₹ 7,014/sq.ft.       2
₹ 5,825/sq.ft.       2
₹ 8,100/sq.ft.       2
₹ 6,455/sq.ft.       2
₹ 8,947/sq.ft.       2
₹ 5,683/sq.ft.       2
₹ 7,449/sq.ft.       2
₹ 13,991/sq.ft.      2
₹ 8,279/sq.ft.       2
₹ 200,000/sq.ft.     2
₹ 6,538/sq.ft.       2
₹ 6,950/sq.ft.       2
₹ 5,714/sq.ft.       2
₹ 7,627/sq.ft.       2
₹ 6,506/sq.ft.       2
₹ 6,722/sq.ft.       2
₹ 12,250/sq.ft.      2
₹ 13,333/sq.ft.      2
₹ 6,859/sq.ft.       2
₹ 7,234/sq.ft.       2
₹ 6,129/sq.ft.       2
₹ 4,723/sq.ft.       2
₹ 4,818/sq.ft.       2
₹ 4,200/sq.ft.       2
₹ 6,361/sq.ft.       2
₹ 6,493/sq.ft.       2
₹ 18,518/sq.ft.      2
₹ 6,209/sq.ft.       2
₹ 5,284/sq.ft.       2
₹ 5,789/sq.ft.       1
₹ 50,000/sq.ft.      1
₹ 5,367/sq.ft.       1
₹ 4,596/sq.ft.       1
₹ 4,033/sq.ft.       1
₹ 4,879/sq.ft.       1
₹ 6,505/sq.ft.       1
₹ 6,761/sq.ft.       1
₹ 4,700/sq.ft.       1
₹ 12,700/sq.ft.      1
₹ 5,257/sq.ft.       1
₹ 6,064/sq.ft.       1
₹ 17,548/sq.ft.      1
₹ 5,576/sq.ft.       1
₹ 4,657/sq.ft.       1
₹ 7,079/sq.ft.       1
₹ 12,110/sq.ft.      1
₹ 11,739/sq.ft.      1
₹ 14,074/sq.ft.      1
₹ 7,146/sq.ft.       1
₹ 12,400/sq.ft.      1
₹ 13,875/sq.ft.      1
₹ 13,846/sq.ft.      1
₹ 6,708/sq.ft.       1
₹ 6,580/sq.ft.       1
₹ 6,514/sq.ft.       1
₹ 13,929/sq.ft.      1
₹ 17,285/sq.ft.      1
₹ 6,819/sq.ft.       1
₹ 9,133/sq.ft.       1
₹ 12,325/sq.ft.      1
₹ 5,541/sq.ft.       1
₹ 14,557/sq.ft.      1
₹ 13,878/sq.ft.      1
₹ 13,888/sq.ft.      1
₹ 9,036/sq.ft.       1
₹ 9,980/sq.ft.       1
₹ 7,065/sq.ft.       1
₹ 5,499/sq.ft.       1
₹ 4,864/sq.ft.       1
₹ 13,528/sq.ft.      1
₹ 9,622/sq.ft.       1
₹ 9,051/sq.ft.       1
₹ 4,022/sq.ft.       1
₹ 7,437/sq.ft.       1
₹ 21,013/sq.ft.      1
₹ 6,523/sq.ft.       1
₹ 14,623/sq.ft.      1
₹ 13,725/sq.ft.      1
₹ 6,953/sq.ft.       1
₹ 8,724/sq.ft.       1
₹ 24,211/sq.ft.      1
₹ 20,533/sq.ft.      1
₹ 15,469/sq.ft.      1
₹ 10,761/sq.ft.      1
₹ 10,994/sq.ft.      1
₹ 12,144/sq.ft.      1
₹ 12,127/sq.ft.      1
₹ 14,536/sq.ft.      1
₹ 11,052/sq.ft.      1
₹ 10,953/sq.ft.      1
₹ 9,117/sq.ft.       1
₹ 9,387/sq.ft.       1
₹ 3,935/sq.ft.       1
₹ 11,860/sq.ft.      1
₹ 9,266/sq.ft.       1
₹ 10,334/sq.ft.      1
₹ 16,580/sq.ft.      1
₹ 16,750/sq.ft.      1
₹ 8,839/sq.ft.       1
₹ 8,759/sq.ft.       1
₹ 14,983/sq.ft.      1
₹ 11,914/sq.ft.      1
₹ 12,571/sq.ft.      1
₹ 8,242/sq.ft.       1
₹ 12,169/sq.ft.      1
₹ 17,484/sq.ft.      1
₹ 7,403/sq.ft.       1
₹ 35,483/sq.ft.      1
₹ 6,215/sq.ft.       1
₹ 14,727/sq.ft.      1
₹ 8,679/sq.ft.       1
₹ 14,090/sq.ft.      1
₹ 6,052/sq.ft.       1
₹ 14,987/sq.ft.      1
₹ 6,060/sq.ft.       1
₹ 8,516/sq.ft.       1
₹ 10,028/sq.ft.      1
₹ 15,007/sq.ft.      1
₹ 9,203/sq.ft.       1
₹ 10,178/sq.ft.      1
₹ 4,531/sq.ft.       1
₹ 5,859/sq.ft.       1
₹ 14,068/sq.ft.      1
₹ 7,789/sq.ft.       1
₹ 10,365/sq.ft.      1
₹ 8,172/sq.ft.       1
₹ 10,080/sq.ft.      1
₹ 10,461/sq.ft.      1
₹ 8,646/sq.ft.       1
₹ 10,595/sq.ft.      1
₹ 4,836/sq.ft.       1
₹ 5,004/sq.ft.       1
₹ 13,678/sq.ft.      1
₹ 12,599/sq.ft.      1
₹ 11,358/sq.ft.      1
₹ 5,418/sq.ft.       1
₹ 8,825/sq.ft.       1
₹ 9,850/sq.ft.       1
₹ 10,224/sq.ft.      1
₹ 10,262/sq.ft.      1
₹ 13,671/sq.ft.      1
₹ 8,922/sq.ft.       1
₹ 5,490/sq.ft.       1
₹ 6,242/sq.ft.       1
₹ 11,451/sq.ft.      1
₹ 8,998/sq.ft.       1
₹ 7,096/sq.ft.       1
₹ 14,179/sq.ft.      1
₹ 9,238/sq.ft.       1
₹ 5,930/sq.ft.       1
₹ 8,062/sq.ft.       1
₹ 6,002/sq.ft.       1
₹ 6,846/sq.ft.       1
₹ 6,286/sq.ft.       1
₹ 15,685/sq.ft.      1
₹ 13,758/sq.ft.      1
₹ 8,204/sq.ft.       1
₹ 16,266/sq.ft.      1
₹ 12,658/sq.ft.      1
₹ 13,580/sq.ft.      1
₹ 20,388/sq.ft.      1
₹ 12,846/sq.ft.      1
₹ 14,843/sq.ft.      1
₹ 6,852/sq.ft.       1
₹ 5,762/sq.ft.       1
₹ 15,531/sq.ft.      1
₹ 12,484/sq.ft.      1
₹ 3,953/sq.ft.       1
₹ 4,308/sq.ft.       1
₹ 6,265/sq.ft.       1
₹ 7,116/sq.ft.       1
₹ 10,162/sq.ft.      1
₹ 6,310/sq.ft.       1
₹ 4,370/sq.ft.       1
₹ 12,190/sq.ft.      1
₹ 13,253/sq.ft.      1
₹ 12,152/sq.ft.      1
₹ 15,185/sq.ft.      1
₹ 5,973/sq.ft.       1
₹ 6,453/sq.ft.       1
₹ 7,230/sq.ft.       1
₹ 6,585/sq.ft.       1
₹ 11,686/sq.ft.      1
₹ 13,571/sq.ft.      1
₹ 7,525/sq.ft.       1
₹ 11,218/sq.ft.      1
₹ 8,270/sq.ft.       1
₹ 11,713/sq.ft.      1
₹ 21,577/sq.ft.      1
₹ 10,529/sq.ft.      1
₹ 10,147/sq.ft.      1
₹ 6,227/sq.ft.       1
₹ 10,727/sq.ft.      1
₹ 5,942/sq.ft.       1
₹ 10,037/sq.ft.      1
₹ 8,395/sq.ft.       1
₹ 5,597/sq.ft.       1
₹ 8,916/sq.ft.       1
₹ 8,875/sq.ft.       1
₹ 5,207/sq.ft.       1
₹ 19,174/sq.ft.      1
₹ 7,590/sq.ft.       1
₹ 6,801/sq.ft.       1
₹ 7,734/sq.ft.       1
₹ 4,355/sq.ft.       1
₹ 4,528/sq.ft.       1
₹ 6,961/sq.ft.       1
₹ 7,646/sq.ft.       1
₹ 10,174/sq.ft.      1
₹ 14,177/sq.ft.      1
₹ 5,867/sq.ft.       1
₹ 5,717/sq.ft.       1
₹ 10,841/sq.ft.      1
₹ 11,174/sq.ft.      1
₹ 6,625/sq.ft.       1
₹ 8,793/sq.ft.       1
₹ 13,352/sq.ft.      1
₹ 15,561/sq.ft.      1
₹ 6,530/sq.ft.       1
₹ 11,817/sq.ft.      1
₹ 12,372/sq.ft.      1
₹ 8,708/sq.ft.       1
₹ 9,512/sq.ft.       1
₹ 7,380/sq.ft.       1
₹ 18,126/sq.ft.      1
₹ 7,180/sq.ft.       1
₹ 7,072/sq.ft.       1
₹ 12,047/sq.ft.      1
₹ 9,039/sq.ft.       1
₹ 8,623/sq.ft.       1
₹ 8,704/sq.ft.       1
₹ 9,365/sq.ft.       1
₹ 10,041/sq.ft.      1
₹ 9,627/sq.ft.       1
₹ 10,786/sq.ft.      1
₹ 10,443/sq.ft.      1
₹ 8,580/sq.ft.       1
₹ 14,563/sq.ft.      1
₹ 15,514/sq.ft.      1
₹ 9,528/sq.ft.       1
₹ 6,826/sq.ft.       1
₹ 12,788/sq.ft.      1
₹ 10,567/sq.ft.      1
₹ 11,470/sq.ft.      1
₹ 11,204/sq.ft.      1
₹ 11,294/sq.ft.      1
₹ 15,906/sq.ft.      1
₹ 3,309/sq.ft.       1
₹ 4,193/sq.ft.       1
₹ 9,497/sq.ft.       1
₹ 4,746/sq.ft.       1
₹ 9,052/sq.ft.       1
₹ 8,023/sq.ft.       1
₹ 7,208/sq.ft.       1
₹ 7,443/sq.ft.       1
₹ 9,030/sq.ft.       1
₹ 6,424/sq.ft.       1
₹ 11,489/sq.ft.      1
₹ 9,655/sq.ft.       1
₹ 9,169/sq.ft.       1
₹ 10,799/sq.ft.      1
₹ 12,589/sq.ft.      1
₹ 10,853/sq.ft.      1
₹ 5,531/sq.ft.       1
₹ 6,019/sq.ft.       1
₹ 6,104/sq.ft.       1
₹ 10,954/sq.ft.      1
₹ 6,888/sq.ft.       1
₹ 9,212/sq.ft.       1
₹ 6,661/sq.ft.       1
₹ 15,160/sq.ft.      1
₹ 12,140/sq.ft.      1
₹ 10,814/sq.ft.      1
₹ 13,790/sq.ft.      1
₹ 6,713/sq.ft.       1
₹ 14,079/sq.ft.      1
₹ 12,235/sq.ft.      1
₹ 7,196/sq.ft.       1
₹ 6,932/sq.ft.       1
₹ 12,178/sq.ft.      1
₹ 9,584/sq.ft.       1
₹ 12,813/sq.ft.      1
₹ 11,764/sq.ft.      1
₹ 16,129/sq.ft.      1
₹ 8,553/sq.ft.       1
₹ 10,755/sq.ft.      1
₹ 6,851/sq.ft.       1
₹ 8,256/sq.ft.       1
₹ 5,026/sq.ft.       1
₹ 7,636/sq.ft.       1
₹ 7,928/sq.ft.       1
₹ 9,393/sq.ft.       1
₹ 8,813/sq.ft.       1
₹ 10,465/sq.ft.      1
₹ 9,563/sq.ft.       1
₹ 13,589/sq.ft.      1
₹ 10,645/sq.ft.      1
₹ 8,541/sq.ft.       1
₹ 15,418/sq.ft.      1
₹ 10,901/sq.ft.      1
₹ 6,163/sq.ft.       1
₹ 7,991/sq.ft.       1
₹ 3,152/sq.ft.       1
₹ 14,375/sq.ft.      1
₹ 16,959/sq.ft.      1
₹ 5,422/sq.ft.       1
₹ 5,607/sq.ft.       1
₹ 6,609/sq.ft.       1
₹ 8,818/sq.ft.       1
₹ 7,554/sq.ft.       1
₹ 11,233/sq.ft.      1
₹ 6,641/sq.ft.       1
₹ 7,339/sq.ft.       1
₹ 12,134/sq.ft.      1
₹ 7,167/sq.ft.       1
₹ 8,320/sq.ft.       1
₹ 11,438/sq.ft.      1
₹ 24,963/sq.ft.      1
₹ 15,510/sq.ft.      1
₹ 12,544/sq.ft.      1
₹ 9,783/sq.ft.       1
₹ 14,950/sq.ft.      1
₹ 7,260/sq.ft.       1
₹ 28,101/sq.ft.      1
₹ 8,051/sq.ft.       1
₹ 13,690/sq.ft.      1
₹ 5,788/sq.ft.       1
₹ 13,125/sq.ft.      1
₹ 5,505/sq.ft.       1
₹ 14,598/sq.ft.      1
₹ 11,227/sq.ft.      1
₹ 6,975/sq.ft.       1
₹ 5,887/sq.ft.       1
₹ 13,318/sq.ft.      1
₹ 12,371/sq.ft.      1
₹ 8,769/sq.ft.       1
₹ 11,868/sq.ft.      1
₹ 12,732/sq.ft.      1
₹ 11,338/sq.ft.      1
₹ 12,533/sq.ft.      1
₹ 5,605/sq.ft.       1
₹ 10,449/sq.ft.      1
₹ 11,050/sq.ft.      1
₹ 10,825/sq.ft.      1
₹ 6,369/sq.ft.       1
₹ 14,040/sq.ft.      1
₹ 7,652/sq.ft.       1
₹ 9,933/sq.ft.       1
₹ 4,961/sq.ft.       1
₹ 18,500/sq.ft.      1
₹ 16,050/sq.ft.      1
₹ 12,818/sq.ft.      1
₹ 7,392/sq.ft.       1
₹ 12,627/sq.ft.      1
₹ 7,220/sq.ft.       1
₹ 26,790/sq.ft.      1
₹ 21,360/sq.ft.      1
₹ 16,486/sq.ft.      1
₹ 11,121/sq.ft.      1
₹ 14,871/sq.ft.      1
₹ 5,747/sq.ft.       1
₹ 6,267/sq.ft.       1
₹ 13,837/sq.ft.      1
₹ 11,966/sq.ft.      1
₹ 12,471/sq.ft.      1
₹ 19,285/sq.ft.      1

In [34]:
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 10,000/sq.ft.     19
₹ 8,000/sq.ft.      16
₹ 12,500/sq.ft.     16
₹ 6,666/sq.ft.      13
₹ 5,000/sq.ft.      13
₹ 8,333/sq.ft.      12
₹ 7,500/sq.ft.      12
₹ 6,000/sq.ft.      11
₹ 8,461/sq.ft.       9
₹ 9,000/sq.ft.       8
₹ 7,000/sq.ft.       8
₹ 12,000/sq.ft.      8
₹ 11,111/sq.ft.      7
₹ 6,578/sq.ft.       6
₹ 8,888/sq.ft.       6
₹ 9,230/sq.ft.       6
₹ 8,928/sq.ft.       6
₹ 11,500/sq.ft.      6
₹ 5,500/sq.ft.       6
₹ 7,692/sq.ft.       5
₹ 7,142/sq.ft.       5
₹ 16,000/sq.ft.      5
₹ 6,500/sq.ft.       5
₹ 11,428/sq.ft.      5
₹ 4,666/sq.ft.       5
₹ 4,444/sq.ft.       5
₹ 8,108/sq.ft.       5
₹ 5,384/sq.ft.       5
₹ 5,600/sq.ft.       5
₹ 4,615/sq.ft.       5
₹ 14,242/sq.ft.      5
₹ 7,641/sq.ft.       5
₹ 7,407/sq.ft.       5
₹ 8,205/sq.ft.       5
₹ 8,571/sq.ft.       5
₹ 5,556/sq.ft.       5
₹ 10,714/sq.ft.      5
₹ 7,812/sq.ft.       4
₹ 4,854/sq.ft.       4
₹ 7,317/sq.ft.       4
₹ 13,636/sq.ft.      4
₹ 6,735/sq.ft.       4
₹ 8,358/sq.ft.       4
₹ 8,445/sq.ft.       4
₹ 13,750/sq.ft.      4
₹ 4,500/sq.ft.       4
₹ 6,250/sq.ft.       4
₹ 8,474/sq.ft.       4
₹ 8,784/sq.ft.       4
₹ 4,814/sq.ft.       4
₹ 11,666/sq.ft.      4
₹ 8,139/sq.ft.       4
₹ 10,383/sq.ft.      4
₹ 9,210/sq.ft.       4
₹ 13,913/sq.ft.      4
₹ 7,250/sq.ft.       4
₹ 4,687/sq.ft.       4
₹ 8,484/sq.ft.       4
₹ 8,432/sq.ft.       4
₹ 16,666/sq.ft.      4
₹ 9,822/sq.ft.       4
₹ 5,660/sq.ft.       4
₹ 10,416/sq.ft.      4
₹ 7,496/sq.ft.       4
₹ 7,272/sq.ft.       4
₹ 15,000/sq.ft.      4
₹ 9,090/sq.ft.       4
₹ 8,787/sq.ft.       4
₹ 8,500/sq.ft.       4
₹ 8,043/sq.ft.       4
₹ 8,163/sq.ft.       4
₹ 15,384/sq.ft.      4
₹ 14,418/sq.ft.      4
₹ 16,969/sq.ft.      3
₹ 6,476/sq.ft.       3
₹ 5,325/sq.ft.       3
₹ 13,392/sq.ft.      3
₹ 8,389/sq.ft.       3
₹ 5,878/sq.ft.       3
₹ 16,470/sq.ft.      3
₹ 8,750/sq.ft.       3
₹ 7,948/sq.ft.       3
₹ 7,954/sq.ft.       3
₹ 9,972/sq.ft.       3
₹ 10,638/sq.ft.      3
₹ 6,404/sq.ft.       3
₹ 8,215/sq.ft.       3
₹ 8,078/sq.ft.       3
₹ 14,254/sq.ft.      3
₹ 6,818/sq.ft.       3
₹ 8,222/sq.ft.       3
₹ 10,500/sq.ft.      3
₹ 6,387/sq.ft.       3
₹ 11,000/sq.ft.      3
₹ 7,302/sq.ft.       3
₹ 11,363/sq.ft.      3
₹ 8,080/sq.ft.       3
₹ 7,541/sq.ft.       3
₹ 6,421/sq.ft.       3
₹ 14,430/sq.ft.      3
₹ 5,833/sq.ft.       3
₹ 6,086/sq.ft.       3
₹ 9,011/sq.ft.       3
₹ 7,150/sq.ft.       3
₹ 8,400/sq.ft.       3
₹ 7,586/sq.ft.       3
₹ 5,856/sq.ft.       3
₹ 5,555/sq.ft.       3
₹ 8,532/sq.ft.       3
₹ 7,179/sq.ft.       3
₹ 7,083/sq.ft.       3
₹ 6,593/sq.ft.       3
₹ 8,181/sq.ft.       3
₹ 8,620/sq.ft.       3
₹ 8,606/sq.ft.       3
₹ 5,238/sq.ft.       3
₹ 9,900/sq.ft.       3
₹ 5,397/sq.ft.       3
₹ 5,319/sq.ft.       3
₹ 4,800/sq.ft.       3
₹ 9,500/sq.ft.       3
₹ 6,470/sq.ft.       3
₹ 10,555/sq.ft.      3
₹ 7,467/sq.ft.       3
₹ 7,865/sq.ft.       3
₹ 7,400/sq.ft.       3
₹ 9,473/sq.ft.       3
₹ 5,735/sq.ft.       3
₹ 6,921/sq.ft.       3
₹ 13,000/sq.ft.      3
₹ 6,644/sq.ft.       3
₹ 9,615/sq.ft.       3
₹ 4,820/sq.ft.       3
₹ 14,000/sq.ft.      3
₹ 10,139/sq.ft.      3
₹ 7,549/sq.ft.       3
₹ 4,210/sq.ft.       3
₹ 4,513/sq.ft.       3
₹ 6,542/sq.ft.       3
₹ 8,886/sq.ft.       3
₹ 8,450/sq.ft.       3
₹ 10,204/sq.ft.      3
₹ 7,056/sq.ft.       3
₹ 13,870/sq.ft.      3
₹ 6,667/sq.ft.       3
₹ 4,105/sq.ft.       3
₹ 9,904/sq.ft.       3
₹ 8,148/sq.ft.       3
₹ 7,750/sq.ft.       3
₹ 8,604/sq.ft.       3
₹ 6,178/sq.ft.       2
₹ 9,135/sq.ft.       2
₹ 7,796/sq.ft.       2
₹ 10,476/sq.ft.      2
₹ 5,470/sq.ft.       2
₹ 4,400/sq.ft.       2
₹ 33,198/sq.ft.      2
₹ 7,200/sq.ft.       2
₹ 10,666/sq.ft.      2
₹ 5,189/sq.ft.       2
₹ 5,291/sq.ft.       2
₹ 6,702/sq.ft.       2
₹ 6,616/sq.ft.       2
₹ 15,151/sq.ft.      2
₹ 6,200/sq.ft.       2
₹ 7,846/sq.ft.       2
₹ 7,297/sq.ft.       2
₹ 5,528/sq.ft.       2
₹ 8,903/sq.ft.       2
₹ 6,811/sq.ft.       2
₹ 5,588/sq.ft.       2
₹ 9,128/sq.ft.       2
₹ 11,574/sq.ft.      2
₹ 7,223/sq.ft.       2
₹ 7,608/sq.ft.       2
₹ 6,655/sq.ft.       2
₹ 5,674/sq.ft.       2
₹ 13,343/sq.ft.      2
₹ 14,545/sq.ft.      2
₹ 9,166/sq.ft.       2
₹ 18,000/sq.ft.      2
₹ 4,307/sq.ft.       2
₹ 8,974/sq.ft.       2
₹ 8,670/sq.ft.       2
₹ 8,159/sq.ft.       2
₹ 7,058/sq.ft.       2
₹ 11,715/sq.ft.      2
₹ 7,174/sq.ft.       2
₹ 6,938/sq.ft.       2
₹ 5,671/sq.ft.       2
₹ 19,882/sq.ft.      2
₹ 9,791/sq.ft.       2
₹ 9,620/sq.ft.       2
₹ 6,789/sq.ft.       2
₹ 6,967/sq.ft.       2
₹ 6,024/sq.ft.       2
₹ 5,882/sq.ft.       2
₹ 13,500/sq.ft.      2
₹ 9,909/sq.ft.       2
₹ 9,876/sq.ft.       2
₹ 6,190/sq.ft.       2
₹ 6,206/sq.ft.       2
₹ 15,294/sq.ft.      2
₹ 9,978/sq.ft.       2
₹ 3,695/sq.ft.       2
₹ 11,992/sq.ft.      2
₹ 5,658/sq.ft.       2
₹ 7,758/sq.ft.       2
₹ 7,863/sq.ft.       2
₹ 11,250/sq.ft.      2
₹ 8,504/sq.ft.       2
₹ 7,097/sq.ft.       2
₹ 7,490/sq.ft.       2
₹ 6,076/sq.ft.       2
₹ 15,500/sq.ft.      2
₹ 5,150/sq.ft.       2
₹ 6,111/sq.ft.       2
₹ 7,782/sq.ft.       2
₹ 7,780/sq.ft.       2
₹ 5,111/sq.ft.       2
₹ 5,786/sq.ft.       2
₹ 6,985/sq.ft.       2
₹ 12,777/sq.ft.      2
₹ 8,517/sq.ft.       2
₹ 9,452/sq.ft.       2
₹ 6,927/sq.ft.       2
₹ 11,724/sq.ft.      2
₹ 6,377/sq.ft.       2
₹ 10,531/sq.ft.      2
₹ 5,038/sq.ft.       2
₹ 5,797/sq.ft.       2
₹ 11,627/sq.ft.      2
₹ 6,569/sq.ft.       2
₹ 11,529/sq.ft.      2
₹ 6,217/sq.ft.       2
₹ 9,062/sq.ft.       2
₹ 9,449/sq.ft.       2
₹ 8,053/sq.ft.       2
₹ 8,618/sq.ft.       2
₹ 6,686/sq.ft.       2
₹ 8,972/sq.ft.       2
₹ 7,585/sq.ft.       2
₹ 10,601/sq.ft.      2
₹ 6,510/sq.ft.       2
₹ 41,245/sq.ft.      2
₹ 9,851/sq.ft.       2
₹ 8,075/sq.ft.       2
₹ 7,727/sq.ft.       2
₹ 15,998/sq.ft.      2
₹ 11,700/sq.ft.      2
₹ 6,551/sq.ft.       2
₹ 9,677/sq.ft.       2
₹ 8,720/sq.ft.       2
₹ 6,318/sq.ft.       2
₹ 6,983/sq.ft.       2
₹ 6,739/sq.ft.       2
₹ 6,325/sq.ft.       2
₹ 6,061/sq.ft.       2
₹ 6,429/sq.ft.       2
₹ 5,100/sq.ft.       2
₹ 5,517/sq.ft.       2
₹ 9,025/sq.ft.       2
₹ 6,373/sq.ft.       2
₹ 18,271/sq.ft.      2
₹ 8,252/sq.ft.       2
₹ 16,985/sq.ft.      2
₹ 6,422/sq.ft.       2
₹ 4,909/sq.ft.       2
₹ 8,897/sq.ft.       2
₹ 8,609/sq.ft.       2
₹ 8,524/sq.ft.       2
₹ 9,600/sq.ft.       2
₹ 7,574/sq.ft.       2
₹ 7,225/sq.ft.       2
₹ 9,286/sq.ft.       2
₹ 8,006/sq.ft.       2
₹ 17,619/sq.ft.      2
₹ 8,206/sq.ft.       2
₹ 6,597/sq.ft.       2
₹ 18,181/sq.ft.      2
₹ 4,271/sq.ft.       2
₹ 14,257/sq.ft.      2
₹ 9,333/sq.ft.       2
₹ 14,214/sq.ft.      2
₹ 7,248/sq.ft.       2
₹ 10,603/sq.ft.      2
₹ 7,391/sq.ft.       2
₹ 16,960/sq.ft.      2
₹ 11,516/sq.ft.      2
₹ 13,769/sq.ft.      2
₹ 6,428/sq.ft.       2
₹ 58/sq.ft.          2
₹ 5,463/sq.ft.       2
₹ 10,370/sq.ft.      2
₹ 4,000/sq.ft.       2
₹ 5,899/sq.ft.       2
₹ 11,333/sq.ft.      2
₹ 9,182/sq.ft.       2
₹ 12,782/sq.ft.      2
₹ 8,072/sq.ft.       2
₹ 14,583/sq.ft.      2
₹ 9,259/sq.ft.       2
₹ 10,384/sq.ft.      2
₹ 10,526/sq.ft.      2
₹ 8,582/sq.ft.       2
₹ 8,310/sq.ft.       2
₹ 7,530/sq.ft.       2
₹ 5,405/sq.ft.       2
₹ 11,755/sq.ft.      2
₹ 9,146/sq.ft.       2
₹ 7,396/sq.ft.       2
₹ 4,327/sq.ft.       2
₹ 15,263/sq.ft.      2
₹ 16,747/sq.ft.      2
₹ 8,290/sq.ft.       2
₹ 8,519/sq.ft.       2
₹ 3,911/sq.ft.       2
₹ 6,333/sq.ft.       2
₹ 6,315/sq.ft.       2
₹ 7,631/sq.ft.       2
₹ 11,726/sq.ft.      2
₹ 9,263/sq.ft.       2
₹ 6,189/sq.ft.       2
₹ 13,281/sq.ft.      2
₹ 7,825/sq.ft.       2
₹ 13,224/sq.ft.      2
₹ 9,022/sq.ft.       2
₹ 12,012/sq.ft.      2
₹ 7,185/sq.ft.       2
₹ 14,478/sq.ft.      2
₹ 4,651/sq.ft.       2
₹ 14,800/sq.ft.      2
₹ 8,521/sq.ft.       2
₹ 11,028/sq.ft.      2
₹ 6,134/sq.ft.       2
₹ 16,858/sq.ft.      2
₹ 8,166/sq.ft.       2
₹ 9,027/sq.ft.       2
₹ 6,420/sq.ft.       2
₹ 10,018/sq.ft.      2
₹ 14,237/sq.ft.      2
₹ 8,433/sq.ft.       2
₹ 20,687/sq.ft.      2
₹ 12,212/sq.ft.      2
₹ 13,108/sq.ft.      2
₹ 15,551/sq.ft.      2
₹ 15,416/sq.ft.      2
₹ 5,980/sq.ft.       2
₹ 5,828/sq.ft.       2
₹ 8,518/sq.ft.       2
₹ 6,588/sq.ft.       2
₹ 8,756/sq.ft.       2
₹ 9,482/sq.ft.       2
₹ 5,599/sq.ft.       2
₹ 4,745/sq.ft.       2
₹ 6,382/sq.ft.       2
₹ 14,683/sq.ft.      2
₹ 14,303/sq.ft.      2
₹ 11,505/sq.ft.      2
₹ 5,177/sq.ft.       2
₹ 8,305/sq.ft.       2
₹ 9,589/sq.ft.       2
₹ 5,564/sq.ft.       2
₹ 6,243/sq.ft.       2
₹ 5,681/sq.ft.       2
₹ 7,884/sq.ft.       2
₹ 13,383/sq.ft.      2
₹ 6,053/sq.ft.       2
₹ 4,856/sq.ft.       2
₹ 5,056/sq.ft.       2
₹ 5,641/sq.ft.       2
₹ 5,982/sq.ft.       2
₹ 8,410/sq.ft.       2
₹ 10,516/sq.ft.      2
₹ 10,936/sq.ft.      2
₹ 7,945/sq.ft.       2
₹ 6,049/sq.ft.       2
₹ 8,024/sq.ft.       2
₹ 6,896/sq.ft.       2
₹ 6,153/sq.ft.       2
₹ 9,306/sq.ft.       2
₹ 16,363/sq.ft.      2
₹ 13,709/sq.ft.      2
₹ 8,457/sq.ft.       2
₹ 5,454/sq.ft.       2
₹ 8,424/sq.ft.       2
₹ 7,987/sq.ft.       2
₹ 9,020/sq.ft.       2
₹ 8,412/sq.ft.       2
₹ 8,835/sq.ft.       2
₹ 4,761/sq.ft.       2
₹ 6,465/sq.ft.       2
₹ 6,679/sq.ft.       2
₹ 6,141/sq.ft.       2
₹ 8,376/sq.ft.       2
₹ 8,536/sq.ft.       2
₹ 19,000/sq.ft.      2
₹ 8,324/sq.ft.       2
₹ 14,285/sq.ft.      2
₹ 6,353/sq.ft.       2
₹ 6,406/sq.ft.       2
₹ 6,839/sq.ft.       2
₹ 7,716/sq.ft.       2
₹ 9,743/sq.ft.       2
₹ 5,839/sq.ft.       2
₹ 11,765/sq.ft.      2
₹ 17,039/sq.ft.      2
₹ 8,846/sq.ft.       2
₹ 10,599/sq.ft.      2
₹ 6,338/sq.ft.       2
₹ 8,035/sq.ft.       2
₹ 8,036/sq.ft.       2
₹ 8,611/sq.ft.       2
₹ 14,785/sq.ft.      2
₹ 12,022/sq.ft.      2
₹ 13,270/sq.ft.      2
₹ 19,767/sq.ft.      2
₹ 7,765/sq.ft.       2
₹ 6,402/sq.ft.       2
₹ 9,950/sq.ft.       2
₹ 10,553/sq.ft.      2
₹ 9,742/sq.ft.       2
₹ 13,076/sq.ft.      2
₹ 6,987/sq.ft.       2
₹ 5,744/sq.ft.       2
₹ 8,294/sq.ft.       2
₹ 3,477/sq.ft.       2
₹ 8,814/sq.ft.       2
₹ 8,031/sq.ft.       2
₹ 9,550/sq.ft.       2
₹ 8,237/sq.ft.       2
₹ 14,615/sq.ft.      2
₹ 7,610/sq.ft.       2
₹ 7,350/sq.ft.       2
₹ 9,074/sq.ft.       2
₹ 7,908/sq.ft.       2
₹ 9,007/sq.ft.       2
₹ 8,733/sq.ft.       2
₹ 9,672/sq.ft.       2
₹ 9,797/sq.ft.       2
₹ 9,922/sq.ft.       2
₹ 7,359/sq.ft.       2
₹ 5,521/sq.ft.       2
₹ 6,812/sq.ft.       2
₹ 5,128/sq.ft.       2
₹ 11,727/sq.ft.      2
₹ 10,489/sq.ft.      2
₹ 15,195/sq.ft.      2
₹ 5,929/sq.ft.       2
₹ 8,283/sq.ft.       2
₹ 8,411/sq.ft.       2
₹ 8,834/sq.ft.       2
₹ 6,692/sq.ft.       2
₹ 5,252/sq.ft.       2
₹ 13,928/sq.ft.      2
₹ 7,850/sq.ft.       2
₹ 7,817/sq.ft.       2
₹ 9,565/sq.ft.       2
₹ 15,454/sq.ft.      2
₹ 6,571/sq.ft.       2
₹ 6,774/sq.ft.       2
₹ 11,412/sq.ft.      2
₹ 4,857/sq.ft.       2
₹ 8,632/sq.ft.       2
₹ 5,513/sq.ft.       2
₹ 9,139/sq.ft.       2
₹ 11,336/sq.ft.      2
₹ 6,029/sq.ft.       2
₹ 10,545/sq.ft.      2
₹ 6,313/sq.ft.       2
₹ 19,747/sq.ft.      2
₹ 7,878/sq.ft.       2
₹ 9,105/sq.ft.       2
₹ 10,699/sq.ft.      2
₹ 7,751/sq.ft.       2
₹ 5,725/sq.ft.       2
₹ 9,433/sq.ft.       2
₹ 10,651/sq.ft.      2
₹ 5,808/sq.ft.       2
₹ 4,080/sq.ft.       2
₹ 10,237/sq.ft.      2
₹ 12,444/sq.ft.      2
₹ 5,896/sq.ft.       2
₹ 5,424/sq.ft.       2
₹ 7,857/sq.ft.       2
₹ 8,600/sq.ft.       2
₹ 8,453/sq.ft.       2
₹ 13,430/sq.ft.      2
₹ 16,608/sq.ft.      2
₹ 5,649/sq.ft.       2
₹ 21,538/sq.ft.      2
₹ 9,854/sq.ft.       2
₹ 11,125/sq.ft.      2
₹ 5,820/sq.ft.       2
₹ 6,254/sq.ft.       2
₹ 6,825/sq.ft.       2
₹ 6,647/sq.ft.       2
₹ 9,642/sq.ft.       2
₹ 11,694/sq.ft.      2
₹ 5,614/sq.ft.       2
₹ 12,222/sq.ft.      2
₹ 10,596/sq.ft.      2
₹ 7,014/sq.ft.       2
₹ 5,825/sq.ft.       2
₹ 8,100/sq.ft.       2
₹ 6,455/sq.ft.       2
₹ 8,947/sq.ft.       2
₹ 5,683/sq.ft.       2
₹ 7,449/sq.ft.       2
₹ 13,991/sq.ft.      2
₹ 8,279/sq.ft.       2
₹ 200,000/sq.ft.     2
₹ 6,538/sq.ft.       2
₹ 6,950/sq.ft.       2
₹ 5,714/sq.ft.       2
₹ 7,627/sq.ft.       2
₹ 6,506/sq.ft.       2
₹ 6,722/sq.ft.       2
₹ 12,250/sq.ft.      2
₹ 13,333/sq.ft.      2
₹ 6,859/sq.ft.       2
₹ 7,234/sq.ft.       2
₹ 6,129/sq.ft.       2
₹ 4,723/sq.ft.       2
₹ 4,818/sq.ft.       2
₹ 4,200/sq.ft.       2
₹ 6,361/sq.ft.       2
₹ 6,493/sq.ft.       2
₹ 18,518/sq.ft.      2
₹ 6,209/sq.ft.       2
₹ 5,284/sq.ft.       2
₹ 5,789/sq.ft.       1
₹ 50,000/sq.ft.      1
₹ 5,367/sq.ft.       1
₹ 4,596/sq.ft.       1
₹ 4,033/sq.ft.       1
₹ 4,879/sq.ft.       1
₹ 6,505/sq.ft.       1
₹ 6,761/sq.ft.       1
₹ 4,700/sq.ft.       1
₹ 12,700/sq.ft.      1
₹ 5,257/sq.ft.       1
₹ 6,064/sq.ft.       1
₹ 17,548/sq.ft.      1
₹ 5,576/sq.ft.       1
₹ 4,657/sq.ft.       1
₹ 7,079/sq.ft.       1
₹ 12,110/sq.ft.      1
₹ 11,739/sq.ft.      1
₹ 14,074/sq.ft.      1
₹ 7,146/sq.ft.       1
₹ 12,400/sq.ft.      1
₹ 13,875/sq.ft.      1
₹ 13,846/sq.ft.      1
₹ 6,708/sq.ft.       1
₹ 6,580/sq.ft.       1
₹ 6,514/sq.ft.       1
₹ 13,929/sq.ft.      1
₹ 17,285/sq.ft.      1
₹ 6,819/sq.ft.       1
₹ 9,133/sq.ft.       1
₹ 12,325/sq.ft.      1
₹ 5,541/sq.ft.       1
₹ 14,557/sq.ft.      1
₹ 13,878/sq.ft.      1
₹ 13,888/sq.ft.      1
₹ 9,036/sq.ft.       1
₹ 9,980/sq.ft.       1
₹ 7,065/sq.ft.       1
₹ 5,499/sq.ft.       1
₹ 4,864/sq.ft.       1
₹ 13,528/sq.ft.      1
₹ 9,622/sq.ft.       1
₹ 9,051/sq.ft.       1
₹ 4,022/sq.ft.       1
₹ 7,437/sq.ft.       1
₹ 21,013/sq.ft.      1
₹ 6,523/sq.ft.       1
₹ 14,623/sq.ft.      1
₹ 13,725/sq.ft.      1
₹ 6,953/sq.ft.       1
₹ 8,724/sq.ft.       1
₹ 24,211/sq.ft.      1
₹ 20,533/sq.ft.      1
₹ 15,469/sq.ft.      1
₹ 10,761/sq.ft.      1
₹ 10,994/sq.ft.      1
₹ 12,144/sq.ft.      1
₹ 12,127/sq.ft.      1
₹ 14,536/sq.ft.      1
₹ 11,052/sq.ft.      1
₹ 10,953/sq.ft.      1
₹ 9,117/sq.ft.       1
₹ 9,387/sq.ft.       1
₹ 3,935/sq.ft.       1
₹ 11,860/sq.ft.      1
₹ 9,266/sq.ft.       1
₹ 10,334/sq.ft.      1
₹ 16,580/sq.ft.      1
₹ 16,750/sq.ft.      1
₹ 8,839/sq.ft.       1
₹ 8,759/sq.ft.       1
₹ 14,983/sq.ft.      1
₹ 11,914/sq.ft.      1
₹ 12,571/sq.ft.      1
₹ 8,242/sq.ft.       1
₹ 12,169/sq.ft.      1
₹ 17,484/sq.ft.      1
₹ 7,403/sq.ft.       1
₹ 35,483/sq.ft.      1
₹ 6,215/sq.ft.       1
₹ 14,727/sq.ft.      1
₹ 8,679/sq.ft.       1
₹ 14,090/sq.ft.      1
₹ 6,052/sq.ft.       1
₹ 14,987/sq.ft.      1
₹ 6,060/sq.ft.       1
₹ 8,516/sq.ft.       1
₹ 10,028/sq.ft.      1
₹ 15,007/sq.ft.      1
₹ 9,203/sq.ft.       1
₹ 10,178/sq.ft.      1
₹ 4,531/sq.ft.       1
₹ 5,859/sq.ft.       1
₹ 14,068/sq.ft.      1
₹ 7,789/sq.ft.       1
₹ 10,365/sq.ft.      1
₹ 8,172/sq.ft.       1
₹ 10,080/sq.ft.      1
₹ 10,461/sq.ft.      1
₹ 8,646/sq.ft.       1
₹ 10,595/sq.ft.      1
₹ 4,836/sq.ft.       1
₹ 5,004/sq.ft.       1
₹ 13,678/sq.ft.      1
₹ 12,599/sq.ft.      1
₹ 11,358/sq.ft.      1
₹ 5,418/sq.ft.       1
₹ 8,825/sq.ft.       1
₹ 9,850/sq.ft.       1
₹ 10,224/sq.ft.      1
₹ 10,262/sq.ft.      1
₹ 13,671/sq.ft.      1
₹ 8,922/sq.ft.       1
₹ 5,490/sq.ft.       1
₹ 6,242/sq.ft.       1
₹ 11,451/sq.ft.      1
₹ 8,998/sq.ft.       1
₹ 7,096/sq.ft.       1
₹ 14,179/sq.ft.      1
₹ 9,238/sq.ft.       1
₹ 5,930/sq.ft.       1
₹ 8,062/sq.ft.       1
₹ 6,002/sq.ft.       1
₹ 6,846/sq.ft.       1
₹ 6,286/sq.ft.       1
₹ 15,685/sq.ft.      1
₹ 13,758/sq.ft.      1
₹ 8,204/sq.ft.       1
₹ 16,266/sq.ft.      1
₹ 12,658/sq.ft.      1
₹ 13,580/sq.ft.      1
₹ 20,388/sq.ft.      1
₹ 12,846/sq.ft.      1
₹ 14,843/sq.ft.      1
₹ 6,852/sq.ft.       1
₹ 5,762/sq.ft.       1
₹ 15,531/sq.ft.      1
₹ 12,484/sq.ft.      1
₹ 3,953/sq.ft.       1
₹ 4,308/sq.ft.       1
₹ 6,265/sq.ft.       1
₹ 7,116/sq.ft.       1
₹ 10,162/sq.ft.      1
₹ 6,310/sq.ft.       1
₹ 4,370/sq.ft.       1
₹ 12,190/sq.ft.      1
₹ 13,253/sq.ft.      1
₹ 12,152/sq.ft.      1
₹ 15,185/sq.ft.      1
₹ 5,973/sq.ft.       1
₹ 6,453/sq.ft.       1
₹ 7,230/sq.ft.       1
₹ 6,585/sq.ft.       1
₹ 11,686/sq.ft.      1
₹ 13,571/sq.ft.      1
₹ 7,525/sq.ft.       1
₹ 11,218/sq.ft.      1
₹ 8,270/sq.ft.       1
₹ 11,713/sq.ft.      1
₹ 21,577/sq.ft.      1
₹ 10,529/sq.ft.      1
₹ 10,147/sq.ft.      1
₹ 6,227/sq.ft.       1
₹ 10,727/sq.ft.      1
₹ 5,942/sq.ft.       1
₹ 10,037/sq.ft.      1
₹ 8,395/sq.ft.       1
₹ 5,597/sq.ft.       1
₹ 8,916/sq.ft.       1
₹ 8,875/sq.ft.       1
₹ 5,207/sq.ft.       1
₹ 19,174/sq.ft.      1
₹ 7,590/sq.ft.       1
₹ 6,801/sq.ft.       1
₹ 7,734/sq.ft.       1
₹ 4,355/sq.ft.       1
₹ 4,528/sq.ft.       1
₹ 6,961/sq.ft.       1
₹ 7,646/sq.ft.       1
₹ 10,174/sq.ft.      1
₹ 14,177/sq.ft.      1
₹ 5,867/sq.ft.       1
₹ 5,717/sq.ft.       1
₹ 10,841/sq.ft.      1
₹ 11,174/sq.ft.      1
₹ 6,625/sq.ft.       1
₹ 8,793/sq.ft.       1
₹ 13,352/sq.ft.      1
₹ 15,561/sq.ft.      1
₹ 6,530/sq.ft.       1
₹ 11,817/sq.ft.      1
₹ 12,372/sq.ft.      1
₹ 8,708/sq.ft.       1
₹ 9,512/sq.ft.       1
₹ 7,380/sq.ft.       1
₹ 18,126/sq.ft.      1
₹ 7,180/sq.ft.       1
₹ 7,072/sq.ft.       1
₹ 12,047/sq.ft.      1
₹ 9,039/sq.ft.       1
₹ 8,623/sq.ft.       1
₹ 8,704/sq.ft.       1
₹ 9,365/sq.ft.       1
₹ 10,041/sq.ft.      1
₹ 9,627/sq.ft.       1
₹ 10,786/sq.ft.      1
₹ 10,443/sq.ft.      1
₹ 8,580/sq.ft.       1
₹ 14,563/sq.ft.      1
₹ 15,514/sq.ft.      1
₹ 9,528/sq.ft.       1
₹ 6,826/sq.ft.       1
₹ 12,788/sq.ft.      1
₹ 10,567/sq.ft.      1
₹ 11,470/sq.ft.      1
₹ 11,204/sq.ft.      1
₹ 11,294/sq.ft.      1
₹ 15,906/sq.ft.      1
₹ 3,309/sq.ft.       1
₹ 4,193/sq.ft.       1
₹ 9,497/sq.ft.       1
₹ 4,746/sq.ft.       1
₹ 9,052/sq.ft.       1
₹ 8,023/sq.ft.       1
₹ 7,208/sq.ft.       1
₹ 7,443/sq.ft.       1
₹ 9,030/sq.ft.       1
₹ 6,424/sq.ft.       1
₹ 11,489/sq.ft.      1
₹ 9,655/sq.ft.       1
₹ 9,169/sq.ft.       1
₹ 10,799/sq.ft.      1
₹ 12,589/sq.ft.      1
₹ 10,853/sq.ft.      1
₹ 5,531/sq.ft.       1
₹ 6,019/sq.ft.       1
₹ 6,104/sq.ft.       1
₹ 10,954/sq.ft.      1
₹ 6,888/sq.ft.       1
₹ 9,212/sq.ft.       1
₹ 6,661/sq.ft.       1
₹ 15,160/sq.ft.      1
₹ 12,140/sq.ft.      1
₹ 10,814/sq.ft.      1
₹ 13,790/sq.ft.      1
₹ 6,713/sq.ft.       1
₹ 14,079/sq.ft.      1
₹ 12,235/sq.ft.      1
₹ 7,196/sq.ft.       1
₹ 6,932/sq.ft.       1
₹ 12,178/sq.ft.      1
₹ 9,584/sq.ft.       1
₹ 12,813/sq.ft.      1
₹ 11,764/sq.ft.      1
₹ 16,129/sq.ft.      1
₹ 8,553/sq.ft.       1
₹ 10,755/sq.ft.      1
₹ 6,851/sq.ft.       1
₹ 8,256/sq.ft.       1
₹ 5,026/sq.ft.       1
₹ 7,636/sq.ft.       1
₹ 7,928/sq.ft.       1
₹ 9,393/sq.ft.       1
₹ 8,813/sq.ft.       1
₹ 10,465/sq.ft.      1
₹ 9,563/sq.ft.       1
₹ 13,589/sq.ft.      1
₹ 10,645/sq.ft.      1
₹ 8,541/sq.ft.       1
₹ 15,418/sq.ft.      1
₹ 10,901/sq.ft.      1
₹ 6,163/sq.ft.       1
₹ 7,991/sq.ft.       1
₹ 3,152/sq.ft.       1
₹ 14,375/sq.ft.      1
₹ 16,959/sq.ft.      1
₹ 5,422/sq.ft.       1
₹ 5,607/sq.ft.       1
₹ 6,609/sq.ft.       1
₹ 8,818/sq.ft.       1
₹ 7,554/sq.ft.       1
₹ 11,233/sq.ft.      1
₹ 6,641/sq.ft.       1
₹ 7,339/sq.ft.       1
₹ 12,134/sq.ft.      1
₹ 7,167/sq.ft.       1
₹ 8,320/sq.ft.       1
₹ 11,438/sq.ft.      1
₹ 24,963/sq.ft.      1
₹ 15,510/sq.ft.      1
₹ 12,544/sq.ft.      1
₹ 9,783/sq.ft.       1
₹ 14,950/sq.ft.      1
₹ 7,260/sq.ft.       1
₹ 28,101/sq.ft.      1
₹ 8,051/sq.ft.       1
₹ 13,690/sq.ft.      1
₹ 5,788/sq.ft.       1
₹ 13,125/sq.ft.      1
₹ 5,505/sq.ft.       1
₹ 14,598/sq.ft.      1
₹ 11,227/sq.ft.      1
₹ 6,975/sq.ft.       1
₹ 5,887/sq.ft.       1
₹ 13,318/sq.ft.      1
₹ 12,371/sq.ft.      1
₹ 8,769/sq.ft.       1
₹ 11,868/sq.ft.      1
₹ 12,732/sq.ft.      1
₹ 11,338/sq.ft.      1
₹ 12,533/sq.ft.      1
₹ 5,605/sq.ft.       1
₹ 10,449/sq.ft.      1
₹ 11,050/sq.ft.      1
₹ 10,825/sq.ft.      1
₹ 6,369/sq.ft.       1
₹ 14,040/sq.ft.      1
₹ 7,652/sq.ft.       1
₹ 9,933/sq.ft.       1
₹ 4,961/sq.ft.       1
₹ 18,500/sq.ft.      1
₹ 16,050/sq.ft.      1
₹ 12,818/sq.ft.      1
₹ 7,392/sq.ft.       1
₹ 12,627/sq.ft.      1
₹ 7,220/sq.ft.       1
₹ 26,790/sq.ft.      1
₹ 21,360/sq.ft.      1
₹ 16,486/sq.ft.      1
₹ 11,121/sq.ft.      1
₹ 14,871/sq.ft.      1
₹ 5,747/sq.ft.       1
₹ 6,267/sq.ft.       1
₹ 13,837/sq.ft.      1
₹ 11,966/sq.ft.      1
₹ 12,471/sq.ft.      1
₹ 19,285/sq.ft.      1

In [35]:
df['price_per_sqft']=='4/sq.ft.'

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
26      False
27      False
28      False
29      False
30      False
31      False
32      False
33      False
34      False
35      False
36      False
37      False
38      False
39      False
40      False
41      False
42      False
43      False
44      False
45      False
46      False
47      False
48      False
49      False
50      False
51      False
52      False
53      False
54      False
55      False
56      False
57      False
58      False
59      False
60      False
61      False
62      False
63      False
64      False
65      False
66      False
67      False
68      False
69      False
70      False
71      False
72      False
73      False
74      False
75      False
76      False
77      False
78      False
79      False
80      False
81      False
82      False
83      False
84      False
85      False
86      False
87      False
88      False
89      False
90      False
91      False
92      False
93      False
94      False
95      False
96      False
97      False
98      False
99      False
100     False
101     False
102     False
103     False
104     False
105     False
106     False
107     False
108     False
109     False
110     False
111     False
112     False
113     False
114     False
115     False
116     False
117     False
118     False
119     False
120     False
121     False
122     False
123     False
124     False
125     False
126     False
127     False
128     False
129     False
130     False
131     False
132     False
133     False
134     False
135     False
136     False
137     False
138     False
139     False
140     False
141     False
142     False
143     False
144     False
145     False
146     False
147     False
148     False
149     False
150     False
151     False
152     False
153     False
154     False
155     False
156     False
157     False
158     False
159     False
160     False
161     False
162     False
163     False
164     False
165     False
166     False
167     False
168     False
169     False
170     False
171     False
172     False
173     False
174     False
175     False
176     False
177     False
178     False
179     False
180     False
181     False
182     False
183     False
184     False
185     False
186     False
187     False
188     False
189     False
190     False
191     False
192     False
193     False
194     False
195     False
196     False
197     False
198     False
199     False
200     False
201     False
202     False
203     False
204     False
205     False
206     False
207     False
208     False
209     False
210     False
211     False
212     False
213     False
214     False
215     False
216     False
217     False
218     False
219     False
220     False
221     False
222     False
223     False
224     False
225     False
226     False
227     False
228     False
229     False
230     False
231     False
232     False
233     False
234     False
235     False
236     False
237     False
238     False
239     False
240     False
241     False
242     False
243     False
244     False
245     False
246     False
247     False
248     False
249     False
250     False
251     False
252     False
253     False
254     False
255     False
256     False
257     False
258     False
259     False
260     False
261     False
262     False
263     False
264     False
265     False
266     False
267     False
268     False
269     False
270     False
271     False
272     False
273     False
274     False
275     False
276     False
277     False
278     False
279     False
280     False
281     False
282     False
283     False
284     False
285     False
286     False
287     False
288     False
289     False
290     False
291     False
292     False
293     False
294     False
295     False
296     False
297     False
298     False
299     False
300     False
301     False
302     False
303     False
304     False
305     False
306     False
307     False
308     False
309     False
310     False
311     False
312     False
313     False
314     False
315     False
316     False
317     False
318     False
319     False
320     False
321     False
322     False
323     False
324     False
325     False
326     False
327     False
328     False
329     False
330     False
331     False
332     False
333     False
334     False
335     False
336     False
337     False
338     False
339     False
340     False
341     False
342     False
343     False
344     False
345     False
346     False
347     False
348     False
349     False
350     False
351     False
352     False
353     False
354     False
355     False
356     False
357     False
358     False
359     False
360     False
361     False
362     False
363     False
364     False
365     False
366     False
367     False
368     False
369     False
370     False
371     False
372     False
373     False
374     False
375     False
376     False
377     False
378     False
379     False
380     False
381     False
382     False
383     False
384     False
385     False
386     False
387     False
388     False
389     False
390     False
391     False
392     False
393     False
394     False
395     False
396     False
397     False
398     False
399     False
400     False
401     False
402     False
403     False
404     False
405     False
406     False
407     False
408     False
409     False
410     False
411     False
412     False
413     False
414     False
415     False
416     False
417     False
418     False
419     False
420     False
421     False
422     False
423     False
424     False
425     False
426     False
427     False
428     False
429     False
430     False
431     False
432     False
433     False
434     False
435     False
436     False
437     False
438     False
439     False
440     False
441     False
442     False
443     False
444     False
445     False
446     False
447     False
448     False
449     False
450     False
451     False
452     False
453     False
454     False
455     False
456     False
457     False
458     False
459     False
460     False
461     False
462     False
463     False
464     False
465     False
466     False
467     False
468     False
469     False
470     False
471     False
472     False
473     False
474     False
475     False
476     False
477     False
478     False
479     False
480     False
481     False
482     False
483     False
484     False
485     False
486     False
487     False
488     False
489     False
490     False
491     False
492     False
493     False
494     False
495     False
496     False
497     False
498     False
499     False
500     False
501     False
502     False
503     False
504     False
505     False
506     False
507     False
508     False
509     False
510     False
511     False
512     False
513     False
514     False
515     False
516     False
517     False
518     False
519     False
520     False
521     False
522     False
523     False
524     False
525     False
526     False
527     False
528     False
529     False
530     False
531     False
532     False
533     False
534     False
535     False
536     False
537     False
538     False
539     False
540     False
541     False
542     False
543     False
544     False
545     False
546     False
547     False
548     False
549     False
550     False
551     False
552     False
553     False
554     False
555     False
556     False
557     False
558     False
559     False
560     False
561     False
562     False
563     False
564     False
565     False
566     False
567     False
568     False
569     False
570     False
571     False
572     False
573     False
574     False
575     False
576     False
577     False
578     False
579     False
580     False
581     False
582     False
583     False
584     False
585     False
586     False
587     False
588     False
589     False
590     False
591     False
592     False
593     False
594     False
595     False
596     False
597     False
598     False
599     False
600     False
601     False
602     False
603     False
604     False
605     False
606     False
607     False
608     False
609     False
610     False
611     False
612     False
613     False
614     False
615     False
616     False
617     False
618     False
619     False
620     False
621     False
622     False
623     False
624     False
625     False
626     False
627     False
628     False
629     False
630     False
631     False
632     False
633     False
634     False
635     False
636     False
637     False
638     False
639     False
640     False
641     False
642     False
643     False
644     False
645     False
646     False
647     False
648     False
649     False
650     False
651     False
652     False
653     False
654     False
655     False
656     False
657     False
658     False
659     False
660     False
661     False
662     False
663     False
664     False
665     False
666     False
667     False
668     False
669     False
670     False
671     False
672     False
673     False
674     False
675     False
676     False
677     False
678     False
679     False
680     False
681     False
682     False
683     False
684     False
685     False
686     False
687     False
688     False
689     False
690     False
691     False
692     False
693     False
694     False
695     False
696     False
697     False
698     False
699     False
700     False
701     False
702     False
703     False
704     False
705     False
706     False
707     False
708     False
709     False
710     False
711     False
712     False
713     False
714     False
715     False
716     False
717     False
718     False
719     False
720     False
721     False
722     False
723     False
724     False
725     False
726     False
727     False
728     False
729     False
730     False
731     False
732     False
733     False
734     False
735     False
736     False
737     False
738     False
739     False
740     False
741     False
742     False
743     False
744     False
745     False
746     False
747     False
748     False
749     False
750     False
751     False
752     False
753     False
754     False
755     False
756     False
757     False
758     False
759     False
760     False
761     False
762     False
763     False
764     False
765     False
766     False
767     False
768     False
769     False
770     False
771     False
772     False
773     False
774     False
775     False
776     False
777     False
778     False
779     False
780     False
781     False
782     False
783     False
784     False
785     False
786     False
787     False
788     False
789     False
790     False
791     False
792     False
793     False
794     False
795     False
796     False
797     False
798     False
799     False
800     False
801     False
802     False
803     False
804     False
805     False
806     False
807     False
808     False
809     False
810     False
811     False
812     False
813     False
814     False
815     False
816     False
817     False
818     False
819     False
820     False
821     False
822     False
823     False
824     False
825     False
826     False
827     False
828     False
829     False
830     False
831     False
832     False
833     False
834     False
835     False
836     False
837     False
838     False
839     False
840     False
841     False
842     False
843     False
844     False
845     False
846     False
847     False
848     False
849     False
850     False
851     False
852     False
853     False
854     False
855     False
856     False
857     False
858     False
859     False
860     False
861     False
862     False
863     False
864     False
865     False
866     False
867     False
868     False
869     False
870     False
871     False
872     False
873     False
874     False
875     False
876     False
877     False
878     False
879     False
880     False
881     False
882     False
883     False
884     False
885     False
886     False
887     False
888     False
889     False
890     False
891     False
892     False
893     False
894     False
895     False
896     False
897     False
898     False
899     False
900     False
901     False
902     False
903     False
904     False
905     False
906     False
907     False
908     False
909     False
910     False
911     False
912     False
913     False
914     False
915     False
916     False
917     False
918     False
919     False
920     False
921     False
922     False
923     False
924     False
925     False
926     False
927     False
928     False
929     False
930     False
931     False
932     False
933     False
934     False
935     False
936     False
937     False
938     False
939     False
940     False
941     False
942     False
943     False
944     False
945     False
946     False
947     False
948     False
949     False
950     False
951     False
952     False
953     False
954     False
955     False
956     False
957     False
958     False
959     False
960     False
961     False
962     False
963     False
964     False
965     False
966     False
967     False
968     False
969     False
970     False
971     False
972     False
973     False
974     False
975     False
976     False
977     False
978     False
979     False
980     False
981     False
982     False
983     False
984     False
985     False
986     False
987     False
988     False
989     False
990     False
991     False
992     False
993     False
994     False
995     False
996     False
997     False
998     False
999     False
1000    False
1001    False
1002    False
1003    False
1004    False
1005    False
1006    False
1007    False
1008    False
1009    False
1010    False
1011    False
1012    False
1013    False
1014    False
1015    False
1016    False
1017    False
1018    False
1019    False
1020    False
1021    False
1022    False
1023    False
1024    False
1025    False
1026    False
1027    False
1028    False
1029    False
1030    False
1031    False
1032    False
1033    False
1034    False
1035    False
1036    False
1037    False
1038    False
1039    False
1040    False
1041    False
1042    False
1043    False
1044    False
1045    False
1046    False
1047    False
1048    False
1049    False
1050    False
1051    False
1052    False
1053    False
1054    False
1055    False
1056    False
1057    False
1058    False
1059    False
1060    False
1061    False
1062    False
1063    False
1064    False
1065    False
1066    False
1067    False
1068    False
1069    False
1070    False
1071    False
1072    False
1073    False
1074    False
1075    False
1076    False
1077    False
1078    False
1079    False
1080    False
1081    False
1082    False
1083    False
1084    False
1085    False
1086    False
1087    False
1088    False
1089    False
1090    False
1091    False
1092    False
1093    False
1094    False
1095    False
1096    False
1097    False
1098    False
1099    False
1100    False
1101    False
1102    False
1103    False
1104    False
1105    False
1106    False
1107    False
1108    False
1109    False
1110    False
1111    False
1112    False
1113    False
1114    False
1115    False
1116    False
1117    False
1118    False
1119    False
1120    False
1121    False
1122    False
1123    False
1124    False
1125    False
1126    False
1127    False
1128    False
1129    False
1130    False
1131    False
1132    False
1133    False
1134    False
1135    False
1136    False
1137    False
1138    False
1139    False
1140    False
1141    False
1142    False
1143    False
1144    False
1145    False
1146    False
1147    False
1148    False
1149    False
1150    False
1151    False
1152    False
1153    False
1154    False
1155    False
1156    False
1157    False
1158    False
1159    False
1160    False
1161    False
1162    False
1163    False
1164    False
1165    False
1166    False
1167    False
1168    False
1169    False
1170    False
1171    False
1172    False
1173    False
1174    False
1175    False
1176    False
1177    False
1178    False
1179    False
1180    False
1181    False
1182    False
1183    False
1184    False
1185    False
1186    False
1187    False
1188    False
1189    False
1190    False
1191    False
1192    False
1193    False
1194    False
1195    False
1196    False
1197    False
1198    False
1199    False
1200    False
1201    False
1202    False
1203    False
1204    False
1205    False
1206    False
1207    False
1208    False
1209    False
1210    False
1211    False
1212    False
1213    False
1214    False
1215    False
1216    False
1217    False
1218    False
1219    False
1220    False
1221    False
1222    False
1223    False
1224    False
1225    False
1226    False
1227    False
1228    False
1229    False
1230    False
1231    False
1232    False
1233    False
1234    False
1235    False
1236    False
1237    False
1238    False
1239    False
1240    False
1241    False
1242    False
1243    False
1244    False
1245    False
1246    False
1247    False
1248    False
1249    False
1250    False
1251    False
1252    False
1253    False
1254    False
1255    False
1256    False
1257    False
1258    False
1259    False
1260    False
1261    False
1262    False
1263    False
1264    False
1265    False
1266    False
1267    False
1268    False
1269    False
1270    False
1271    False
1272    False
1273    False
1274    False
1275    False
1276    False
1277    False
1278    False
1279    False
1280    False
1281    False
1282    False
1283    False
1284    False
1285    False
1286    False
1287    False
1288    False
1289    False
1290    False
1291    False
1292    False
1293    False
1294    False
1295    False
1296    False
1297    False
1298    False
1299    False
1300    False
1301    False
1302    False
1303    False
1304    False
1305    False
1306    False
1307    False
1308    False
1309    False
1310    False
1311    False
1312    False
1313    False
1314    False
1315    False
1316    False
1317    False
1318    False
1319    False
1320    False
1321    False
1322    False
1323    False
1324    False
1325    False
1326    False
1327    False
1328    False
1329    False
1330    False
1331    False
1332    False
1333    False
1334    False
1335    False
1336    False
1337    False
1338    False
1339    False
1340    False
1341    False
1342    False
1343    False
1344    False
1345    False
1346    False
1347    False
1348    False
1349    False
1350    False
1351    False
1352    False
1353    False
1354    False
1355    False
1356    False
1357    False
1358    False
1359    False
1360    False
1361    False
1362    False
1363    False
1364    False
1365    False
1366    False
1367    False
1368    False
1369    False
1370    False
1371    False
1372    False
1373    False
1374    False
1375    False
1376    False
1377    False
1378    False
1379    False
1380    False
1381    False
1382    False
1383    False
1384    False
1385    False
1386    False
1387    False
1388    False
1389    False
1390    False
1391    False
1392    False
1393    False
1394    False
1395    False
1396    False
1397    False
1398    False
1399    False
1400    False
1401    False
1402    False
1403    False
1404    False
1405    False
1406    False
1407    False
1408    False
1409    False
1410    False
1411    False
1412    False
1413    False
1414    False
1415    False
1416    False
1417    False
1418    False
1419    False
1420    False
1421    False
1422    False
1423    False
1424    False
1425    False
1426    False
1427    False
1428    False

In [37]:
df['price_per_sqft'] = df['price_per_sqft'] = (
    df['price_per_sqft']
    .str.split('/')
    .str.get(0)
    .str.replace('₹','', regex=False)
    .str.replace(',','', regex=False)
    .str.strip()
)

df['price_per_sqft'] = pd.to_numeric(df['price_per_sqft'], errors='coerce')

In [38]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [43]:
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
bedRoom          1
Name: count, dtype: int64

In [42]:
df[df['bedRoom'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2850,2 BHK Flat in Sector 107 Gurgaon,Signature Global Solera3.7 ★,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2851,4 BHK Flat in Sector 53 Gurgaon,Tulip Monsella,NaN,33198.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2852,2 BHK Flat in New Palam Vihar,My Home,NaN,4400.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2853,2 BHK Flat in Sohna,Breez Global Hill View,NaN,5470.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2923,3 BHK Flat in Sector 99A Gurgaon,Pareena Coban Residences,NaN,5759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2924,1 BHK Flat in Golf Course Ext Road,ikon tower baani city centre,NaN,12437.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2925,2 BHK Flat in Sector 89 Gurgaon,Greenopolis,NaN,4820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2927,4 BHK Flat in C Block Sushant Lok Phase 1,Maple Heights,NaN,8888.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2928,2 BHK Flat in Sector 99 Gurgaon,Assotech Blith,NaN,6593.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2994,4 BHK Flat in DLF Phase 4,Chanderlok Society,NaN,7234.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2995,3 BHK Flat in Sector 9A Gurgaon,Jammu and Kashmir Bank Employees CGHS3.7 ★,NaN,6129.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2996,3 BHK Flat in Sector 37C Gurgaon,ILD Greens4.1 ★,NaN,4723.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2997,3 BHK Flat in Adarsh Nagar,ss residency,NaN,4818.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2998,3 BHK Flat in Rajendra Park,Uphar lakshya homes,NaN,4200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2999,2 BHK Flat in Sector 79 Gurgaon,Supertech Araville,NaN,9000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3000,3 BHK Flat in Sector 37C Gurgaon,Corona Optus3.9 ★,NaN,6361.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3001,3 BHK Flat in Sector 78 Gurgaon,Umang Monsoon Breeze,NaN,6493.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3002,3 BHK Flat in Sector 88A Gurgaon,Godrej Oasis3.9 ★,NaN,8108.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3003,"2 BHK Flat in Godrej Aria , sector 79 , Gurgaon","Godrej Aria , sector 79 , Gurgaon",NaN,11111.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
df = df[~df['bedRoom'].isnull()]

In [45]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [49]:
df['bathroom'].value_counts()

bathroom
2 Bathrooms    1044
3 Bathrooms     989
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
bathroom          1
Name: count, dtype: int64

In [50]:
df['bathroom'].isnull().sum()

(0       False
 1       False
 2       False
 3       False
 4       False
 5       False
 6       False
 7       False
 8       False
 9       False
 10      False
 11      False
 12      False
 13      False
 14      False
 15      False
 16      False
 17      False
 18      False
 19      False
 20      False
 21      False
 22      False
 23      False
 24      False
 26      False
 27      False
 28      False
 29      False
 30      False
 31      False
 32      False
 33      False
 34      False
 35      False
 36      False
 37      False
 38      False
 39      False
 40      False
 41      False
 42      False
 43      False
 44      False
 45      False
 46      False
 47      False
 48      False
 49      False
 50      False
 51      False
 52      False
 53      False
 54      False
 55      False
 56      False
 57      False
 58      False
 59      False
 60      False
 61      False
 62      False
 63      False
 64      False
 65      False
 66      False
 67      False
 68      False
 69      False
 70      False
 71      False
 72      False
 73      False
 74      False
 75      False
 76      False
 77      False
 78      False
 79      False
 80      False
 81      False
 82      False
 83      False
 84      False
 85      False
 86      False
 87      False
 88      False
 89      False
 90      False
 91      False
 92      False
 93      False
 94      False
 95      False
 96      False
 97      False
 98      False
 99      False
 100     False
 101     False
 102     False
 103     False
 104     False
 105     False
 106     False
 107     False
 108     False
 109     False
 110     False
 111     False
 112     False
 113     False
 114     False
 115     False
 116     False
 117     False
 118     False
 119     False
 120     False
 121     False
 122     False
 123     False
 124     False
 125     False
 126     False
 127     False
 128     False
 129     False
 130     False
 131     False
 132     False
 133     False
 134     False
 135     False
 136     False
 137     False
 138     False
 139     False
 140     False
 141     False
 142     False
 143     False
 144     False
 145     False
 146     False
 147     False
 148     False
 149     False
 150     False
 151     False
 152     False
 153     False
 154     False
 155     False
 156     False
 157     False
 158     False
 159     False
 160     False
 161     False
 162     False
 163     False
 164     False
 165     False
 166     False
 167     False
 168     False
 169     False
 170     False
 171     False
 172     False
 173     False
 174     False
 175     False
 176     False
 177     False
 178     False
 179     False
 180     False
 181     False
 182     False
 183     False
 184     False
 185     False
 186     False
 187     False
 188     False
 189     False
 190     False
 191     False
 192     False
 193     False
 194     False
 195     False
 196     False
 197     False
 198     False
 199     False
 200     False
 201     False
 202     False
 203     False
 204     False
 205     False
 206     False
 207     False
 208     False
 209     False
 210     False
 211     False
 212     False
 213     False
 214     False
 215     False
 216     False
 217     False
 218     False
 219     False
 220     False
 221     False
 222     False
 223     False
 224     False
 225     False
 226     False
 227     False
 228     False
 229     False
 230     False
 231     False
 232     False
 233     False
 234     False
 235     False
 236     False
 237     False
 238     False
 239     False
 240     False
 241     False
 242     False
 243     False
 244     False
 245     False
 246     False
 247     False
 248     False
 249     False
 250     False
 251     False
 252     False
 253     False
 254     False
 255     False
 256     False
 257     False
 258     False
 259     False
 260     False
 261     False
 262     False
 263     False
 264     False
 265     False
 266     False
 267     False
 268     False
 269     False
 270     False
 271     False
 272     False
 273     False
 274     False
 275     False
 276     False
 277     False
 278     False
 279     False
 280     False
 281     False
 282     False
 283     False
 284     False
 285     False
 286     False
 287     False
 288     False
 289     False
 290     False
 291     False
 292     False
 293     False
 294     False
 295     False
 296     False
 297     False
 298     False
 299     False
 300     False
 301     False
 302     False
 303     False
 304     False
 305     False
 306     False
 307     False
 308     False
 309     False
 310     False
 311     False
 312     False
 313     False
 314     False
 315     False
 316     False
 317     False
 318     False
 319     False
 320     False
 321     False
 322     False
 323     False
 324     False
 325     False
 326     False
 327     False
 328     False
 329     False
 330     False
 331     False
 332     False
 333     False
 334     False
 335     False
 336     False
 337     False
 338     False
 339     False
 340     False
 341     False
 342     False
 343     False
 344     False
 345     False
 346     False
 347     False
 348     False
 349     False
 350     False
 351     False
 352     False
 353     False
 354     False
 355     False
 356     False
 357     False
 358     False
 359     False
 360     False
 361     False
 362     False
 363     False
 364     False
 365     False
 366     False
 367     False
 368     False
 369     False
 370     False
 371     False
 372     False
 373     False
 374     False
 375     False
 376     False
 377     False
 378     False
 379     False
 380     False
 381     False
 382     False
 383     False
 384     False
 385     False
 386     False
 387     False
 388     False
 389     False
 390     False
 391     False
 392     False
 393     False
 394     False
 395     False
 396     False
 397     False
 398     False
 399     False
 400     False
 401     False
 402     False
 403     False
 404     False
 405     False
 406     False
 407     False
 408     False
 409     False
 410     False
 411     False
 412     False
 413     False
 414     False
 415     False
 416     False
 417     False
 418     False
 419     False
 420     False
 421     False
 422     False
 423     False
 424     False
 425     False
 426     False
 427     False
 428     False
 429     False
 430     False
 431     False
 432     False
 433     False
 434     False
 435     False
 436     False
 437     False
 438     False
 439     False
 440     False
 441     False
 442     False
 443     False
 444     False
 445     False
 446     False
 447     False
 448     False
 449     False
 450     False
 451     False
 452     False
 453     False
 454     False
 455     False
 456     False
 457     False
 458     False
 459     False
 460     False
 461     False
 462     False
 463     False
 464     False
 465     False
 466     False
 467     False
 468     False
 469     False
 470     False
 471     False
 472     False
 473     False
 474     False
 475     False
 476     False
 477     False
 478     False
 479     False
 480     False
 481     False
 482     False
 483     False
 484     False
 485     False
 486     False
 487     False
 488     False
 489     False
 490     False
 491     False
 492     False
 493     False
 494     False
 495     False
 496     False
 497     False
 498     False
 499     False
 500     False
 501     False
 502     False
 503     False
 504     False
 505     False
 506     False
 507     False
 508     False
 509     False
 510     False
 511     False
 512     False
 513     False
 514     False
 515     False
 516     False
 517     False
 518     False
 519     False
 520     False
 521     False
 522     False
 523     False
 524     False
 525     False
 526     False
 527     False
 528     False
 529     False
 530     False
 531     False
 532     False
 533     False
 534     False
 535     False
 536     False
 537     False
 538     False
 539     False
 540     False
 541     False
 542     False
 543     False
 544     False
 545     False
 546     False
 547     False
 548     False
 549     False
 550     False
 551     False
 552     False
 553     False
 554     False
 555     False
 556     False
 557     False
 558     False
 559     False
 560     False
 561     False
 562     False
 563     False
 564     False
 565     False
 566     False
 567     False
 568     False
 569     False
 570     False
 571     False
 572     False
 573     False
 574     False
 575     False
 576     False
 577     False
 578     False
 579     False
 580     False
 581     False
 582     False
 583     False
 584     False
 585     False
 586     False
 587     False
 588     False
 589     False
 590     False
 591     False
 592     False
 593     False
 594     False
 595     False
 596     False
 597     False
 598     False
 599     False
 600     False
 601     False
 602     False
 603     False
 604     False
 605     False
 606     False
 607     False
 608     False
 609     False
 610     False
 611     False
 612     False
 613     False
 614     False
 615     False
 616     False
 617     False
 618     False
 619     False
 620     False
 621     False
 622     False
 623     False
 624     False
 625     False
 626     False
 627     False
 628     False
 629     False
 630     False
 631     False
 632     False
 633     False
 634     False
 635     False
 636     False
 637     False
 638     False
 639     False
 640     False
 641     False
 642     False
 643     False
 644     False
 645     False
 646     False
 647     False
 648     False
 649     False
 650     False
 651     False
 652     False
 653     False
 654     False
 655     False
 656     False
 657     False
 658     False
 659     False
 660     False
 661     False
 662     False
 663     False
 664     False
 665     False
 666     False
 667     False
 668     False
 669     False
 670     False
 671     False
 672     False
 673     False
 674     False
 675     False
 676     False
 677     False
 678     False
 679     False
 680     False
 681     False
 682     False
 683     False
 684     False
 685     False
 686     False
 687     False
 688     False
 689     False
 690     False
 691     False
 692     False
 693     False
 694     False
 695     False
 696     False
 697     False
 698     False
 699     False
 700     False
 701     False
 702     False
 703     False
 704     False
 705     False
 706     False
 707     False
 708     False
 709     False
 710     False
 711     False
 712     False
 713     False
 714     False
 715     False
 716     False
 717     False
 718     False
 719     False
 720     False
 721     False
 722     False
 723     False
 724     False
 725     False
 726     False
 727     False
 728     False
 729     False
 730     False
 731     False
 732     False
 733     False
 734     False
 735     False
 736     False
 737     False
 738     False
 739     False
 740     False
 741     False
 742     False
 743     False
 744     False
 745     False
 746     False
 747     False
 748     False
 749     False
 750     False
 751     False
 752     False
 753     False
 754     False
 755     False
 756     False
 757     False
 758     False
 759     False
 760     False
 761     False
 762     False
 763     False
 764     False
 765     False
 766     False
 767     False
 768     False
 769     False
 770     False
 771     False
 772     False
 773     False
 774     False
 775     False
 776     False
 777     False
 778     False
 779     False
 780     False
 781     False
 782     False
 783     False
 784     False
 785     False
 786     False
 787     False
 788     False
 789     False
 790     False
 791     False
 792     False
 793     False
 794     False
 795     False
 796     False
 797     False
 798     False
 799     False
 800     False
 801     False
 802     False
 803     False
 804     False
 805     False
 806     False
 807     False
 808     False
 809     False
 810     False
 811     False
 812     False
 813     False
 814     False
 815     False
 816     False
 817     False
 818     False
 819     False
 820     False
 821     False
 822     False
 823     False
 824     False
 825     False
 826     False
 827     False
 828     False
 829     False
 830     False
 831     False
 832     False
 833     False
 834     False
 835     False
 836     False
 837     False
 838     False
 839     False
 840     False
 841     False
 842     False
 843     False
 844     False
 845     False
 846     False
 847     False
 848     False
 849     False
 850     False
 851     False
 852     False
 853     False
 854     False
 855     False
 856     False
 857     False
 858     False
 859     False
 860     False
 861     False
 862     False
 863     False
 864     False
 865     False
 866     False
 867     False
 868     False
 869     False
 870     False
 871     False
 872     False
 873     False
 874     False
 875     False
 876     False
 877     False
 878     False
 879     False
 880     False
 881     False
 882     False
 883     False
 884     False
 885     False
 886     False
 887     False
 888     False
 889     False
 890     False
 891     False
 892     False
 893     False
 894     False
 895     False
 896     False
 897     False
 898     False
 899     False
 900     False
 901     False
 902     False
 903     False
 904     False
 905     False
 906     False
 907     False
 908     False
 909     False
 910     False
 911     False
 912     False
 913     False
 914     False
 915     False
 916     False
 917     False
 918     False
 919     False
 920     False
 921     False
 922     False
 923     False
 924     False
 925     False
 926     False
 927     False
 928     False
 929     False
 930     False
 931     False
 932     False
 933     False
 934     False
 935     False
 936     False
 937     False
 938     False
 939     False
 940     False
 941     False
 942     False
 943     False
 944     False
 945     False
 946     False
 947     False
 948     False
 949     False
 950     False
 951     False
 952     False
 953     False
 954     False
 955     False
 956     False
 957     False
 958     False
 959     False
 960     False
 961     False
 962     False
 963     False
 964     False
 965     False
 966     False
 967     False
 968     False
 969     False
 970     False
 971     False
 972     False
 973     False
 974     False
 975     False
 976     False
 977     False
 978     False
 979     False
 980     False
 981     False
 982     False
 983     False
 984     False
 985     False
 986     False
 987     False
 988     False
 989     False
 990     False
 991     False
 992     False
 993     False
 994     False
 995     False
 996     False
 997     False
 998     False
 999     False
 1000    False
 1001    False
 1002    False
 1003    False
 1004    False
 1005    False
 1006    False
 1007    False
 1008    False
 1009    False
 1010    False
 1011    False
 1012    False
 1013    False
 1014    False
 1015    False
 1016    False
 1017    False
 1018    False
 1019    False
 1020    False
 1021    False
 1022    False
 1023    False
 1024    False
 1025    False
 1026    False
 1027    False
 1028    False
 1029    False
 1030    False
 1031    False
 1032    False
 1033    False
 1034    False
 1035    False
 1036    False
 1037    False
 1038    False
 1039    False
 1040    False
 1041    False
 1042    False
 1043    False
 1044    False
 1045    False
 1046    False
 1047    False
 1048    False
 1049    False
 1050    False
 1051    False
 1052    False
 1053    False
 1054    False
 1055    False
 1056    False
 1057    False
 1058    False
 1059    False
 1060    False
 1061    False
 1062    False
 1063    False
 1064    False
 1065    False
 1066    False
 1067    False
 1068    False
 1069    False
 1070    False
 1071    False
 1072    False
 1073    False
 1074    False
 1075    False
 1076    False
 1077    False
 1078    False
 1079    False
 1080    False
 1081    False
 1082    False
 1083    False
 1084    False
 1085    False
 1086    False
 1087    False
 1088    False
 1089    False
 1090    False
 1091    False
 1092    False
 1093    False
 1094    False
 1095    False
 1096    False
 1097    False
 1098    False
 1099    False
 1100    False
 1101    False
 1102    False
 1103    False
 1104    False
 1105    False
 1106    False
 1107    False
 1108    False
 1109    False
 1110    False
 1111    False
 1112    False
 1113    False
 1114    False
 1115    False
 1116    False
 1117    False
 1118    False
 1119    False
 1120    False
 1121    False
 1122    False
 1123    False
 1124    False
 1125    False
 1126    False
 1127    False
 1128    False
 1129    False
 1130    False
 1131    False
 1132    False
 1133    False
 1134    False
 1135    False
 1136    False
 1137    False
 1138    False
 1139    False
 1140    False
 1141    False
 1142    False
 1143    False
 1144    False
 1145    False
 1146    False
 1147    False
 1148    False
 1149    False
 1150    False
 1151    False
 1152    False
 1153    False
 1154    False
 1155    False
 1156    False
 1157    False
 1158    False
 1159    False
 1160    False
 1161    False
 1162    False
 1163    False
 1164    False
 1165    False
 1166    False
 1167    False
 1168    False
 1169    False
 1170    False
 1171    False
 1172    False
 1173    False
 1174    False
 1175    False
 1176    False
 1177    False
 1178    False
 1179    False
 1180    False
 1181    False
 1182    False
 1183    False
 1184    False
 1185    False
 1186    False
 1187    False
 1188    False
 1189    False
 1190    False
 1191    False
 1192    False
 1193    False
 1194    False
 1195    False
 1196    False
 1197    False
 1198    False
 1199    False
 1200    False
 1201    False
 1202    False
 1203    False
 1204    False
 1205    False
 1206    False
 1207    False
 1208    False
 1209    False
 1210    False
 1211    False
 1212    False
 1213    False
 1214    False
 1215    False
 1216    False
 1217    False
 1218    False
 1219    False
 1220    False
 1221    False
 1222    False
 1223    False
 1224    False
 1225    False
 1226    False
 1227    False
 1228    False
 1229    False
 1230    False
 1231    False
 1232    False
 1233    False
 1234    False
 1235    False
 1236    False
 1237    False
 1238    False
 1239    False
 1240    False
 1241    False
 1242    False
 1243    False
 1244    False
 1245    False
 1246    False
 1247    False
 1248    False
 1249    False
 1250    False
 1251    False
 1252    False
 1253    False
 1254    False
 1255    False
 1256    False
 1257    False
 1258    False
 1259    False
 1260    False
 1261    False
 1262    False
 1263    False
 1264    False
 1265    False
 1266    False
 1267    False
 1268    False
 1269    False
 1270    False
 1271    False
 1272    False
 1273    False
 1274    False
 1275    False
 1276    False
 1277    False
 1278    False
 1279    False
 1280    False
 1281    False
 1282    False
 1283    False
 1284    False
 1285    False
 1286    False
 1287    False
 1288    False
 1289    False
 1290    False
 1291    False
 1292    False
 1293    False
 1294    False
 1295    False
 1296    False
 1297    False
 1298    False
 1299    False
 1300    False
 1301    False
 1302    False
 1303    False
 1304    False
 1305    False
 1306    False
 1307    False
 1308    False
 1309    False
 1310    False
 1311    False
 1312    False
 1313    False
 1314    False
 1315    False
 1316    False
 1317    False
 1318    False
 1319    False
 1320    False
 1321    False
 1322    False
 1323    False
 1324    False
 1325    False
 1326    False
 1327    False
 1328    False
 1329    False
 1330    False
 1331    False
 1332    False
 1333    False

In [51]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [53]:
df['bathroom'] = pd.to_numeric(
    df['bathroom'].str.split(' ').str.get(0),
    errors='coerce'
)

/tmp/ipykernel_1095/3491363460.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['bathroom'] = pd.to_numeric(

In [57]:
df['bedRoom'] = pd.to_numeric(
    df['bedRoom'].str.split(' ').str.get(0),
    errors='coerce'
)

/tmp/ipykernel_1095/258852309.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['bedRoom'] = pd.to_numeric(

In [58]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2.0,2.0,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2.0,2.0,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2.0,2.0,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2.0,2.0,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2.0,2.0,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [63]:
df['balcony'].value_counts()

balcony
3.0    974
2.0    749
1.0    315
Name: count, dtype: int64

In [60]:
df['balcony'].isnull().sum()

np.int64(0)

In [61]:
df['balcony'] = pd.to_numeric(
    df['balcony'].str.split(' ').str.get(0),
    errors='coerce'
)

/tmp/ipykernel_1095/2915569885.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balcony'] = pd.to_numeric(

In [62]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2.0,2.0,1.0,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2.0,2.0,1.0,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2.0,2.0,3.0,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2.0,2.0,2.0,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2.0,2.0,3.0,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [64]:
df['balcony'].value_counts()

balcony
3.0    974
2.0    749
1.0    315
Name: count, dtype: int64

In [65]:
df['additionalRoom'].value_counts().shape

(50,)

In [66]:
df['additionalRoom'].isnull().sum()

np.int64(1305)

In [67]:
df['additionalRoom'].fillna('not available',inplace=True)

/tmp/ipykernel_1095/1615843200.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['additionalRoom'].fillna('not available',inplace=True)
/tmp/ipykernel_1095/1615843200.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['additionalRoom'].fillna('not available',inplace=True)

In [68]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

/tmp/ipykernel_1095/4218856625.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['additionalRoom'] = df['additionalRoom'].str.lower()

In [69]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2.0,2.0,1.0,not available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2.0,2.0,1.0,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2.0,2.0,3.0,not available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2.0,2.0,2.0,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2.0,2.0,3.0,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [70]:
df['additionalRoom'].value_counts()

additionalRoom
not available                                    1305
servant room                                      629
study room                                        232
others                                            179
pooja room                                        132
study room,servant room                            81
store room                                         76
pooja room,servant room                            60
servant room,others                                52
servant room,pooja room                            30
study room,others                                  27
pooja room,study room,servant room,others          25
pooja room,study room,servant room                 24
servant room,store room                            19
pooja room,study room                              13
pooja room,study room,servant room,store room      12
servant room,study room                             8
study room,pooja room                               8
study room,servant room,store room                  7
others,servant room                                 6
pooja room,servant room,others                      6
servant room,study room,pooja room,store room       6
pooja room,others                                   6
pooja room,store room                               6
study room,servant room,others                      5
pooja room,study room,store room                    4
pooja room,store room,study room,servant room       4
study room,pooja room,store room                    3
servant room,pooja room,study room,store room       3
store room,servant room                             3
servant room,others,pooja room                      2
servant room,others,store room,pooja room           2
study room,servant room,pooja room,store room       2
servant room,study room,store room                  2
study room,pooja room,servant room                  2
pooja room,study room,others                        2
additionalroom                                      1
store room,pooja room,servant room                  1
pooja room,study room,store room,servant room       1
pooja room,servant room,study room,store room       1
servant room,pooja room,store room                  1
study room,servant room,store room,pooja room       1
study room,servant room,pooja room                  1
servant room,pooja room,store room,study room       1
study room,store room                               1
store room,study room                               1
servant room,pooja room,study room                  1
servant room,study room,pooja room                  1
others,study room                                   1
servant room,study room,others                      1
store room,pooja room                               1
Name: count, dtype: int64

In [71]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2.0,2.0,1.0,not available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2.0,2.0,1.0,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2.0,2.0,3.0,not available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2.0,2.0,2.0,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2.0,2.0,3.0,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [72]:
df['floorNum']

0              4th   of 4 Floors
1              1st   of 3 Floors
2            12nd   of 14 Floors
3              2nd   of 4 Floors
4              5th   of 8 Floors
5              3rd   of 3 Floors
6             5th   of 25 Floors
7            14th   of 27 Floors
8              2nd   of 3 Floors
9            31st   of 40 Floors
10             1st   of 4 Floors
11            4th   of 13 Floors
12            4th   of 15 Floors
13            3rd   of 20 Floors
14           13rd   of 13 Floors
15           25th   of 25 Floors
16            Ground of 1 Floors
17           Ground of 14 Floors
18           11st   of 14 Floors
19           12nd   of 13 Floors
20             4th   of 4 Floors
21           11st   of 22 Floors
22             4th   of 4 Floors
23           Ground of 14 Floors
24           10th   of 25 Floors
26             3rd   of 3 Floors
27           20th   of 20 Floors
28            5th   of 17 Floors
29            4th   of 12 Floors
30             4th   of 4 Floors
31             1st   of 4 Floors
32           12nd   of 12 Floors
33            8th   of 12 Floors
34           20th   of 20 Floors
35             8th   of 8 Floors
36           21st   of 24 Floors
37           Ground of 11 Floors
38            6th   of 19 Floors
39            1st   of 19 Floors
40             1st   of 3 Floors
41           12nd   of 17 Floors
42            6th   of 24 Floors
43            1st   of 25 Floors
44             2nd   of 4 Floors
45             1st   of 4 Floors
46            9th   of 29 Floors
47             5th   of 8 Floors
48           18th   of 32 Floors
49           29th   of 31 Floors
50             3rd   of 5 Floors
51            3rd   of 26 Floors
52            5th   of 18 Floors
53             1st   of 4 Floors
54            9th   of 12 Floors
55            6th   of 10 Floors
56             2nd   of 4 Floors
57           14th   of 14 Floors
58            1st   of 11 Floors
59            8th   of 14 Floors
60             2nd   of 2 Floors
61           12nd   of 12 Floors
62            4th   of 14 Floors
63            1st   of 18 Floors
64            7th   of 19 Floors
65             3rd   of 4 Floors
66            5th   of 20 Floors
67            9th   of 15 Floors
68           14th   of 17 Floors
69           14th   of 14 Floors
70           15th   of 20 Floors
71            6th   of 14 Floors
72            6th   of 14 Floors
73            2nd   of 12 Floors
74            3rd   of 11 Floors
75             2nd   of 4 Floors
76            4th   of 13 Floors
77             3rd   of 4 Floors
78            6th   of 14 Floors
79            8th   of 13 Floors
80             2nd   of 4 Floors
81             4th   of 4 Floors
82           Ground of 14 Floors
83           11st   of 11 Floors
84             1st   of 3 Floors
85           11st   of 13 Floors
86           21st   of 41 Floors
87            4th   of 13 Floors
88             2nd   of 5 Floors
89             2nd   of 3 Floors
90             4th   of 4 Floors
91           32nd   of 32 Floors
92             2nd   of 4 Floors
93             2nd   of 2 Floors
94             2nd   of 2 Floors
95           11st   of 11 Floors
96           23rd   of 26 Floors
97            6th   of 12 Floors
98            9th   of 20 Floors
99             1st   of 4 Floors
100           5th   of 15 Floors
101            43   of 47 Floors
102            1st   of 1 Floors
103            1st   of 4 Floors
104           1st   of 13 Floors
105          11st   of 12 Floors
106          14th   of 24 Floors
107           9th   of 30 Floors
108           8th   of 14 Floors
109            9th   of 9 Floors
110           2nd   of 12 Floors
111           4th   of 14 Floors
112          32nd   of 55 Floors
113            43   of 47 Floors
114           2nd   of 19 Floors
115            3rd   of 4 Floors
116           8th   of 22 Floors
117            3rd   of 4 Floors
118          20th   of 32 Floors
119           2nd   of 17 Floors
120        Basement of 28 Floors
121           4th   of 10 Floors
122           Ground of 4 Floors
123            3rd   of 4 Floors
124            4th   of 8 Floors
125            3rd   of 4 Floors
126           6th   of 20 Floors
127          13rd   of 13 Floors
128          13rd   of 13 Floors
129          16th   of 16 Floors
130            3rd   of 4 Floors
131           Ground of 1 Floors
132          11st   of 14 Floors
133           2nd   of 14 Floors
134          12nd   of 12 Floors
135            2nd   of 4 Floors
136           1st   of 18 Floors
137           4th   of 12 Floors
138          11st   of 13 Floors
139           5th   of 17 Floors
140           1st   of 25 Floors
141          12nd   of 16 Floors
142          16th   of 18 Floors
143            6th   of 6 Floors
144            2nd   of 2 Floors
145            3rd   of 4 Floors
146          11st   of 25 Floors
147          10th   of 18 Floors
148           2nd   of 25 Floors
149            4th   of 4 Floors
150          19th   of 41 Floors
151            1st   of 3 Floors
152            8th   of 8 Floors
153          18th   of 19 Floors
154          10th   of 16 Floors
155           7th   of 20 Floors
156           2nd   of 14 Floors
157          10th   of 10 Floors
158           5th   of 12 Floors
159          10th   of 20 Floors
160          20th   of 34 Floors
161          20th   of 22 Floors
162            3rd   of 4 Floors
163          13rd   of 14 Floors
164           3rd   of 19 Floors
165           7th   of 18 Floors
166            4th   of 4 Floors
167           4th   of 14 Floors
168            2nd   of 4 Floors
169           2nd   of 25 Floors
170           4th   of 14 Floors
171           3rd   of 19 Floors
172            1st   of 1 Floors
173            2nd   of 4 Floors
174          11st   of 15 Floors
175          11st   of 21 Floors
176          16th   of 22 Floors
177           8th   of 10 Floors
178           1st   of 35 Floors
179          18th   of 25 Floors
180           8th   of 15 Floors
181                          NaN
182           2nd   of 16 Floors
183          17th   of 17 Floors
184          23rd   of 28 Floors
185          10th   of 18 Floors
186          30th   of 32 Floors
187            4th   of 4 Floors
188            2nd   of 3 Floors
189           Ground of 3 Floors
190          Ground of 14 Floors
191            1st   of 4 Floors
192            1st   of 1 Floors
193          11st   of 36 Floors
194          11st   of 13 Floors
195           Ground of 3 Floors
196          19th   of 19 Floors
197          28th   of 28 Floors
198            4th   of 4 Floors
199            9th   of 9 Floors
200            7th   of 7 Floors
201         Basement of 4 Floors
202          15th   of 15 Floors
203           2nd   of 34 Floors
204          Ground of 14 Floors
205           9th   of 10 Floors
206           1st   of 15 Floors
207            1st   of 1 Floors
208           4th   of 34 Floors
209           4th   of 18 Floors
210           3rd   of 15 Floors
211            1st   of 4 Floors
212           1st   of 19 Floors
213     Lower Ground of 4 Floors
214          13rd   of 13 Floors
215           4th   of 40 Floors
216           6th   of 18 Floors
217          20th   of 47 Floors
218          27th   of 48 Floors
219            6th   of 7 Floors
220          33rd   of 48 Floors
221          35th   of 35 Floors
222          26th   of 47 Floors
223           Ground of 1 Floors
224            2nd   of 4 Floors
225           4th   of 14 Floors
226          10th   of 17 Floors
227          11st   of 14 Floors
228          10th   of 22 Floors
229          Ground of 24 Floors
230           3rd   of 12 Floors
231           7th   of 25 Floors
232           8th   of 14 Floors
233            2nd   of 4 Floors
234           3rd   of 18 Floors
235            1st   of 4 Floors
236           9th   of 14 Floors
237          14th   of 15 Floors
238            4th   of 4 Floors
239           8th   of 25 Floors
240          10th   of 14 Floors
241           3rd   of 14 Floors
242            3rd   of 4 Floors
243            2nd   of 4 Floors
244           3rd   of 14 Floors
245            7th   of 7 Floors
246            2nd   of 4 Floors
247           3rd   of 15 Floors
248           8th   of 34 Floors
249          12nd   of 14 Floors
250           8th   of 42 Floors
251            1st   of 4 Floors
252           1st   of 22 Floors
253          26th   of 34 Floors
254          21st   of 29 Floors
255           8th   of 32 Floors
256           2nd   of 14 Floors
257           1st   of 12 Floors
258            2nd   of 4 Floors
259          39th   of 40 Floors
260           1st   of 14 Floors
261           8th   of 10 Floors
262            2nd   of 3 Floors
263            3rd   of 4 Floors
264            7th   of 9 Floors
265           4th   of 15 Floors
266          22nd   of 24 Floors
267          14th   of 20 Floors
268          11st   of 15 Floors
269          17th   of 17 Floors
270           3rd   of 12 Floors
271          12nd   of 13 Floors
272           8th   of 19 Floors
273           3rd   of 14 Floors
274          14th   of 14 Floors
275            7th   of 7 Floors
276           9th   of 15 Floors
277           2nd   of 17 Floors
278            3rd   of 3 Floors
279            6th   of 6 Floors
280          16th   of 16 Floors
281          12nd   of 12 Floors
282            1st   of 1 Floors
283            4th   of 4 Floors
284          17th   of 17 Floors
285           7th   of 26 Floors
286                     floorNum
287          11st   of 30 Floors
288            4th   of 8 Floors
289           1st   of 14 Floors
290           6th   of 14 Floors
291            1st   of 3 Floors
292          17th   of 17 Floors
293            1st   of 7 Floors
294          16th   of 18 Floors
295          19th   of 40 Floors
296          31st   of 32 Floors
297          14th   of 22 Floors
298           5th   of 19 Floors
299            2nd   of 4 Floors
300            1st   of 4 Floors
301           1st   of 10 Floors
302          15th   of 32 Floors
303            1st   of 7 Floors
304            1st   of 2 Floors
305            2nd   of 3 Floors
306          11st   of 14 Floors
307           9th   of 26 Floors
308          33rd   of 42 Floors
309          14th   of 18 Floors
310            4th   of 4 Floors
311           5th   of 14 Floors
312          18th   of 18 Floors
313           1st   of 14 Floors
314          20th   of 23 Floors
315           9th   of 14 Floors
316          18th   of 19 Floors
317           8th   of 32 Floors
318           4th   of 15 Floors
319           9th   of 17 Floors
320            4th   of 8 Floors
321           1st   of 14 Floors
322           6th   of 14 Floors
323            1st   of 3 Floors
324          19th   of 40 Floors
325          31st   of 32 Floors
326           5th   of 19 Floors
327            1st   of 4 Floors
328           1st   of 10 Floors
329          15th   of 32 Floors
330            1st   of 7 Floors
331            1st   of 2 Floors
332            2nd   of 3 Floors
333          11st   of 14 Floors
334           9th   of 26 Floors
335          14th   of 18 Floors
336           5th   of 14 Floors
337           1st   of 14 Floors
338           9th   of 14 Floors
339          18th   of 19 Floors
340           4th   of 15 Floors
341           1st   of 44 Floors
342          20th   of 20 Floors
343          24th   of 31 Floors
344           2nd   of 15 Floors
345            4th   of 4 Floors
346          14th   of 14 Floors
347           9th   of 16 Floors
348          14th   of 15 Floors
349           4th   of 14 Floors
350          26th   of 30 Floors
351           2nd   of 16 Floors
352          14th   of 24 Floors
353          17th   of 17 Floors
354           2nd   of 14 Floors
355          25th   of 25 Floors
356           9th   of 22 Floors
357            4th   of 4 Floors
358           6th   of 17 Floors
359           5th   of 14 Floors
360           4th   of 14 Floors
361          14th   of 21 Floors
362          15th   of 19 Floors
363           7th   of 14 Floors
364            2nd   of 4 Floors
365          16th   of 20 Floors
366          24th   of 51 Floors
367          10th   of 20 Floors
368            2nd   of 4 Floors
369           2nd   of 12 Floors
370           2nd   of 24 Floors
371           1st   of 19 Floors
372           8th   of 18 Floors
373          12nd   of 22 Floors
374          18th   of 19 Floors
375            1st   of 4 Floors
376           2nd   of 36 Floors
377            3rd   of 4 Floors
378          11st   of 11 Floors
379           7th   of 20 Floors
380           5th   of 18 Floors
381           6th   of 12 Floors
382          19th   of 31 Floors
383          25th   of 25 Floors
384          10th   of 10 Floors
385          10th   of 10 Floors
386            3rd   of 9 Floors
387           8th   of 14 Floors
388           5th   of 12 Floors
389           4th   of 22 Floors
390           1st   of 35 Floors
391          10th   of 14 Floors
392          16th   of 24 Floors
393          10th   of 14 Floors
394            3rd   of 8 Floors
395          17th   of 19 Floors
396           9th   of 14 Floors
397          11st   of 26 Floors
398          19th   of 20 Floors
399          Ground of 16 Floors
400          Ground of 23 Floors
401           8th   of 26 Floors
402           4th   of 11 Floors
403          30th   of 32 Floors
404          16th   of 51 Floors
405          18th   of 21 Floors
406           2nd   of 10 Floors
407           7th   of 10 Floors
408            2nd   of 4 Floors
409          10th   of 10 Floors
410           9th   of 12 Floors
411           6th   of 10 Floors
412          14th   of 29 Floors
413          25th   of 36 Floors
414           7th   of 23 Floors
415           4th   of 14 Floors
416            7th   of 9 Floors
417          18th   of 32 Floors
418          12nd   of 17 Floors
419            3rd   of 4 Floors
420          21st   of 28 Floors
421          14th   of 28 Floors
422           5th   of 25 Floors
423           3rd   of 19 Floors
424          19th   of 24 Floors
425          10th   of 14 Floors
426            5th   of 9 Floors
427          10th   of 30 Floors
428           7th   of 14 Floors
429          11st   of 20 Floors
430           2nd   of 17 Floors
431            2nd   of 4 Floors
432           7th   of 14 Floors
433           6th   of 14 Floors
434          11st   of 17 Floors
435           9th   of 14 Floors
436            4th   of 4 Floors
437          14th   of 20 Floors
438            5th   of 5 Floors
439            1st   of 4 Floors
440          16th   of 27 Floors
441           1st   of 10 Floors
442          18th   of 32 Floors
443           6th   of 16 Floors
444           8th   of 13 Floors
445            4th   of 4 Floors
446           7th   of 27 Floors
447            9th   of 9 Floors
448            3rd   of 4 Floors
449          11st   of 18 Floors
450          17th   of 25 Floors
451           7th   of 42 Floors
452           5th   of 30 Floors
453          16th   of 32 Floors
454           2nd   of 16 Floors
455           8th   of 29 Floors
456            2nd   of 8 Floors
457           3rd   of 32 Floors
458           6th   of 26 Floors
459          Ground of 14 Floors
460           2nd   of 12 Floors
461          15th   of 40 Floors
462          10th   of 25 Floors
463          11st   of 30 Floors
464          10th   of 15 Floors
465           4th   of 12 Floors
466           3rd   of 18 Floors
467           9th   of 19 Floors
468           8th   of 16 Floors
469           7th   of 12 Floors
470           5th   of 12 Floors
471           7th   of 14 Floors
472           7th   of 14 Floors
473           9th   of 14 Floors
474           2nd   of 20 Floors
475           5th   of 18 Floors
476          11st   of 20 Floors
477           8th   of 11 Floors
478           7th   of 17 Floors
479          20th   of 26 Floors
480          10th   of 12 Floors
481           7th   of 29 Floors
482          10th   of 51 Floors
483          16th   of 21 Floors
484           8th   of 21 Floors
485           1st   of 14 Floors
486          18th   of 30 Floors
487          15th   of 30 Floors
488          25th   of 30 Floors
489           5th   of 29 Floors
490           9th   of 26 Floors
491           5th   of 26 Floors
492           7th   of 26 Floors
493           7th   of 26 Floors
494           7th   of 26 Floors
495          12nd   of 30 Floors
496           5th   of 15 Floors
497           4th   of 10 Floors
498           6th   of 10 Floors
499            3rd   of 6 Floors
500          10th   of 18 Floors
501          15th   of 28 Floors
502          15th   of 28 Floors
503          10th   of 14 Floors
504           9th   of 28 Floors
505          10th   of 15 Floors
506          10th   of 21 Floors
507           9th   of 12 Floors
508           Ground of 4 Floors
509            1st   of 2 Floors
510          11st   of 12 Floors
511          17th   of 24 Floors
512           1st   of 26 Floors
513          Ground of 18 Floors
514           7th   of 14 Floors
515            5th   of 8 Floors
516          12nd   of 29 Floors
517          14th   of 29 Floors
518          14th   of 29 Floors
519           9th   of 21 Floors
520          19th   of 29 Floors
521           8th   of 14 Floors
522          14th   of 29 Floors
523           8th   of 14 Floors
524            2nd   of 5 Floors
525           9th   of 13 Floors
526           5th   of 14 Floors
527          Ground of 14 Floors
528            6th   of 8 Floors
529          10th   of 19 Floors
530           6th   of 10 Floors
531           8th   of 18 Floors
532           9th   of 24 Floors
533           9th   of 26 Floors
534          12nd   of 17 Floors
535          11st   of 16 Floors
536           6th   of 16 Floors
537          15th   of 39 Floors
538           7th   of 12 Floors
539           8th   of 19 Floors
540           8th   of 26 Floors
541           3rd   of 26 Floors
542          10th   of 26 Floors
543           1st   of 26 Floors
544           4th   of 26 Floors
545           5th   of 12 Floors
546           2nd   of 12 Floors
547          20th   of 40 Floors
548          13rd   of 40 Floors
549           8th   of 40 Floors
550           8th   of 19 Floors
551          16th   of 19 Floors
552          12nd   of 18 Floors
553          10th   of 19 Floors
554           6th   of 15 Floors
555          16th   of 19 Floors
556           8th   of 16 Floors
557          12nd   of 15 Floors
558          12nd   of 18 Floors
559           5th   of 22 Floors
560           9th   of 42 Floors
561           7th   of 14 Floors
562           7th   of 12 Floors
563           7th   of 12 Floors
564           5th   of 16 Floors
565           8th   of 31 Floors
566           7th   of 21 Floors
567           5th   of 29 Floors
568           9th   of 30 Floors
569          11st   of 29 Floors
570          10th   of 19 Floors
571           6th   of 31 Floors
572            3rd   of 9 Floors
573          22nd   of 30 Floors
574           5th   of 20 Floors
575          15th   of 29 Floors
576           5th   of 14 Floors
577          Ground of 14 Floors
578           6th   of 14 Floors
579           1st   of 24 Floors
580            2nd   of 8 Floors
581          12nd   of 19 Floors
582          12nd   of 25 Floors
583           6th   of 17 Floors
584           8th   of 18 Floors
585            4th   of 5 Floors
586           5th   of 25 Floors
587           2nd   of 19 Floors
588          20th   of 30 Floors
589          12nd   of 14 Floors
590          18th   of 19 Floors
591           2nd   of 26 Floors
592           3rd   of 15 Floors
593           3rd   of 19 Floors
594          18th   of 51 Floors
595           7th   of 27 Floors
596          17th   of 19 Floors
597           8th   of 14 Floors
598           2nd   of 19 Floors
599           8th   of 19 Floors
600           9th   of 30 Floors
601           3rd   of 18 Floors
602          12nd   of 23 Floors
603          10th   of 28 Floors
604            2nd   of 5 Floors
605          Ground of 21 Floors
606           7th   of 16 Floors

In [73]:
df['floorNum'].isnull().sum()

np.int64(2)

In [75]:
df[df['floorNum'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
181,3 BHK Flat in Dwarka Expressway Gurgaon,Experion Heartsong,1.08,6150.0,Built Up area: 1758 (163.32 sq.m.),3.0,3.0,NaN,not available,"604, Tower B-3, 6th Floor,Sector 108, Dwarka E...",NaN,NaN,Under Construction,NaN,A property by one of the most reputed builders...,[],NaN,NaN
2767,2 BHK Flat in Sector 78 Gurgaon,NaN,0.60,3692.0,Built Up area: 1625 (150.97 sq.m.),2.0,2.0,NaN,not available,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [76]:
df['floorNum'] = df['floorNum'].str.split(' ').str.get(0).replace('Ground','0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

/tmp/ipykernel_1095/208426714.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['floorNum'] = df['floorNum'].str.split(' ').str.get(0).replace('Ground','0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

In [77]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2.0,2.0,1.0,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2.0,2.0,1.0,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2.0,2.0,3.0,not available,"Sohna, Gurgaon, Haryana",12,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2.0,2.0,2.0,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2.0,2.0,3.0,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [78]:
df['facing'].value_counts()

facing
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
facing          1
Name: count, dtype: int64

In [79]:
df['facing'].isnull().sum()

np.int64(874)

In [80]:
df['facing'].fillna('NA',inplace=True)

/tmp/ipykernel_1095/3692945726.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('NA',inplace=True)
/tmp/ipykernel_1095/3692945726.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['facing'].fillna('NA',inplace=True)

In [81]:
df['facing'].value_counts()

facing
NA            874
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
facing          1
Name: count, dtype: int64

In [82]:
df.insert(loc=4,column='area',value=round((df['price']*10000000)/df['price_per_sqft']))

In [83]:
df.insert(loc=1,column='property_type',value='flat')

In [85]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2.0,2.0,1.0,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,Apna Enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2.0,2.0,1.0,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,Tulsiani Easy in Homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2.0,2.0,3.0,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,Smart World Orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2.0,2.0,2.0,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,Parkwood Westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2.0,2.0,3.0,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2998 entries, 0 to 3027
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2998 non-null   object
 1   property_type    2998 non-null   object
 2   society          2997 non-null   object
 3   price            2996 non-null   float64
 4   price_per_sqft   2996 non-null   float64
 5   area             2996 non-null   float64
 6   areaWithType     2998 non-null   object
 7   bedRoom          2997 non-null   float64
 8   bathroom         2997 non-null   float64
 9   balcony          2038 non-null   float64
 10  additionalRoom   2998 non-null   object
 11  address          2992 non-null   object
 12  floorNum         2995 non-null   object
 13  facing           2998 non-null   object
 14  agePossession    2997 non-null   object
 15  nearbyLocations  2907 non-null   object
 16  description      2998 non-null   object
 17  furnishDetails   2201 non-null   object
 18  features         2591 non-null   object
 19  rating           2669 non-null   object
dtypes: float64(6), object(14)
memory usage: 491.9+ KB

In [88]:
df.shape

(2998, 20)

In [89]:
df.to_csv('flats_cleaned.csv',index=False)